### ISSUE TITLE
problem reading pdf and .txt file

### ISSUE THREAD

**Issue by emanueleiacca** [cheshire-cat-ai/core#112]
hi, i'm a student learning machine learning through your yt video so i had to try your ceshire-cat: i'm having problem in uploading .txt or pdf file, the program is not able to read the content and i think there is some incompability between my data and the way the software receive, it seams like he receive the data full of simbols, like it's some sort of html data and it's not able to read it. can you help me understand this problem pls? i created the .txt file in block note so there shouldn't be any problem with the format
thanks for your work
emanuele

**Comment by pieroit** [comment]
Can you try again? We fixed a few bugs.
Also, this is the new tutorial for installation:
https://youtu.be/Rvx19TZBCrw
