### ISSUE TITLE
Rest API backend query

### ISSUE THREAD

**Issue by xdatap1** [cheshire-cat-ai/core#118]
To increase the integrability of the backend we would benefit from a REST API.

The use case I encounter this need is when I tried to develop an Apple Shortcut (https://support.apple.com/guide/shortcuts-mac/welcome/6.0/mac) to query cheshire cat from siri with voice that support only rest apis. I solved it using websocat (https://github.com/vi/websocat) that allows to websocket query from command line, but this solutions works only on mac.

If we had a Rest API, we could do that also from iphone and ipads from the same network, using this: https://support.apple.com/guide/shortcuts/request-your-first-api-apd58d46713f/ios

**Comment by pieroit** [comment]
Closing this issue as we use websocket as chat and notification protocol, http for all other endpoints
