### ISSUE TITLE
Problems with Real Time tools

### ISSUE THREAD

**Issue by marcocagnoli** [cheshire-cat-ai/core#130]
I'm playing with a plugin retrieving real time data for transit information. I connect the tool to an external API to get data. I noticed some problems. Tha cat uses all previous questions and aswers to build the answer for my request, moreover he uses also loaded documents. I know this is the general expected behaviour, anyway for my use case this is a problem: often, when I ask for arriving buses, he doesn't use my plugin but he builds a plausible answer (also formatted as the real one) by generating "fake" information. For example, he associated a square in Forlì to a Rome bus stop (I never mentioned that square name, neither in the loaded document). I decorated the plugin with "@tool(return_direct=True)", so I guess that sometimes he doesn't use the plugin at all, otherwise I should obtain the right answer.

**Comment by pieroit** [comment]
@marcocagnoli can I close this?
It is possible to change cat context in two different ways:
- via hooks (as you already did)
- via endpoint (there is a new DELETE endpoint `/working-memory/conversation-history/` that allows you to clear conversation history, we'll make also a button in the chat for it)
