### ISSUE TITLE
Custom (local) LLM and Embedder

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#184]
Custom LLMs should be supported from the Cat as any other LLM, via a [Config class](https://github.com/pieroit/cheshire-cat/blob/main/core/cat/factory/llm.py). Same goes for a [custom embedder](https://github.com/pieroit/cheshire-cat/blob/main/core/cat/factory/embedder.py).
Config classes should in turn refer to subclasses of langchain.llms.base.LLM and langchain.embeddings.Embeddings that make the actual request.

User can configure a custom endpoint with two parameters:
* `url`
* (optional) `auth_key`
* (optional) `options`

## LLM

When the cat needs the LLM will launch a POST request to `url` with this payload:

```json
{
    "text": "...prompt...",
    "options": {  "custom_option_a": 35 },
    "auth_key": "some_auth_key"
}
```

The LLM service should return:

```json
{
    "text": "...generated text..."
}
```

## Embedder

When the cat needs to embed text will make a POST request to `url`:

```json
{
    "text": "...text to embed...",
    "options": {  "custom_option_a": 35 },
    "auth_key": "some_auth_key"
}
```

The embedder service should return:

```json
{
    "embedding": [0.3, -0.5, 1.0, -0.2]
}
```

In this way attaching a new LLM to the Cat is simply a matter of giving the admin an `url` and having a local or remote webserver hosting the model and respecting this contract.

Tell me what you think

**Comment by AlessandroSpallina** [comment]
If someone is searching for a code snippet, here's an example of a REST API server using Llama 2 as LLM:
```python
from fastapi import FastAPI
from pydantic import BaseModel
from llama_cpp import Llama


class Item(BaseModel):
    text: str
    auth_key: str | None = None
    option: dict | None = None


app = FastAPI()

# customize your model path here, if you use llama 70b remember to use n_gpa=8, leave it default otherwise
llm = Llama(model_path="/home/skela/llama.cpp/models/llama-2-13b-chat-f16-q8_0.bin", n_ctx=2048)
# llm = Llama(model_path="/home/skela/llama.cpp/models/llama-2-70b-chat-f16-q4_0.bin", n_gqa=8, n_ctx=2048)


@app.get("/custom-llm")
async def test_get():
    return {"message": "Here we are folks!"}


@app.post("/custom-llm")
async def root(item: Item):
    answer = llm(item.text, max_tokens=0)
    print(answer)
    return {"text": answer['choices'][0]['text']}
```

thanks @nicola-corbellini for the hint
