### ISSUE TITLE
Displaying local images in the chat with Markdown

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/core#218]
Asking the Cat to display a local image with Markdown only returns the alternative text.  
If I understood correctly, there would be the need for a static content server like [this](https://fastapi.tiangolo.com/tutorial/static-files/).

**Comment by pieroit** [comment]
> Isn't this as easy as:
> 
> ```python
> cheshire_cat_api.mount("/static", StaticFiles(directory="/static"), name="static")
> ```
> where `"/static"` is a sub-folder of `cat` at the same level of `"/admin"`.

I guess you are there, but `directory` is a full path, in fact the admin files are served from a folder out of the cat.

Try `directory="/app/cat/static"`, if that does not work make a PR anyway and I'll push on top of it (we can work it together until it's done)

Thanks

**Comment by pieroit** [comment]
Fixed with #266
