### ISSUE TITLE
Move admin_index_injected in a specific file

### ISSUE THREAD

**Issue by Mte90** [cheshire-cat-ai/core#263]
On https://github.com/pieroit/cheshire-cat/blob/main/core/cat/main.py#L71 we have the code that generated the index/html statically but we have a folder that has all the code for `routes`.
It is better to move it away.

**Comment by pieroit** [comment]
I started in a separate file but it seems that `StaticFiles` can only be attached to the main FastAPI instance and not on routes objects:
https://github.com/tiangolo/fastapi/issues/1469

So I left both the admin routes there in the admin... agree it's better under routes but don't know how to do it

**Comment by Mte90** [comment]
It make sense to do a new class that contain all the route instances in the main.py in a different file, in the routes folder. In this way the main is just... the main.
