### ISSUE TITLE
Minimal public chat under `/chat`

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#267]
Create a `/chat` endpoint serving:
 - a minimal index.html (basic layout)
 - a main.css
 - widget-vue.js for the chat widget (see #269 )

This page will be ready to be customized by devs and is intended to be the starting point to build the public facing interface for the cat.

**Comment by pieroit** [comment]
Public chat done, yet to improve but present!
Go under `http://localhost:1865/public`

**Comment by BelvEnr** [comment]
Hi! Thanks for the great work.
Is this /public page still available in new version of cheshire cat ai? gives me 404 error and no mention in the documentation

**Comment by pieroit** [comment]
> Hi! Thanks for the great work. Is this /public page still available in new version of cheshire cat ai? gives me 404 error and no mention in the documentation

No sorry, you will have to use the admin or build your own frontend
