### ISSUE TITLE
[Feature] Plugin endpoint to enable/disable it

### ISSUE THREAD

**Issue by zAlweNy26** [cheshire-cat-ai/core#274]
**Describe the solution you'd like**
There should be an endpoint to enable or disable the plugins, also adding this feature in the admin GUI.

**Comment by pieroit** [comment]
`POST /plugins/toggle/{plugin_id}`

**Comment by pieroit** [comment]
@calebgcc are you interested in plugin db and switch?

**Comment by pieroit** [comment]
Done in `develop` branch
