### ISSUE TITLE
Make number of elements retrieved from memory parameterizable

### ISSUE THREAD

**Issue by cristianorevil** [cheshire-cat-ai/core#278]
**Is your feature request related to a problem? Please describe.**
Currently the context of declarative/episodic memory is limited to 5 items that are added to the prompt. This number is "fixed" in the vector_memory.py file and sometimes is better to have an higher number of items to have a highest quality response 

**Describe the solution you'd like**
Make this value parameterizable adding a value in working memory so it is writable  from both endpoints and hooks

**Comment by nickprock** [comment]
Hi @cristianorevil @pieroit , one problem on the topk value parametrization could be the LLM has a limited number of token to be divided between context, query, answer (now I focus on OpenAI but I think it's the same for HF or Cohere). If you have an higher k in context the answer could be truncated

**Comment by pieroit** [comment]
@nickprock for smaller models we should limit prompt length at minimum (maybe separate it in different steps)

A plugin could be useful for this

**Comment by pieroit** [comment]
Fixed with #307

**Comment by pieroit** [comment]
@cristianorevil ok so let's use both `limit` and `score_threshold` in Qdrant search ;)
I'll tag you in the discord
