### ISSUE TITLE
POST `rabbithole/memory` endpoint to upload exported memories

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#287]
**Is your feature request related to a problem? Please describe.**
It is possible to export memories from the admin, and should be possible to upload them so people can share embeddings

**Describe the solution you'd like**
POST `rabbithole/memory` endpoint to upload exported JSON from memory

**Comment by giovannialbero1992** [comment]
Hi @pieroit: this issue can be closed or is it missing something? Thanks

**Comment by pieroit** [comment]
@giovannialbero1992 the endpoint is there but does nothing, it should be implemented

If you are interested in doing it I can give you some reference :)

**Comment by giovannialbero1992** [comment]
Yes, for sure :)
I'm open to receive any reference.

**Comment by pieroit** [comment]
I realized it is harder than I thought, because when you upload a document or an URL, the cat deals with text and in both cases he will store documents [via this function](https://github.com/cheshire-cat-ai/core/blob/main/core/cat/rabbit_hole.py#L230) that passes docs to memory, ending up [here](https://github.com/cheshire-cat-ai/core/blob/main/core/cat/memory/vector_memory.py#L76).

Note the `VectorMemoryCollection` class does not have the method directly, it is inherited from a [langchain class](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/qdrant.py#L112) that deals with Qdrant.

In the case of memory upload, embeddings are already there and so we should [call directly Qdrant]() and pass metadata along. It is one of those cases were langchain is not enough :rabbit: 

It doesn't matter if you reach the end goal, a stub is enough so I can work on it or we do peer programming in open mic in the discord ;)

Let me know or we find something else to contribute, thanks again

**Comment by giovannialbero1992** [comment]
Hi @pieroit sorry for being late, I'm available next week to go deeply on this issue.
In the meanwhile I worked to another issue (I'll reach you in the specific issue)
