### ISSUE TITLE
Hook to dynamically change the `input_variables` int the main prompt

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/core#288]
I tried to remove the declarative memory from the main prompt and I received a `ValidationError(model='PromptTemplate', errors=[{'loc': ('__root__',), 'msg': "Invalid prompt schema; check for mismatched or missing input parameters. 'declarative_memory'", 'type': 'value_error'}])` because the [input variables](https://github.com/cheshire-cat-ai/core/blob/959f86baa62ea526e547b7418c03ae87324df87e/core/cat/looking_glass/agent_manager.py#L26) of the prompt in the AgentManager are hard coded.

I've seen from the comments above that dynamically defining the input variables was already a plan. Therefore, I propose this solution:
```python
@hook(priority=0)
def before_agent_creates_prompt(input_variables, main_prompt, cat):
    """Hook to dynamically define the input variables.
    
    Allows to dynamically filter the input variables that end up in the main prompt by looking for which placeholders
    there are in it starting from a fixed list.
    
    Args:
        input_variables: list of placeholders to look for in the main prompt
        main_prompt: string made of the prompt prefix, the agent instructions and the prompt suffix
        cat: Cheshire Cat instance

    Returns:
        list of placeholders present in the main prompt.

    """
    
    # Look the input variables and check if they are in the main prompt
    input_variables = [i for i in input_variables if i in main_prompt]

    return input_variables
```

Honestly, I don't know if this should be a hook or the list comprehension could just be used to filter the input variables when some placeholder is removed from the prompt suffix.

**Comment by pieroit** [comment]
This is crucial to have custom agents, If you got time you can implement this hook

On the long run we should prepare the prompt ourselves and feed it to the (custom) agent

**Comment by nicola-corbellini** [comment]
Sure the PR is already ready. Would you put this before or after the [agent_allowed_tools](https://github.com/cheshire-cat-ai/core/blob/959f86baa62ea526e547b7418c03ae87324df87e/core/cat/looking_glass/agent_manager.py#L34) hook?

**Comment by pieroit** [comment]
Thanks @nicola-corbellini before sounds ok as in the code.
Having some doubt on how to pass the `main_prompt`, but let me see your proposal in the PR :D
