### ISSUE TITLE
Dockerfile simplification

### ISSUE THREAD

**Issue by lucaGazzola** [cheshire-cat-ai/core#289]
The project's [Dockerfile](https://github.com/cheshire-cat-ai/core/blob/main/core/Dockerfile) now manually installs Node.js, we can instead use a docker image that already contains python and node to simplify it.

**Comment by zioproto** [comment]
Hello @lucaGazzola 
thanks for your feedback. I agree that simpler is better.

It would be great to find a Docker image that satisfies the following:
* Supports at least the amd64 and arm64 architectures.
* Does not add anything else then python3.10 and nodejs to keep the image size small.

The image you are proposing in PR #290 has a double installation of python 3.9 and 3.10 and this is not acceptable for a Docker image that must keep the size as small as possible.

https://cloud.google.com/architecture/best-practices-for-building-containers#build-the-smallest-image-possible

Thanks

**Comment by pieroit** [comment]
Nodejs is no more necessary because core downloads a static release from repo `admin-vue`
Thanks all!
