### ISSUE TITLE
[BUG] Loop after uploading pdf with only images

### ISSUE THREAD

**Issue by zAlweNy26** [cheshire-cat-ai/core#292]
**Describe the bug**
I tried to upload a pdf with only images and it started looping over
`cheshire_cat_core           | Building summaries over 0 chunks. Please wait.`
without end.

**To Reproduce**
Steps to reproduce the behavior (as an example):
1. Go to the chat
2. Upload a pdf with only images
3. See the logs

**Expected behavior**
I expect the cat to respond with an information notification saying that it has created 0 thoughts on that file, otherwise, an error notification saying that it was unable to create thoughts on that file.

**Comment by tarunsamanta2k20** [comment]
I'd like to look into this.

**Comment by pieroit** [comment]
@tarunsamanta2k20 thanks

Tell me if you need indications or explanations on how the code works
