### ISSUE TITLE
`GET /plugins/` returns both installed and available plugins

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#300]
**Is your feature request related to a problem? Please describe.**
Plugin registry is to be introduced in the cat and the admin should show them 

**Describe the solution you'd like**
Return installed plugins with their metadata and a list of available plugins

**Describe alternatives you've considered**
Two different endpoints, because registry may be an external service one day (maybe)

Example response elaborated from @EugenioPetulla proposal.
Conversation held by @zAlweNy26 @lorenzopalloni @sirius-0 @nicola-corbellini 

```json
{
  "status": "success",
  "results": 3,
  "installed": [
     {
        "id": "sdfgdfgsdgsdgsdgdfgafewarwqft",
        "name": "Quick Cat Plugin",
        "description": "This is a quickstart plugin.",
        "author_name": "Name",
        "author_url": "https://link-to-author/",
        "plugin_url": "https://link-to-support-page/",
        "tags": "math, finance, utility, wolfram, wikipedia",
        "thumb": "https://link-to-your-thumb.jpg",
        "version": "0.1.2"
      }
   ]
   "registry": [
    {
      "id": "b_plugin",
      "name": "B plugin",
      "description": "Description",
      "...": "..."
    },
  ]
}
```

**Comment by valentimarco** [comment]
I am working on this issue!
I implemented a function (5ff68b9b816c01ca2bb275eb2656f1710e638b9e) to read the [awesome-plugins](https://github.com/cheshire-cat-ai/awesome-plugins/tree/main) repo, but there is a problem for the future:
When you download the plugin to install it ,the "download zip" command that provide github, adds the string "-main" at the end, this can be problematic once we add the feature to install on the plugin page. 

We can resolve this or  by download the plugin from the "Releases" section with already the correct name or by truncate the "-main" part from the file before upload it.

**Comment by pieroit** [comment]
@valentimarco the core will ask plugins to this service:
https://github.com/cheshire-cat-ai/awesome-plugins-backend

Please let's have a call so I can show you how it's going to work and you can contribute :)

**Comment by valentimarco** [comment]
I changed as you suggested but i needed to pass as body the url (i will study a method to pass url as query param) and will accept any link that host a zip file (for github reps, just add "/archive/master.zip" at the end of the repo link" ) 
The name of the new endpoint is a placeholder!
25abae6d6549117551ca1464dc28f27bda66a121

**Comment by pieroit** [comment]
@valentimarco can you send a PR on branch develop?
