### ISSUE TITLE
Switch episodic/declarative collections on/off

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#306]
**Is your feature request related to a problem? Please describe.**
Users may be interested in activating or deactivating one or both memories.

**Describe the solution you'd like**
Assume the core receives a message like this via websocket:

```json
{
    "text": "....",
    "prompt_settings": {
        "use_declatarive_memory": false,
        "use_episodic_memory": true,
    }
}
```

The cat should activate / deactivate memory retrieval based on this information that ends up directly in working memory.
The prompt can also be simplified, if no memory is present, no memory title should be inserted.

@cristianorevil if you comment here I can assign to you the issue.
I'm available for support in case it is needed ;)

**Comment by cristianorevil** [comment]
Please assign to me
