### ISSUE TITLE
Qdrant local mode

### ISSUE THREAD

**Issue by Pingdred** [cheshire-cat-ai/core#308]
**Is your feature request related to a problem? Please describe.**
Docker container can be smaller.

**Describe the solution you'd like**
The [qdrant-client local mode](https://github.com/qdrant/qdrant-client#local-mode) allows you to have qdrant features available without having to install the server.

In case of need to scale, a section for configuring access to a qdrant server could be added to the settings page in the admin.

**Comment by pieroit** [comment]
Thanks let's try it out

**Comment by pieroit** [comment]
@lorenzo-polaris this could be useful for testing

**Comment by lorenzo-polaris** [comment]
Yes it's the way to go! It will also enable us to run tests in CI/CD. I'll implement it asap :)

**Comment by pieroit** [comment]
@lorenzo-polaris sweeeeeet
