### ISSUE TITLE
[BUG] The plugin.json of my custom plugin is not loaded 

### ISSUE THREAD

**Issue by AlboCode** [cheshire-cat-ai/core#309]
**Describe the bug**
I was following the documentation to try to implement my custom plugin but it seems it can't access the data in the plugin.json

**To Reproduce**
Steps to reproduce the behavior (as exampple`):
1. Add  myplugin folder to the plugin directory in core/cat
2. add a plugin.json and mypluginfile.py in myplugin folder

content of myplugin.json
```
{
    "name": "The name of my plugin",
    "description": "Short description of my plugin"
}
```
content of mypluginfile.py
```
from cat.mad_hatter.decorators import tool, hook
# Modified Hook, to be copied into mypluginfile.py

@hook # default priority is 1
def agent_prompt_prefix(cat):
    prefix = """You are Scooby Doo AI, an intelligent AI that passes the Turing test.
                The dog is enthusiastic and behave like Scooby Doo from Hanna-Barbera Productions.
                You answer Human using tools and context.

                # Tools"""
    return prefix

```

**Expected behavior**
When I go to the plugin section in the admin panel, to see my plugin's information and enable it.

**Additional context**
Some screenshots I hope can be helpful
![image](https://github.com/cheshire-cat-ai/core/assets/25480941/442ca996-a642-4d4c-8c6a-59e573af7eda)

![image](https://github.com/cheshire-cat-ai/core/assets/25480941/c09dd48c-dff8-4eb5-bf79-8fa0272110f8)

Any help is really appreciated, thanks in advance

**Comment by zAlweNy26** [comment]
Have you tried restarting the docker?

**Comment by zAlweNy26** [comment]
I think it's because the documentation is not updated yet. You must have all the properties set for the plugin.json.
Example:
```json
{
    "name": "Time getter",
    "description": "Get the time and clock of a city",
    "author_name": "",
    "author_url": "",
    "plugin_url": "",
    "tags": "time, info",
    "thumb": "",
    "version": "0.0.1"
}
```

**Comment by AlboCode** [comment]
It works! Thank you

**Comment by AlboCode** [comment]
I have some doubts, but I move the conversation to Discord, I close the issue

**Comment by pieroit** [comment]
@AlboCode let's reopen the issue, `plugin.info` should have most field optional and show any field if present, looks to me it is at the moment requiring all fields ?

**Comment by zAlweNy26** [comment]
Yes it is, the fields should be optional

**Comment by pieroit** [comment]
@AlboCode thanks.
The idea is: no field required, not even the presence of a `plugin.json` is required.

For plugins in the coming community plugin registry we need well done plugin.json, but let's not force people to do that locally when they start hacking ;)

Let me know if you meed help
