### ISSUE TITLE
Handle all the recalled memories in the same place

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/core#315]
**Is your feature request related to a problem? Please describe.**
Currently, the tool semantic search is managed inside the `agent_allowed_tools` [hook](https://github.com/cheshire-cat-ai/core/blob/dbd27f73d6c9d37df66e61b119918a33f67062eb/core/cat/mad_hatter/core_plugin/hooks/agent.py#L16). 
However, the same pipeline is performed for the other two collections in when [saving the context in the working memory](https://github.com/cheshire-cat-ai/core/blob/dbd27f73d6c9d37df66e61b119918a33f67062eb/core/cat/looking_glass/cheshire_cat.py#L97).

**Describe the solution you'd like**
The discussed solution could be:

- make the `before_cat_recalls_memories` [hook](https://github.com/cheshire-cat-ai/core/blob/dbd27f73d6c9d37df66e61b119918a33f67062eb/core/cat/looking_glass/cheshire_cat.py#LL104C54-L104C81) return nothing
- make another hook to manage the semantic search parameters `k` and `threshold`
- loop the `recall_memories_from_embedding` step for the three collections

The `agent_allowed_tools` hook should take core of mapping the tools names to the tools `BaseTool` class and the tools names should be added in the working memory along with the other two memories content.

As discussed with @pieroit and @zAlweNy26

**Comment by pieroit** [comment]
Done in #302 and later 994b276f04cc86ed053ed4ec11613d3cd8ee50cf
