### ISSUE TITLE
[BUG] Setting wrong HuggingFace Hub models prevent the Cat from starting 

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/core#323]
**Describe the bug**
The HuggingFace Hub setting only accepts few categories of NLP models.
Setting a LLM from a not valid category saves the setting in the db, but then prevents the Cat from starting. Hence, changing back to another valid model is not possible anymore. The only solution is to delete `metadata-v3.db`.

**To Reproduce**
Steps to reproduce the behavior (as example):
1. Go to the `Setting` page
2. Configure LLM with `HuggingFace Hub`
3. Set the repo id from any model from HuggingFace with a tag different from  'text2text-generation', 'text-generation' or 'summarization' (e.g. use a 'Conversational' model like this: microsoft/DialoGPT-medium)
4. See error:
```bash
cheshire_cat_core           |   Got invalid task conversational, currently only ('text2text-generation', 'text-generation', 'summarization') are supported (type=value_error)
```
5. Change back to any other valid LLM (e.g. ChatGPT)
6. See error:
```bash
pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFaceHub
cheshire_cat_core           | __root__
cheshire_cat_core           |   Got invalid task conversational, currently only ('text2text-generation', 'text-generation', 'summarization') are supported (type=value_error)
cheshire_cat_core           | 
cheshire_cat_core           | ERROR:    Application startup failed. Exiting.
```

**Expected behavior**
The Cat should check if the model is correct before getting the configuration and prevent setting it to no crash.
Additionally, the admin could notify the event.

**Additional context**
Specifically, the app crashes [here](https://github.com/cheshire-cat-ai/core/blob/1589af0638f9b584c9f568eba295e26c198b0efc/core/cat/mad_hatter/core_plugin/hooks/models.py#L50)

**Comment by pieroit** [comment]
A first fix could be to use `LLMDefaultConfig` when there is an exception during [model instantiation](https://github.com/cheshire-cat-ai/core/blob/1589af0638f9b584c9f568eba295e26c198b0efc/core/cat/mad_hatter/core_plugin/hooks/models.py#L50).
So if anything goes wrong, the cat does not die (he is already 6 lives out of 7)

As a second step we can specialize the exception to dealt with specific LLMs

**Comment by nicola-corbellini** [comment]
@SantoSimone It didn't happen to me, could you share the full error trace please? Is this happening right after you set the LLM?

My best guess is that this error is due to the tool embedding that happens when [bootstrapping](https://github.com/cheshire-cat-ai/core/blob/b2cda15a6b94ea297a86ab6757cfbf6218db3c41/core/cat/routes/setting/llm_setting.py#L60) the Cat.

**Comment by SantoSimone** [comment]
I had to reboot the pc in the meanwhile and it seems I do not get that error now, strange..

Anyway, is the naive solution what we were looking for? Should I make a PR?

**Comment by nicola-corbellini** [comment]
I think it is, let's hear from @pieroit

**Comment by pieroit** [comment]
@SantoSimone @nicola-corbellini yes let's go with the naive solution, and if demand for HF support raises we come back to improve ;)
