### ISSUE TITLE
Admin should ask for API_KEY / user credentials

### ISSUE THREAD

**Issue by zAlweNy26** [cheshire-cat-ai/core#324]
**Describe the bug**
If I set the API_KEY in the .env file, I can't access anymore the /admin endpoint.
It is because EVERY endpoint needs an "access_token" in the header of the request.

**To Reproduce**
Steps to reproduce the behavior (as an example):
1. Set an API_KEY in the .env file
2. Build again the core
3. Go to the /admin endpoint
4. See the error message

**Expected behavior**
I expect to access the admin GUI without checking for the access_token header, because it should be checked in the frontend.

**Comment by pieroit** [comment]
Agree
At the moment it is better to not serve the admin at all when API_KEY is set, for obvious security reasons.

As we define the user system, we can circle back to this ;)

**Comment by pieroit** [comment]
#62

**Comment by pieroit** [comment]
Note: as suggested by @zAlweNy26 it could be useful to have a JWT to avoid requiring an API_KEY each time the admin is open

**Comment by EugenioPetulla** [comment]
API_KEY is intended for machine-to-machine communication, JWT is more suitable for user-to-machine auth system because it can pass also some metadata (like username, email, etc). We can have both when we will address the user auth issue, if we choose to support oAuth2 or similar.

**Comment by pieroit** [comment]
As users are supported via `user_id` but not managed, `/admin` endpoint can serve the interface without considering API_KEY, as it will not be possible to use the endpoints.

As suggested by @zAlweNy26, end user in admin will input the API_KEY in the admin to let it connect securely to endpoints
