### ISSUE TITLE
Add `summarize` flag to rabbit hole endpoints

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#342]
**Is your feature request related to a problem? Please describe.**
We had to deactivate summarization because most newcomers try to upload to the cat 150 pages of pdf - just as a start.

**Describe the solution you'd like**
Summarization should be opt-in for high quality ingestion. Each rabbit hole endpoint should have a `summarize` parameter which defaults to `False` but can easily be activated :)

**Comment by pieroit** [comment]
@calebgcc are you interested?

**Comment by zAlweNy26** [comment]
How should it be designed in the admin panel?

**Comment by calebgcc** [comment]
@pieroit @zAlweNy26 I think we can have a little chat in the next days to solve this problem once and for all
