### ISSUE TITLE
docker compose up error on m2 mac

### ISSUE THREAD

**Issue by Tnnienn** [cheshire-cat-ai/core#354]
Ciao!! i'm on a m2 mac book air,

I tried to install the cat but the following error appears:

`
cheshire_cat_core           | INFO:     Will watch for changes in these directories: ['/app']
cheshire_cat_core           | INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
cheshire_cat_core           | INFO:     Started reloader process [1] using WatchFiles
cheshire_cat_core           | Process SpawnProcess-1:
cheshire_cat_core           | Traceback (most recent call last):
cheshire_cat_core           |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
cheshire_cat_core           |     self.run()
cheshire_cat_core           |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
cheshire_cat_core           |     self._target(*self._args, **self._kwargs)
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
cheshire_cat_core           |     target(sockets=sockets)
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
cheshire_cat_core           |     return asyncio.run(self.serve(sockets=sockets))
cheshire_cat_core           |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
cheshire_cat_core           |     return loop.run_until_complete(main)
cheshire_cat_core           |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
cheshire_cat_core           |     config.load()
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 477, in load
cheshire_cat_core           |     self.loaded_app = import_from_string(self.app)
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
cheshire_cat_core           |     raise exc from None
cheshire_cat_core           |   File "/usr/local/lib/python3.10/sie-packages/uvicorn/importer.py", line 21, in import_from_string
cheshire_cat_core           |     module = importlib.import_module(module_str)
cheshire_cat_core           |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
cheshire_cat_core           |     return _bootstrap._gcd_import(name[level:], package, level)
cheshire_cat_core           |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
cheshire_cat_core           |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
cheshire_cat_core           |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
cheshire_cat_core           |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
cheshire_cat_core           |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
cheshire_cat_core           |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
cheshire_cat_core           |   File "/app/./cat/main.py", line 10, in <module>
cheshire_cat_core           |     from cat.log import log, welcome
cheshire_cat_core           |   File "/app/./cat/log.py", line 10, in <module>
cheshire_cat_core           |     from loguru import logger
cheshire_cat_core           | ModuleNotFoundError: No module named 'loguru'`

**Comment by pieroit** [comment]
First time you install?
Or it is an old installation?

**Comment by pieroit** [comment]
loguru is not found, it means you did not `docker-compose build --no-cache `

Please follow this update instructions and let me know:

https://github.com/cheshire-cat-ai/core#update

**Comment by Tnnienn** [comment]
Grazieee! the cat started after making the build(and the update)
