### ISSUE TITLE
[Feature] support more file type and directory upload

### ISSUE THREAD

**Issue by AndreaPesce2002** [cheshire-cat-ai/core#356]
**Is your feature request related to a problem? Please describe.**
I'm interested in implementing programming languages ​​and uploading entire folders.

**Describe the solution you'd like**
I'd like the Rabbit hole supports more file type for exeple .py and HTML and if possibile to upload an entrire folder

**Describe alternatives you've considered**
I've seen that langchain supports different types of loders and a directory loader

If you are interested in the feature I am interested in working on it

**Comment by nicola-corbellini** [comment]
Hi @AndreaPesce2002, I'm having some doubts about the chat we had to support programming languages files.
In the end, one could just convert the file to `.txt` and upload every programming file. Maybe not the best, but for the moment it doesn't have any drawback.

Rather, I've seen there is [this](https://api.python.langchain.com/en/latest/text_splitter/langchain.text_splitter.PythonCodeTextSplitter.html#langchain.text_splitter.PythonCodeTextSplitter) Python text splitter that looks interesting. 
Currently, we are using [this](https://github.com/cheshire-cat-ai/core/blob/724baa817c93fff68afb4a8532fcad7377ce1961/core/cat/mad_hatter/core_plugin/hooks/rabbithole.py#L102) splitter. An alternative idea, could be to add a proper splitter if the uploaded file has some Python code. What do you think?

**Comment by pieroit** [comment]
Since `.py` are simple text files, what about let them be uploaded as `.py` and in that case be splitted with the python splitter?

**Comment by AndreaPesce2002** [comment]
@nicola-corbellini  
my idea was to make the transition only more comfortable, in addition I used python as an example but I would like to make it possible to upload as many types of files as possible (obviously files that can be converted into text), in addition to this as I have said I'd like to make sure you upload entire folders of files.

@pieroit 
as regards the use of the splitter, I think it's a great solution since I don't think it's a good idea to load an entire file of who knows how many lines in a single memory cell

**Comment by nicola-corbellini** [comment]
Great then, I'll assign the issue to you

**Comment by AndreaPesce2002** [comment]
Thank you
