### ISSUE TITLE
DRY code

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/core#366]
Following [this](https://github.com/cheshire-cat-ai/core/pull/362#discussion_r1267029114) suggestion from @giovannialbero1992,  I propose to aggregate memory specific [recalls from embedding](https://github.com/cheshire-cat-ai/core/blob/2f5c027dc80e0e1fdf5ec05e624a8c366619ebf9/core/cat/looking_glass/cheshire_cat.py#L199-L234) in a `for` loop for better organization and readability.

For example, we could have three lists with k, threshold and memory settings that could be zipped and looped.
E.g.:
```python
ks = [k_episodic, k_declarative, k_procedural]
thresholds = [t_episodic, ..., ...]
memories_settings = ["use_episodic_memory", ..., ...]

for k, threshold, setting in zip(ks, thresholds, memories_settings):

# use self.memory.vectors.episodic.recall_memories_from_embedding

``` 

Don't know if this could be useful or could be organized even better, I'm open to suggestions

**Comment by Lv-291** [comment]
How about something like this?

```python
        memory_types = ["episodic", "declarative", "procedural"]

        for k, threshold, memory_type in zip(ks, thresholds, memory_types):
            setting = f"use_{memory_type}_memory"
            memory_key = f"{memory_type}_memories"

            if prompt_settings[setting]:
                # recall relevant memories
                vector_memory = getattr(self.memory.vectors, memory_type)

                memories = vector_memory.recall_memories_from_embedding(
                    embedding=memory_query_embedding,
                    k=k,
                    threshold=threshold,
                    metadata={
                        "source": user_id
                    }
                )
            else:
                memories = []

            self.working_memory[memory_key] = memories
```

**Comment by nicola-corbellini** [comment]
@Lv-291 Exactly something like this. 

If `memories = []` is not needed further in the code I guess you could skip the `else` or even directly assign `self.working_memory[memory_key] = vector_memory.recall_memories_from_embedding`.

Btw let's hear also from @pieroit

**Comment by pieroit** [comment]
Thanks @nicola-corbellini @Lv-291, I agree a refactor can be useful there.

Two observations:
- `metadata={ "source": user_id }` is only used for episodic memory, so there will be for each collection:
   - `embedding` (this should not change, but could if plugin devs decide to land a different query to each collection)
   - `k`: how many memories to recall
   - `threshold` minimal score
   - `metadata` conditions on recall 
- how do we ask this stuff from hooks? The one we have now is not ideal, maybe a different hook for each memory? Each giving `embedding`, `k`, `threshold`, `metadata`? As a tuple or as a dictionary? Let's define this so we have a good standard to rely on ;)

@cristianorevil @calebgcc @EugenioPetulla you are welcome to leave suggestions




> If `memories = []` is not needed further in the code I guess you could skip the `else` or even directly assign `self.working_memory[memory_key] = vector_memory.recall_memories_from_embedding`.

@nicola-corbellini can you please clarify? I don't get the idea

**Comment by nicola-corbellini** [comment]
> If memories = [] is not needed further in the code I guess you could skip the else or even directly assign self.working_memory[memory_key] = vector_memory.recall_memories_from_embedding

Sorry @pieroit, my bad forget about this part.

W.r.t. the hook, I agree having three separate methods for each memory, where each method allows to hook the declaration of `embedding`, `k`, `threshold` and `metadata`. 
If I'm not wrong, we could just pass `metadata=None` for procedural and declarative memories as is it indeed the [default value](https://github.com/cheshire-cat-ai/core/blob/2f5c027dc80e0e1fdf5ec05e624a8c366619ebf9/core/cat/memory/vector_memory.py#L191) if not specified otherwise.
