### ISSUE TITLE
Plugin settings

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#370]
Plugins should be able to:
- decide their own settings
- have validated http endpoints exposed to clients
- save and load them from wherever they want
- have good default to make as less work as possible

There will be an (optional) `settings.json` in the plugin folder itself.
Via plugin, a dev can define the following hooks:

```python
from pydantic import BaseModel

@hook
def plugin_settings_get_schema():
    # This hook tells the cat how plugin settings are defined, required vs optional, default values, etc.
    # the standard used is JSON SCHEMA (so a client can auto-generate html forms)
    # Schema can be created in several ways:
    # 1 - auto-generarted with pydantic (see Cocumber below)
    # 2 - python dictionary
    # 3 - json loaded from current folder or from another place

    Cocumber(BaseModel):
        # required field, type int
        length: int
        # optional field, type str, default "my fav when I feel lonely"
        description: str = "my fav when I feel lonely"

    return Cocumber.schema()


@hook
def plugin_settings_save(settings):
    # this hook passes the plugin settings as sent to the http endpoint (via admin, or any client)
    # the settings to save are validated according to the json schema given above
    # default behavior for this hook, just saves contents in a settings.json in current folder
    pass


@hook
def plugin_settings_load():
    # how to load saved settings for the plugin.
    # default: loads the settings.json in current folder
    pass
```

A plugin dev can:
- write no hook at all: in this case, plugin has no settings exposed via rest api
- only give the schema: in this case, the cat will expose settings via http and manage how settings are loaded and saved in `settings.json`, while respecting the given schema
- give schema, save and load hooks: the cat will open endpoints to get and post settings according to schema, but they are loaded and saved as the developer wishes
- additional settings can be managed as the plugin dev wishes, out of this basic spec

Thanks to @zAlweNy26 @calebgcc @Jhonnyr97 @Pingdred for helping define this spec.
Feedback welcome! Tagging for interest @nicola-corbellini @EugenioPetulla @Mte90 @cristianorevil

**Comment by cristianorevil** [comment]
@pieroit this sounds great! I wait a full example on a demo plugin to better understand

**Comment by Mte90** [comment]
It is very cool, my suggestions:

* Create a repository with a plugin proposal (without implementing in the core)
* Endpoints should be defined in a json, in this way those information can be exposed more easily (also if the plugin is not initialized or installed)
  *  Like `/hello` and the class that handle it (in this way the class is loaded only when need it and not always)
* `settings.json` that refer at the various options that can be altered by the cat, I mean like you are saying defaults values that the can manage with their own endpoints, the plugin it will use some cat methods to read the settings itself (that method will check if the value exists in the db with a fallback to the file)
  *  If the dev need to manipulate the data on load/save as your example a filter (not an hook) that handle that data before the action itself, but in this way it is something more advanced and not mandatory like your example
    * I think the examples of a secret key for a saas as example, as you don't need to manipulate that data

My idea is that if we can do the biggest part to help the plugins developers is to achieve this stuff without coding at all. So a json with settings and one with endpoints simplify a lot, as you have just to do your code.  
In this way it is more simple to integrate it with other stuff/library/framework/saas.

**Comment by pieroit** [comment]
Thanks for your feedback @Mte90 

> * Create a repository with a plugin proposal (without implementing in the core)

@EugenioPetulla just created a [repo for community plugins](https://github.com/cheshire-cat-ai/awesome-plugins) and is also building a microservice around it

> * Endpoints should be defined in a json, in this way those information can be exposed more easily (also if the plugin is not initialized or installed)
>   
>   * Like `/hello` and the class that handle it (in this way the class is loaded only when need it and not always)

Do you mean to let plugins extend the cat endpoints? We did not discuss this yet but it is a cool idea.
What about an additional decorator `@route` to automagically extend fastAPI routes?

> * `settings.json` that refer at the various options that can be altered by the cat, I mean like you are saying defaults values that the can manage with their own endpoints, the plugin it will use some cat methods to read the settings itself (that method will check if the value exists in the db with a fallback to the file)

Did not understand this sorry :(
Maybe a call in open mic?

>   * If the dev need to manipulate the data on load/save as your example a filter (not an hook) that handle that data before the action itself, but in this way it is something more advanced and not mandatory like your example

We do not adopt the difference between filter and hooks, they're all hooks (and it will be documented if they need to return something or not)

>   * I think the examples of a secret key for a saas as example, as you don't need to manipulate that data

Agree, that can be in `settings.json`, and if plugin dev defines a schema for it the cat will automatically create both the endpoint and an admin form to change them

> My idea is that if we can do the biggest part to help the plugins developers is to achieve this stuff without coding at all. So a json with settings and one with endpoints simplify a lot, as you have just to do your code. In this way it is more simple to integrate it with other stuff/library/framework/saas.

So you mean an additional json for the endpoints?

**Comment by Mte90** [comment]
* I am not talking about a repository of community plugins, I am talking about a repository with a demo plugin for the plugin proposal, where we can discuss there about changes and so on before the plugin changes to the core
* Yeah, I mean a way to create new endpoints if needed but in my opinion those should be defined in the json and loaded from there
* My setting suggestion is define those in json, cat core add support for those setting when read the file (no code required from a plugin developer) and also add hooks/filter/whatever you call it to manipulate that data on save and on loading

Move stuff to json simplify the plugin creation because require less code and development speedup

**Comment by pieroit** [comment]
> * I am not talking about a repository of community plugins, I am talking about a repository with a demo plugin for the plugin proposal, where we can discuss there about changes and so on before the plugin changes to the core

Agree this can be a good way to demo how a plugin is going to look like

> * Yeah, I mean a way to create new endpoints if needed but in my opinion those should be defined in the json and loaded from there

A dev has anyway to write logic for those endpoints, adding a JSON is twice the work for them.

> * My setting suggestion is define those in json, cat core add support for those setting when read the file (no code required from a plugin developer) and also add hooks/filter/whatever you call it to manipulate that data on save and on loading
> 

Auto-generated settings endpoint for a plugin requires two things:
- a schema (what fields, required vs optional, defaults)
- a way to get settings
- a way to save them

As you can see in the example [above](https://github.com/cheshire-cat-ai/core/issues/370#issue-1814451334) the core provides defaults so you can just provide the schema, and you can provide it in three different ways (JSON - pydantic class - python dict)

> Move stuff to json simplify the plugin creation because require less code and development speedup

Ok

**Comment by pieroit** [comment]
Done in `develop` branch
