### ISSUE TITLE
[BUG] Cat history is not deleted when admin is left

### ISSUE THREAD

**Issue by gianfrancodemarco** [cheshire-cat-ai/core#392]
**Describe the bug**
The cat _history_ is not deleted when the admin page is left. 

**To Reproduce**
Steps to reproduce the behavior (as exampple`):
1. Go to _admin_
2. Chat with the cat
3. Reload the page
4. Chat with the cat
5. The history of the previous session is attached to the prompt context

**Expected behavior**
The cat history should be deleted when the admin page is left or reloaded.

**Comment by pieroit** [comment]
There is an endpoint to delete convo history, any client can use it
