### ISSUE TITLE
[Feature]Support streaming

### ISSUE THREAD

**Issue by KevinZhang19870314** [cheshire-cat-ai/core#411]
**Is your feature request related to a problem? Please describe.**
Support streaming when answer user question. Make typo effect in admin ui.

**Describe the solution you'd like**
Add streaming=True in ChatOpenAI parameter. And do corrensponding changes in Chesshire_cat class.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by pieroit** [comment]
Not so easy, there is an agent in the cat that makes multiple calls to the LLM

Also, not all LLMs support streaming

Let's see in the future
