### ISSUE TITLE
[BUG] Network error while requesting

### ISSUE THREAD

**Issue by AlessandroSpallina** [cheshire-cat-ai/core#416]
**Describe the bug**
After my first cat setup using docker-compose up I can't even configure LLM or embedder because I receive "Network error while requesting". Is the cat trying to get LLM/embedder info online? I just wanted to ask this because in that case, I need to configure a proxy somewhere.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get a physical host/VM unable to reach the internet without passing through a proxy
2. Git clone the cat core
3. Docker compose up
4. Visit the /admin/settings panel and you'll get the error

**Additional context**
If anything in that stage goes on the internet I have to specify a http/https proxy

![image](https://github.com/cheshire-cat-ai/core/assets/10786872/3ebd17a2-4fe3-497f-af19-cd4de2c50b30)

![image](https://github.com/cheshire-cat-ai/core/assets/10786872/6c4cefb7-7e07-4adf-8f14-0ff929c7205d)

![image](https://github.com/cheshire-cat-ai/core/assets/10786872/c42ccfdc-5c29-4a27-a27e-2969449e5234)

**Comment by zAlweNy26** [comment]
To retrieve LLM and embedder settings, the admin panel requests them from the cat endpoints. Be sure to correctly configure the .env file in the cat core repo

**Comment by AlessandroSpallina** [comment]
Right, I just realized that the front end was querying localhost and not my remote host!
