### ISSUE TITLE
[Feature] Add user_id to the cat's ws response

### ISSUE THREAD

**Issue by simonedoria** [cheshire-cat-ai/core#434]
If you want the cat to be used by different people with different sessions, you can put an _user_id_ in the options parameters of the payload. By the way, it is not returned in the cat websocket answer. Not making me able to know for which user that message is for.

**The solution** should be the cat returning it in the websocket response.

Thanks!

**Comment by varrialeciro** [comment]
I think that every conversation with a different user should be segregated. I mean that there should be a different user chat session for each user and every chat should be indipendent from each other.

Each chat should follow its own flow.


So maybe an idea could be to create a class for a chat and istanciate a **chat_object** for each user and then work on it when that user send and receive message.

**Comment by simonedoria** [comment]
> I think that every conversation with a different user should be segregated. I mean that there should be a different user chat session for each user and every chat should be indipendent from each other.
> 
> Each chat should follow its own flow.
> 
> So maybe an idea could be to create a class for a chat and istanciate a **chat_object** for each user and then work on it when that user send and receive message.

I think This should assume that you have to allocate a ws handler for each session opened by each user from your client...

**Comment by pieroit** [comment]
@varrialeciro we have a rudimental non-session system to handle different contexts for different users, can you elaborate a little more on your proposal? Let's reason about this and do it once and for all.

Keep in mind that:
- we will not support user register/login/auth
- we will only manage sessions, separated by a `user_id` that is created by the websocket client
- episodic memory and convo history are already separated by `user_id`, but it's buggy and has to be redesigned
- there is a websocket manager in `cat/routes/websocket.py`

**Comment by pieroit** [comment]
@simonedoria thanks, for this issue here are a few pointers:

- `user_id` is added to working memory [here](https://github.com/cheshire-cat-ai/core/blob/5b84b1d600ba9e8600413ff27c033c6d8ed5d0ca/core/cat/looking_glass/cheshire_cat.py#L333)
- should be reinserted in `final_output` [here](https://github.com/cheshire-cat-ai/core/blob/5b84b1d600ba9e8600413ff27c033c6d8ed5d0ca/core/cat/looking_glass/cheshire_cat.py#L412)

**Comment by pieroit** [comment]
Please also have a look at this:
https://cheshire-cat-ai.github.io/docs/technical/advanced/user_system/
