### ISSUE TITLE
[BUG] The vector DB is full of blank strings

### ISSUE THREAD

**Issue by AlessandroSpallina** [cheshire-cat-ai/core#439]
**Describe the bug**
When ingesting files and web pages I noticed several entries with only blank strings (or invisible characters)

**To Reproduce**
1. Ingest a couple of Wikipedia pages and some PDFs
2. In /admin -> memory search for ""
2a. You'll find a lot of useless blank strings

**Expected behavior**
I expect 0 blank strings in the DB

**Additional context**
![image](https://github.com/cheshire-cat-ai/core/assets/10786872/980da562-9b92-4956-ab62-b212db2e913a)

**Comment by pieroit** [comment]
We have a filter for docs shorter than 10 chars. It's here:
https://github.com/cheshire-cat-ai/core/blob/a1262d3cf3abe7cf31cb79e8bcee7343339b6275/core/cat/mad_hatter/core_plugin/hooks/rabbithole.py#L132

Did you override that hook? If not, there is a bug somewhere

**Comment by AlessandroSpallina** [comment]
I'm only using the [summarization plugin](https://github.com/nicola-corbellini/ccat_summarization/blob/main/summarization.py#L8) from Nicola, but the rabbithole_splits_text is not overriden, so there must be a bug somewhere in the core.
I'll investigate and let you know.

**Comment by nickprock** [comment]
Hi @pieroit @AlessandroSpallina 
interesting I will try to investigate as well

**Comment by pieroit** [comment]
Also no blank strings on my side. How can we repeat the bug? Could be something related to the uploaded documents?
