### ISSUE TITLE
[Feature] Add a hook on plugin activation

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/core#442]
**Is your feature request related to a problem? Please describe.**
I'm developing a plugin that needs to upload some memories and I would like to do it once enabled.

**Describe the solution you'd like**
A possible solution would be to add a hook [here](https://github.com/cheshire-cat-ai/core/blob/a1262d3cf3abe7cf31cb79e8bcee7343339b6275/core/cat/mad_hatter/mad_hatter.py#L240) to make devs able to intervene after the plugin is toggled.

For instance:
```python
@hook(priority=0)
def after_madhatter_toggles_plugin(plugin_id, cat):
    return None
```
In this way, one could perform some setup/cleaning actions once a plugin is de-/activated.

**Describe alternatives you've considered**
The hook could be placed in many different places, the proposed one looked the one solving the more general use cases. Otherwise, more specific hooks could be placed in the [activate](https://github.com/cheshire-cat-ai/core/blob/a1262d3cf3abe7cf31cb79e8bcee7343339b6275/core/cat/mad_hatter/plugin.py#L55) and [deactivate](https://github.com/cheshire-cat-ai/core/blob/a1262d3cf3abe7cf31cb79e8bcee7343339b6275/core/cat/mad_hatter/plugin.py#L60) `Plugin` methods.

If adding this hook is ok, I assigned the issue to myself already.

**Comment by zAlweNy26** [comment]
I agree with this idea, it can help in various use cases

**Comment by pieroit** [comment]
Will be done just after the refactoring ;)
@nicola-corbellini still interested in doing  this?

**Comment by nicola-corbellini** [comment]
Yep, will do gladly, but I need a recap when you're free 😄

**Comment by pieroit** [comment]
> Yep, will do gladly, but I need a recap when you're free 😄

Gladly!
The mad hatter is ready for this

**Comment by pieroit** [comment]
## First step:

- `@plugin` decorated functions will be automagically available under `Plugin._plugin_overrides`
- `mad_hatter` can call `Plugin.activated()` and `Plugin.deactivated()` in `MadHatter.toggle()`

```python
@plugin
def activated(plugin):
    pass
```

```python
@plugin
def deactivated(plugin):
    pass
```

## Later on (after experimentation)

```python
@plugin
def installed(plugin):
    pass
```

```python
@plugin
def uninstalled():
    pass
```
