### ISSUE TITLE
`cat` instance as a singleton

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#443]
Since the `CheshireCat` instance `cat` is only one and used in many different modules, it is way easier and maintainable to have that instance as a singleton.

The instance itself could be imported easily with something like:

```python
from cat import cat
```

Or

```python
from cat import get_the_cat
cat = get_the_cat()
```

What do you think?
How would you like to have the cat available in your plugins?

**Comment by zAlweNy26** [comment]
I agree with the first snippet
