### ISSUE TITLE
`mad_hatter.hooks` cache as a dictionary

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#444]
The mad hatter at the moments keeps a cache of hooks as a list of `CatHook` objects sorted by priority

It could be more efficient and trasparent if the data structure is a dictionary:

```python
mad_hatter.hooks = {
   "before_cat_sends_message": [ CatHook, CatHook, CatHook ], # sorted by priority
   "another_hook": [ CatHook, CatHook ],  
}
```

When the mad hatter executes an hook, there would be no more need to cycle the whole list (but just the proper sublist)

**Comment by valentimarco** [comment]
Ah yes, HashMaps. I like it

**Comment by valentimarco** [comment]
I will try to implement a WIP

**Comment by pieroit** [comment]
@valentimarco I took a look, was a little too hard to do :)
Let's find a simpler issue!
