### ISSUE TITLE
Remove redundant websocket message system

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#449]
The Cat has a double system to send ws messages:
- chat (via `cat.__call__`)
- notification (via `cat.ws_messages` FIFO list)

Since there is a method [`cat.send_ws_message`](https://github.com/cheshire-cat-ai/core/blob/970693e8780be8c5e2aceaff916268d30861b004/core/cat/looking_glass/cheshire_cat.py#L285), there is no need to keep them separate

`send_ws_message` can support the following args:
- content (str)
- type (enum - optional)
- why (free dict! - optional)
- user_id (str - optional)

**Comment by zAlweNy26** [comment]
So in this way a plugin can also send messages to specific user id, right?

**Comment by pieroit** [comment]
> So in this way a plugin can also send messages to specific user id, right?

The websocket manager should check the mapping between connection and user_id ([which is not there yet](https://github.com/cheshire-cat-ai/core/blob/a1262d3cf3abe7cf31cb79e8bcee7343339b6275/core/cat/routes/websocket.py#L14)), so it is a step towards making it possible :)

**Comment by zAlweNy26** [comment]
@pieroit I think this could be closed as fixed.

**Comment by pieroit** [comment]
Still to update the main cat response (send ws message instead of return):
https://github.com/cheshire-cat-ai/core/blob/464bbe3cbc9a6c544701f1ec478a120df3f288d7/core/cat/looking_glass/cheshire_cat.py#L522

**Comment by zAlweNy26** [comment]
Oh ok, sorry

**Comment by Pingdred** [comment]
> Still to update the main cat response (send ws message instead of return):
> https://github.com/cheshire-cat-ai/core/blob/464bbe3cbc9a6c544701f1ec478a120df3f288d7/core/cat/looking_glass/cheshire_cat.py#L522

As discussed on discord, the addition of this features would allow multiple calls to the agent for a single websocket connection, generating confusion with the chat history
