### ISSUE TITLE
Consistent behaviour for heavy duty endpoints

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#451]
There are endpoints doing possibly long jobs, for example:
- change of llm
- change of embedder
- plugin install/uninstall
- plugin toggle
- rabbithole file/url/memories

At the moment their behaviour is inconsistent, as some of them are sync (client gets response when job is finished) and some are async (client gets response immediately and gets a websocket notification when job is finished)

We should devise a common behaviour so clients (and first of all the admin) are offered a consistent interface

**Comment by zAlweNy26** [comment]
I would add a new **msg_type** in the ws message content to send, called `task`, to notify the frontend that a specific task was completed, maybe defined with the name of the endpoint (?). I don't know if it's a good practice, tell me if it sounds good to you.

**Comment by pieroit** [comment]
> I would add a new **msg_type** in the ws message content to send, called `task`, to notify the frontend that a specific task was completed, maybe defined with the name of the endpoint (?). I don't know if it's a good practice, tell me if it sounds good to you.

Yep something to reason about.
Let's also see what @Pingdred thinks as he prolly will refactor the ws messages ( #449 )

**Comment by pieroit** [comment]
After a core contrib meeting:
- sync endpoints
- send ws message at the end
- admin blocks interactions and refreshes at ws message

**Comment by pieroit** [comment]
Note: endpoints mentioned above should just run the task sync, no `background_task`.
Client will just wait until the task is finished
