### ISSUE TITLE
[Feature] Save settings on plugin activation

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/core#454]
**Is your feature request related to a problem? Please describe.**

Currently, plugins store their settings in the `settings.json` file. This file is created only once the user/dev explicitly saves the settings.
However, as a dev, I may be interested in having the plugin ready-to-use, specifically if I make all the settings optional.

**Describe the solution you'd like**

I think people could have a smoother experience if the file is created as soon as the plugin is activated.
In particular, this is needed for plugins that have default values.

**Additional context**
At a first glance, a possibility could be to [save the settings](https://github.com/cheshire-cat-ai/core/blob/main/core/cat/mad_hatter/plugin.py#L110) on plugin [activation](https://github.com/cheshire-cat-ai/core/blob/main/core/cat/mad_hatter/plugin.py#L55).
Something like:
```python
  def activate(self):
      # lists of hooks and tools
      self._hooks, self._tools = self._load_hooks_and_tools()
      # Load and save settings
      settings = self.load_settings()
      self.save_settings(settings)
     # Activate plugin
      self._active = True
```
Yet, this doesn't handle the case where some settings are required, rather than optional

**Comment by nicola-corbellini** [comment]
Yes this could be done.
My concern was mainly from the dev's perspective.
E.g., I was developing a plugin with all optional settings and I wanted to grab those settings inside a hook. Thus, I did the following:
1. load the settings inside the hook, like explained in the doc.
2. go to the GUI and toggle the plugin
3. open the settings side panel and save them, so the cat creates the settings.json

In my mind, I was thinking about skipping point 3 and merging it with the point 2. Yet, this is just a detail: the pipeline above should be done only once when you start developing a plugin

**Comment by pieroit** [comment]
@nicola-corbellini there should be a way in pydantic to get a dictionary directly from the settings class (or an instance of it), with `.dict()` maybe

Agree on the position of this code, as soon as the plugin is activated

**Comment by Pingdred** [comment]
Definitely not a good first issue

**Comment by pieroit** [comment]
We did it!
Win
