### ISSUE TITLE
Dashboard for plugin debugging

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#460]
For plugin devs is essential to rapidly see:
- active hooks
- hooks ordering
- hooks input/output?
- active tools

We may create a page in the admin, or a separate client just for this purpose

**Comment by zAlweNy26** [comment]
I think it's overkill to create a new client just for this

**Comment by zAlweNy26** [comment]
Actually in admin there is now the possibiity to see the tools and hooks used by a plugin in a sidepanel on the right of the plugin settings. Should we close this?

**Comment by pieroit** [comment]
Yes, I'll open a new issue when core gives which hooks were executed for a convo turn, into the `why`
