### ISSUE TITLE
[BUG] application crashes if an OpenAI API key with exceeded quota is provided in embeddings settings

### ISSUE THREAD

**Issue by zenimarc** [cheshire-cat-ai/core#461]
**Describe the bug**
If you exceed the OpenAI API quota, (in my case I generated an api key but no payment method is registered), and you put this api key in the embeddings configuration. when you save, a loading spinner is shown but it gets stuck, from the console I can see this error printed multiple times:
```
Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
cheshire_cat_core           | Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
cheshire_cat_core           | Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
```
Even if i restart the project with docker during startup it continues to say the same previous error and the following error is shown:  ERROR:    Application startup failed. Exiting.

**To Reproduce**
1. fresh installation
2. go to settings
3. embeddings settings
4. openAI
5. put an api key which has no quota left
6. save

**Expected behavior**
print you exceeded your quota and let you input another key or change embeddings

**Additional context**

**Comment by pieroit** [comment]
Thanks, we know very well this error but never managed it.
Are you able to do a PR?

**Comment by kodaline** [comment]
@pieroit in case I can think on a general solution for this one

**Comment by pieroit** [comment]
@kodaline thanks! If you look around in the code you will find consistency in how exceptions are thrown back to the client

Let me know if you need clarification or reference
