### ISSUE TITLE
[PIZZA ORDER CHALLENGE] Make it easy to manage conversational forms from a plugin

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#479]
As [prototyped](https://github.com/Pingdred/pizza_delivery/blob/main/pizza.py) with the help of @Pingdred (and feedback from @nicola-corbellini and @zAlweNy26 ), there should be an easy to use API for plugin devs in order to make the Cat fill out automatically custom data structures during conversations, store those data in working memory, and have easy ways to create, read, edit and delete them. Let's call them "conversational forms".

Let's say for example a plugin dev wants to write a plugin to manage pizza ordering.
The order should be triggered (with confirmation from the user!) when this JSON is filled up:

```json
{
  "pizza_type": "margherita",
  "address": "youraunt street, 1112 CA"
}
``` 

This is something that can be done (and in fact can be triggered) with a `@tool`, whenever an user says something like `I want to order a pizza margherita to be delivered at Youraunt street, 1112 CA`. But what if the user just says `Let's order a pizza`?

A conversational form can be easily triggered from a `@tool`, but conversation should then be driven so the Cat asks user the missing informations, resisting to out of topic user utterances, and keep in working memory the relevant information until the task is done.

The idea from @Pingdred is to have a pydantic class representing the information to be filled, in this case:

```python
from cat.plugin_utils import Form

PizzaForm(Form):
  pizza_type: str
  address: str
```

When the ordering pizza `@tool` is triggered, the followig happens:
- input from the user is used to create an instance of `PizzaForm`, i.e. `pizza_form = PizzaForm(tool_input)`
- the instance has a method to check if every attribute has been filled, i.e. `pizza_form.is_complete()`
- the instance has a method to determine what is the next question to ask the user, i.e. `pizza_form.next()` or `.ask()`
- the instance is stored in working memory so can serve in other hooks/tools and drive conversation
- when a form is present in working memory and active, it should automatically check if the latest user utterance can help fill the form (`PizzaForm` could provide an additional and internal `cat.llm` call to analyze incoming utterances and fill up the form)

This is still a stub and must be way more explicit, but it works!!! It allows for quite complicated, but controlled conversations.

Questions:
- how much of this should be automatic?
- what is the minimal, most flexible API for `Form`? 

Any feedback is welcome. :)

**Comment by pieroit** [comment]
@nicola-corbellini and @zAlweNy26 did not like the spec, and Nicola went even further by launching a challenge to create a better one.

### PIZZA ORDER CHALLENGE
Objective:
the Cat should be able to have goal oriented conversations
basically, build and fill up a dictionary with the relevant (and validated) information

```python
{
  "pizza_type": "Margherita",  # must be enum (3 different types)
  "cheese": True, #boolean
  "address": "street....", # free string
  "floor": 4, # int, address floor
}```

**Comment by pieroit** [comment]
@AlessandroSpallina @AlboCode @cristianorevil @calebgcc

**Comment by AlessandroSpallina** [comment]
this is just amazing

**Comment by pieroit** [comment]
@EugenioPetulla @zioproto @Mte90 join us

**Comment by pieroit** [comment]
@sambarza

**Comment by valentimarco** [comment]
It's a great idea and can help a lot when creating a tool. it should be a automatic pipeline to be able to parse from the conversation and extract the features that it needs

**Comment by picc09** [comment]
The idea is fantastic. I'd like to share some thoughts that I hope can help the discussion.

1. In my opinion, it's not a good idea to think the Form as map, in the real cases Form can have some complexity.\
For instance, an address could be either a simple string (as in the example) or it could be a "subtask" that needs to collect various components of an address (street, zip, state, etc.).\
Just as an example, I'll share you how Angular represents forms. Ihmo its API is a gem: [AbstractController](https://angular.io/api/forms/AbstractControl) is the abstract class used to nest the three primary components arbitrarily: [FormControl](https://angular.io/api/forms/FormControl) represents a single field (text, number, etc.), [FormGroup](https://angular.io/api/forms/FormGroup) represents the canonical map-like form, and [FormArray](https://angular.io/api/forms/FormArray) represents a list of similar items (additional pizza toppings, perhaps?).

2. I believe that form fields could be represented with an object that includes:

- The acquired value (yes, obviously).
- A field type (string, number, picklist, boolean, etc.) to provide additional information, like whether the values must be in a list, whether the number is actually a currency, or a percentage, etc...
- A transformer/normalizer method for parsing the acquired data. \
Using an async function could be a good idea, allowing you to invoke a REST API, for example, to sanitize an address using Gmaps or perform similar procedures.
- A validation method that returns success or an error message to prompt the user for specific information request. I'd implement this here to produce more context-specific messages as needed ("I need a string with at least 10 characters," "Do you really live on the 1000th floor?", etc...).

Now, always keeping in mind the idea of "Angular-like forms", this same API would work well for the form. If it's not fulfilled, it would trigger a prompt to attempt to collect the entire data group in a single shoot.

3. Finally, I'd like to emphasize what I believe is the most important/interesting aspect of this "toy."\
As mentioned earlier, if the validation method returns SUCCESS or the NEXT USER INTERACTION, it might be possible to make this method the decision-making brain of an acquisition workflow. What I imagine is that the next interaction could be generated based on the number of retries, previously discarded data, and anything reasonably collectible in an execution context.

**Comment by pieroit** [comment]
@picc09 thanks for the deep feedback, I'll reply point by point:

1. Agree we are headed in that direction, but at the moment is more fruitful and playful to have a simple map and move to a  more complicated spec as soon as we realize it is (and it will be) necessary.
2. Yes!
3. There should be a few callbacks and all methods of the class `Form` and eventually `Field` should be overrideable. Also keep in mind the cat has a working memory to store and retrieve arbitrary information, so whenever the form is not enough, context will be available everywhere in the framework.

Thanks! Join us in the Discord to discuss this further and have some live coding sessions :D
Or you can directly propose a spec (or suggest a library that already does it). At the moment we are focusing on pydantic and many LLM specific tools - none of them really does what we need. Fun time!

**Comment by giovannialbero1992** [comment]
Hi all, I'd like to discuss about this feature. Do you think that is possible catch the intent and propose the form on a specific set of intent. Like if the cat intercepts the intent to order a pizza, it'll start to ask anything defined in the form.
@pieroit if you want we could have a discussion in discord tomorrow or even next days.

**Comment by pieroit** [comment]
> Hi all, I'd like to discuss about this feature. Do you think that is possible catch the intent and propose the form on a specific set of intent? Like if the cat intercepts the intent to order a pizza, it'll start to ask anything defined in the form object. @pieroit if you want we could have a discussion in discord tomorrow or even next days.

Absolutely @giovannialbero1992 !
A way to do it is to have that Form instance live in working memory (triggered by a `@tool` - aka an intent) and try to parse incoming messages to fill up the fields and automatically pose questions on what is missing.

Tag me in the Discord I'll gladly bring you onboard in this conversation
Thanks

**Comment by pieroit** [comment]
### Discord meeting notes:
- how to stop/remove the form
- to start a form, just put it in working memory
-  `Form` and `Field` should be general and customizable
- few shot starting from a list of dictionaries
- ask for confirmation before submit
- two classes (pydantic and `Form`) or subclass `Form` ?

**Comment by pieroit** [comment]
Output of Discord reunion
Messy but beautiful

![Screenshot from 2024-02-13 20-48-28](https://github.com/cheshire-cat-ai/core/assets/6328377/c31e420a-af5c-4ff8-9be8-fd9097c0d4af)

**Comment by pieroit** [comment]
Closing this issue as we've got the best conversational form spec worldwide in `cat.experimental`

![image](https://github.com/cheshire-cat-ai/core/assets/6328377/d22ea97a-2559-4178-bf89-9e05c8521c49)
