### ISSUE TITLE
Access the app from another IP

### ISSUE THREAD

**Issue by pribadihcr** [cheshire-cat-ai/core#494]
Hi, I got the error message "Something went wrong while connecting to the server" when try to access /public in another IP

Here the logs:
"cheshire_cat_vector_memory    | [2023-10-18T03:52:10.846Z INFO  actix_web::middleware::logger] 172.22.0.3 "PUT /collections/episodic/points?wait=true HTTP/1.1" 200 92 "-" "python-httpx/0.25.0" 0.000936
cheshire_cat_core             | INFO:     192.168.2.161:38176 - "GET / HTTP/1.1" 304 Not Modified
cheshire_cat_core             | INFO:     192.168.2.161:38176 - "GET /favicon.ico HTTP/1.1" 404 Not Found
"

Thanks

**Comment by pieroit** [comment]
Is the problem only for `/public` or all the endpoints?

**Comment by AlessandroSpallina** [comment]
@pribadihcr modify the file in core/cat/public/settings.js in order to let the frontend know the baseUrl and the port of your cheshire cat instance

**Comment by pieroit** [comment]
Thanks @AlessandroSpallina this is not documented in fact

**Comment by pribadihcr** [comment]
> @pribadihcr modify the file in core/cat/public/settings.js in order to let the frontend know the baseUrl and the port of your cheshire cat instance

Thanks @AlessandroSpallina It's work now
