### ISSUE TITLE
Test to send message via curl

### ISSUE THREAD

**Issue by pribadihcr** [cheshire-cat-ai/core#495]
Hi How to test to send message from websocket via curl /command cli?, since the endpoint is not available in /docs.

Thanks.

**Comment by zAlweNy26** [comment]
The websocket route is [here](https://github.com/cheshire-cat-ai/core/blob/main/core/cat/routes/websocket.py#L79).

**Comment by pribadihcr** [comment]
> The websocket route is [here](https://github.com/cheshire-cat-ai/core/blob/main/core/cat/routes/websocket.py#L79).

ok thanks. I just know there is python client api to test https://github.com/cheshire-cat-ai/api-client-py

**Comment by zAlweNy26** [comment]
Yeah, and a js/ts API client also [here](https://github.com/cheshire-cat-ai/api-client-ts). Also one in PHP [here](https://github.com/AlboCode/ccatphp-sdk)
