### ISSUE TITLE
Detect duplicate data/chunk before convert to embedding

### ISSUE THREAD

**Issue by pribadihcr** [cheshire-cat-ai/core#503]
Hi, 

Is there a logic to detect duplicate data before converting it into the embedding vector?

I have tried to ingest the same data, and it allows duplication in the vector store at the moment.

Thanks

**Comment by valentimarco** [comment]
@AlessandroSpallina wrote a plugin for this purpose: Detect if you ingest the same file/data and skip the rabbit_hole [plugin](https://github.com/AlessandroSpallina/ccat-dietician)
