### ISSUE TITLE
[BUG] type object 'LLMDefaultConfig' has no attribute 'model_json_schema' (Fail on docker compose up)

### ISSUE THREAD

**Issue by Roby91** [cheshire-cat-ai/core#507]
Fail on "docker compose up" starting with clean project.
I tried with latest cloned repo, with releases "1.2.0" and "1.1.2".

I get the following error at startup:

AttributeError: type object 'LLMDefaultConfig' has no attribute 'model_json_schema'

![Screenshot 2023-10-19 18 44 10](https://github.com/cheshire-cat-ai/core/assets/12767821/4b4d75dc-a243-4a7c-b321-7f0ec4f6bd93)

**Comment by pieroit** [comment]
You need to rebuild

Follow the update instructions:
https://cheshire-cat-ai.github.io/docs/guides/update-the-core/
