### ISSUE TITLE
Add CustomEmbedding class in factory

### ISSUE THREAD

**Issue by pribadihcr** [cheshire-cat-ai/core#508]
Hi, Is there tutorial how to custom the embedding model like custom LLM here https://cheshirecat.ai/2023/08/19/custom-large-language-model/

I want to try this embedding https://huggingface.co/BAAI/bge-small-en-v1.5

Thanks

**Comment by pieroit** [comment]
Are you able to add a class for CustomEmbrdder here?
https://github.com/cheshire-cat-ai/core/blob/main/core/cat/factory/custom_embedder.py

I'll assign the issue to you or anyone interested in doing it

**Comment by nickprock** [comment]
Hi @pieroit I can try.

**Comment by pieroit** [comment]
Assigned @nickprock thanks

**Comment by valentimarco** [comment]
Yes 💖

**Comment by nickprock** [comment]
> Assigned @nickprock thanks
> It would be great if you involve in this also @valentimarco who is experimenting with local models
> 

Ok, I will create a thread on discord tomorrow.
@pieroit @valentimarco
