### ISSUE TITLE
[BUG] Plugin files' names can't start with ".py" 

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/core#514]
**Describe the bug**
The Cat is not able to load plugins that have modules whose names start with ".py" because, when importing those modules, the Cat replaces ".py" with an empty string (see [here](https://github.com/cheshire-cat-ai/core/blob/464bbe3cbc9a6c544701f1ec478a120df3f288d7/core/cat/mad_hatter/plugin.py#L37)).

E.g. a plugin `cat/plugins/pythonic/pythonic.py` breaks the plugin activation because the imported module becomes `cat.plugins.pythonicthonic.

**To Reproduce**
Steps to reproduce the behavior (as exampple`):
1. Create a plugin file named `pythonic/pythonic.py`
2. Enable it

**Comment by pieroit** [comment]
Should suffice to substitute [here](https://github.com/cheshire-cat-ai/core/blob/0334330475254817c8480644c385975f37a42409/core/cat/mad_hatter/plugin.py#L230C13-L230C71):
`py_filename = py_file.replace("/", ".").replace(".py", "")`
with:
`py_filename = py_file.replace(".py", "").replace("/", ".")`
