### ISSUE TITLE
User Feedback 

### ISSUE THREAD

**Issue by pribadihcr** [cheshire-cat-ai/core#517]
Hi, is there user feedback features. For example, user will click the button like/dislike in the right bellow of the response. 

Thanks

**Comment by zAlweNy26** [comment]
Not at the moment, do you have any suggestions on how to do that?

**Comment by zAlweNy26** [comment]
@pribadihcr anyway, next time join the discord if you want to ask something. The issues section are called in this way for a reason.

**Comment by pieroit** [comment]
Too soon for this.Thanks anyway :D
