### ISSUE TITLE
[Feature] Set a default ip for ollama settings 

### ISSUE THREAD

**Issue by valentimarco** [cheshire-cat-ai/core#524]
Right now, there isn't a default ip for the settings of ollama. 
I thought about using ```host.docker.internal``` that is a particular string for docker and with this the localhost don't point inside the container but outside.
So i can use ```http://localhost:11443``` in the settings of ollama, and point outside the container!
(This need also to be in the Ollama runtime container of course)

[Source of this info](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach)

**Comment by kodaline** [comment]
Give it to me :D @pieroit

**Comment by pieroit** [comment]
We sure the `0.0.0.0` hack works?
We can have that as default address for Ollama

**Comment by valentimarco** [comment]
Resolved by #857 merge.
