### ISSUE TITLE
Declarative and procedural memories default configurations are inverted in hook execution

### ISSUE THREAD

**Issue by piust** [cheshire-cat-ai/core#529]
While navigating the cat's code I found this lines in cheshire_cat.py:

https://github.com/cheshire-cat-ai/core/blob/464bbe3cbc9a6c544701f1ec478a120df3f288d7/core/cat/looking_glass/cheshire_cat.py#L297-L303

The configurations of declarative and procedural memories are inverted.

Not a problem if you use the default configurations because they are identical but maybe they should be fixed.

**Comment by pieroit** [comment]
Already fixed in `develop` #526 
Thanks for signaling and welcome :)
