### ISSUE TITLE
[Feature] Add `link` key in the embedders config

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/core#530]
**Describe the solution you'd like**
For consistency, it could be useful to add a `link` key to the embedder configs, like there is in the LLM [config](https://github.com/cheshire-cat-ai/core/blob/464bbe3cbc9a6c544701f1ec478a120df3f288d7/core/cat/factory/llm.py#L107). Also it is missing in the LLaMa CPP [config](https://github.com/cheshire-cat-ai/core/blob/464bbe3cbc9a6c544701f1ec478a120df3f288d7/core/cat/factory/llm.py#L79).

**Comment by mustafaazad03** [comment]
Hi, This issue is very easy but I have doubts that which link URLs to insert or if this can be copied from LLM config itself. also, I am curious to know what enhancement will be done after adding the link ??

**Comment by nicola-corbellini** [comment]
Hi @mustafaazad03, if I'm not wrong, most of the vendors have specific links pointing to the available embedders lists (e.g. see https://platform.openai.com/docs/models/embeddings).

Concerning the `EmbedderFakeConfig` and the `EmbedderDumbConfig`, I would prepare a `link` key with an empty string.
We'll later fill it with specific links pointing to where the documentation explains what those two are.

The enhancement consists in having this pink link button in the settings:
![immagine](https://github.com/cheshire-cat-ai/core/assets/67009524/385b6790-878e-4555-a62a-189571176534)

**Comment by mustafaazad03** [comment]
Okay, I got it thanks for explaining @nicola-corbellini.
Can I make a contribution here, if any challenging issues are there pls let me know I will try to solve them.

**Comment by nicola-corbellini** [comment]
Ok I assigned it to you, thank you.

For more challenging issues take a look e.g. at Issues #522, #514 or #454. You will need to dive deeper in the code to solve these.

**Comment by mustafaazad03** [comment]
Hi, Pls check PR for the same.

**Comment by mustafaazad03** [comment]
Please add the hacktoberfest accepted label so that this PR will be accepted

**Comment by mustafaazad03** [comment]
Hi @nicola-corbellini,
Can you pls add this PR?

**Comment by nicola-corbellini** [comment]
@mustafaazad03 I left you a comment in the PR

**Comment by mustafaazad03** [comment]
Hi, Sorry I forgot that but yah I made new PR for that branch ?
