### ISSUE TITLE
[Feature] Reranker

### ISSUE THREAD

**Issue by pribadihcr** [cheshire-cat-ai/core#553]
Hi, is there reranker model after initial retrieved documents?. For example using this model https://huggingface.co/BAAI/bge-reranker-large . In my experiment it can boost 20% accuracy

Thanks

**Comment by pieroit** [comment]
Not by default, but you can easily add one via plugin

For example "lost in the middle" by @nickprock 
https://github.com/Furrmidable-Crew/lost-in-the-middle

(You should be able to install it directly from the admin plugins page)

**Comment by nickprock** [comment]
Hi @pribadihcr check this post on Discord

https://discord.com/channels/1092359754917089350/1173313817678184529/1173313817678184529

**Comment by pribadihcr** [comment]
> Hi @pribadihcr check this post on Discord
> 
> https://discord.com/channels/1092359754917089350/1173313817678184529/1173313817678184529

Hi @nickprock ok thanks
