### ISSUE TITLE
Restore previous embedder settings if the new ones generate an exception

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#554]
Enpoint to change embedder `PUT /embedder/settings/` has been fixed in PR #552 to handle exceptions in `load_memory`. When the exception occurs, embedder settings are deleted.

It can be further improved by saving precedent embedder settings and in case the new settings generate an exception, all is reverted

**Comment by kodaline** [comment]
Nice, here to take care of it :)
