### ISSUE TITLE
[BUG] - Websockets implementation is broken when using API_KEY

### ISSUE THREAD

**Issue by zioproto** [cheshire-cat-ai/core#563]
**Describe the bug**
The current Websockets implementation is broken when using `API_KEY`, it has issues accepting a broken trying to reconnect.

The core container prints this error message:
```
cheshire_cat_core           | ERROR:    ASGI callable returned without sending handshake.
```

**To Reproduce**
1. Start the core container with the `API_KEY`
2. Use the `/admin` path and start using the cat (enter the `API_KEY` when prompted by the web interface)
3. Refresh the page, enter the `API_KEY` again in the pop-up window.
4. Observe that the text box is grey out, and you cannot write anymore because the websockets connection is failing.

**Additional context**
I suspect here you can't just return and ignore a new connection:
https://github.com/cheshire-cat-ai/core/blob/0185e2435d78894a3f246d099f467099b64931a7/core/cat/routes/websocket.py#L83-L94

**Comment by Pingdred** [comment]
Have you tried in develop?  A few days ago I added a ws exception in case two connections are opened with the same user id

**Comment by zioproto** [comment]
Yes I tried the `develop` branch after PR https://github.com/cheshire-cat-ai/core/pull/556

The error changed in the logs:
```
cheshire_cat_core           | [2023-11-15 15:38:40.948] ERROR  cat.routes.websocket..websocket_endpoint::94 => "A websocket connection with ID 'user' has already been opened."
```

But the buggy behaviour is exactly the same.

**Comment by Pingdred** [comment]
Ok then it seems that the old websocket connection is not closed with the page refresh, so that the core refuse the new connection, can you check if after the refresh the  in the cat's logs appears
```
cheshire_cat_core  | INFO:     connection closed
```

before (not necessarily in the previous line)

```
cheshire_cat_core | ERROR  cat.routes.websocket..websocket_endpoint::94 => "A websocket connection with ID 'user' has already been opened."
```
Thanks

**Comment by zioproto** [comment]
Here the log snippet:
```
cheshire_cat_core           | INFO:     192.168.65.1:60896 - "GET /plugins/settings/ HTTP/1.1" 403 Forbidden
cheshire_cat_core           | INFO:     192.168.65.1:60893 - "GET /plugins/ HTTP/1.1" 403 Forbidden
cheshire_cat_core           | INFO:     192.168.65.1:60894 - "GET /memory/collections/ HTTP/1.1" 403 Forbidden
cheshire_cat_core           | [2023-11-15 15:38:40.948] ERROR  cat.routes.websocket..websocket_endpoint::94 => "A websocket connection with ID 'user' has already been opened."
cheshire_cat_core           | INFO:     ('192.168.65.1', 60897) - "WebSocket /ws/user" 403
cheshire_cat_core           | INFO:     connection failed (403 Forbidden)
cheshire_cat_core           | INFO:     192.168.65.1:60896 - "GET / HTTP/1.1" 200 OK
cheshire_cat_core           | [2023-11-15 15:38:40.966] INFO   cat.routes.websocket..websocket_endpoint::111 => 'WebSocket connection closed'
cheshire_cat_core           | [2023-11-15 15:38:40.980] INFO   cat.routes.websocket..websocket_endpoint::124 => "Removed WebSocket connection with ID 'user'"
cheshire_cat_core           | INFO:     connection closed
cheshire_cat_core           | INFO:     connection closed
```

**Comment by pieroit** [comment]
Cannot reproduce this error anymore
