### ISSUE TITLE
Web Interface Unavailable After Docker Reboot, Hindering API Key Correction 

### ISSUE THREAD

**Issue by ethanlacerenza** [cheshire-cat-ai/core#572]
**Describe the Bug:**
Upon entering an invalid OpenAI API key, if an error message is generated, and the Docker is subsequently restarted, the system retains the erroneous modification. This prevents the interface from restarting, hindering the ability to manually correct the issue.

**To Reproduce:**

- Insert an invalid OpenAI API key. If it's an invalid or (finished quota) API key, remain blocked here.

![Screenshot 2023-11-16 alle 17 32 01](https://github.com/cheshire-cat-ai/core/assets/71321892/af3d51c5-b4dc-4f41-ade3-0981cd3c7bc0)

- Execute docker-compose stop followed by docker-compose start.
- Observe the error: the web server does not remain operational, preventing the modification of the API key.

![Screenshot 2023-11-16 alle 17 33 28](https://github.com/cheshire-cat-ai/core/assets/71321892/e3cad635-f064-4720-b714-f98e9cb9aa27)

Expected Behavior:
After rebooting, the system restricts access to the web interface, thereby impeding the user's ability to modify the API key. This issue results in a critical barrier, as the web interface serves as the primary means for users to make manual corrections to the API key. Consequently, the lack of access prevents any immediate resolution of the erroneous key, posing a significant obstacle to the proper functioning of the system. A seamless restart of the interface after a Docker reboot is essential for users to efficiently rectify any API key-related issues and ensure the smooth operation of the application

**Comment by valentimarco** [comment]
If you delete metadata.json, you are able to reuse the admin interface.
We should check if the api_key is valid before insert it in db, do you agree @pieroit ?

**Comment by ethanlacerenza** [comment]
@valentimarco You can proceed with this, but be aware that the usage quota may expire during the process. The API key will still be stored in the database but will become non-functional later on.

**Comment by ethanlacerenza** [comment]
I think I've understood how to handle the exception. If you want, I can run some tests, and if it works, I'll open a pull request in the develop branch 😸

**Comment by pieroit** [comment]
> I think I've understood how to handle the exception. If you want, I can run some tests, and if it works, I'll open a pull request in the develop branch 😸

Where would you put the exception handling?
We had PR #470  about this but was too complex and too tied to openai - should be able to surface any problem related with LLM setup as we did for embedders in #552

**Comment by ethanlacerenza** [comment]
I am seeking a more comprehensive solution without relying on OpenAI libraries. I would prefer that, in case of failure, the system provides an error message and automatically resets the language to the default language model.

I have observed that the solution proposed in issue #552  appears to be ineffective in addressing this issue. Did it initially work?

**Comment by pieroit** [comment]
> I am seeking a more comprehensive solution without relying on OpenAI libraries. I would prefer that, in case of failure, the system provides an error message and automatically resets the language to the default language model.

Thanks @ethanlacerenza 
Check the solution found for embedders:
https://github.com/cheshire-cat-ai/core/blob/11b86cfb327afcb865cfee49b43048bb17c0e247/core/cat/routes/embedder.py#L109

**Comment by ethanlacerenza** [comment]
@pieroit Let me know if you think it's okay; otherwise, I'll continue working on it. It seems like the simplest solution to me
