### ISSUE TITLE
[BUG] Cat doesn't fetch new parsers when added in the hook

### ISSUE THREAD

**Issue by zAlweNy26** [cheshire-cat-ai/core#577]
**Describe the bug**
When I make a plugin with the `rabbithole_instantiates_parsers` hook, the cat and the relative endpoint don't see the newly added parser when refreshing. I have to stop and start again the cat to make the change effective.

**Expected behavior**
The refresh of the Cat (when modifying code for example), should be enough to make the change effective.

**Comment by pieroit** [comment]
@zAlweNy26 could you check if this is fixed on develop?
You should see parsers automatically updated at every upload and you can still send ws messages, user specific, with `cat.send_ws_message`

**Comment by zAlweNy26** [comment]
Ok thanks, I'll check
