### ISSUE TITLE
Tag docker ghcr image with version

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#580]
At the moment all docker images automatically built [with this workflow](https://github.com/cheshire-cat-ai/core/blob/c70db3ee1a738fa6d19b2cd29b3d6a19a45e1d35/.github/workflows/tag.yml#L33) are tagged as `ghcr.io/cheshire-cat-ai/core:latest`
It could be useful to have all mid version tagged separatedly `:1.3.1`, `:1.3.2`, etc.

Not a priority, just here for reference

**Comment by ethanlacerenza** [comment]
@pieroit If you want, I'll take care of working on this :)
