### ISSUE TITLE
[Feature] Please add documentation on how to run it within China.

### ISSUE THREAD

**Issue by horw** [cheshire-cat-ai/core#603]
I suggest that, since there are many people in China interested in LLM in general, it may attract more users if we provide a simpler way to run it, such as by setting up a proxy.

If you are from the Chinese community here, you can react to this issue or leave a comment. This way, we can address it more objectively.

**Is your feature request related to a problem? Please describe.**
In China, you need to set up a proxy to run OpenAI stuff.

**Describe the solution you'd like**
I use the `http_proxy` environment variable in `docker-compose`, with `network_mode` set to `host`.

**Comment by AlessandroSpallina** [comment]
Should we just document how to pass the http_proxy environment variable to a container or insert a setting on the admin panel?

**Comment by valentimarco** [comment]
> Should we just document how to pass the http_proxy environment variable to a container or insert a setting in the admin panel?

I prefer to Just document the all process.
What do you think @pieroit ?

**Comment by pieroit** [comment]
@valentimarco @AlessandroSpallina @horw ok for giving an example of proxy config via docker, let's just document with a blog post and open an issue in the `docs` repo to figure out where to put this information
