### ISSUE TITLE
LLM adapter for OpenAI mock apis

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#604]
Both [`llama-cpp-python`](https://github.com/abetlen/llama-cpp-python) and [`text-generation-webui`](https://github.com/oobabooga/text-generation-webui) imitate OpenAI api spec to allow local network usage of LLMs.

Since we have already a "pseudo" [OpenAI adapter class](https://github.com/cheshire-cat-ai/core/blob/0f7f06dec24a44d3338e93886a1095b72820e92f/core/cat/factory/custom_llm.py#L73), we can use only an element in the [LLM factory](https://github.com/cheshire-cat-ai/core/blob/main/core/cat/factory/llm.py) and put into the [description](https://github.com/cheshire-cat-ai/core/blob/0f7f06dec24a44d3338e93886a1095b72820e92f/core/cat/factory/llm.py#L105) that the adapter is compatible with any endpoint imitating OpenAI (saying also explicitly that TextGenWebUI and llama.cpp are included)

**Comment by AlessandroSpallina** [comment]
I can take care of it

**Comment by pieroit** [comment]
OpenRouter (#620 ) also can included in this, the LLM adapter should be called `OpenAI compatible service` ro something like that. It has become a de facto standard

**Comment by AlessandroSpallina** [comment]
even [TinyLLM](https://github.com/jasonacox/TinyLLM) is using the same

**Comment by pieroit** [comment]
Thanks @AlessandroSpallina
