### ISSUE TITLE
Add user_id metadata to declarative collection points

### ISSUE THREAD

**Issue by cristianorevil** [cheshire-cat-ai/core#615]
I have currently setup a multiuser instance of the cat (every user connect with websocket_url/username) and all works very well, every user has proper chat history and episodic memory retrivial. The "problem" is for declarative because actually is shared to all users. Implementing a "filter" also for this collection permit the user segmentation of the collection (and open the cat to develop GPTS like features)

**Describe the solution you'd like**
1. Add the check user_id header to /rabbithole/ http endpoint (user_id = request.headers.get("user_id", "user"))
2. Add a new meta to the collection point: doc.metadata["user_id"] = user_id
3. Implement the metadata "user_id" filter into declarative method

@pieroit what do you think?

**Comment by AlessandroSpallina** [comment]
let’s keep in mind that we should think about different “layers” of declarative memory:
* common memory: memories common to all users
* group memory: memories to be recalled only if the user is in that group 
* user memory: private memories

**Comment by nicola-corbellini** [comment]
I think it is already feasible.

`doc.metadata["user_id"] = user_id` can be added using the `RabbitHole` hooks, e.g. [here](https://github.com/cheshire-cat-ai/core/blob/e6eabe6706ae810f66cf4ca0024e3d65824e0490/core/cat/rabbit_hole.py#L338). The `user_id` is available under `cat.user_id` in the `StrayCat` instance that the hook takes as an argument.
The same, filtering can be done setting the `metadata` [key](https://github.com/cheshire-cat-ai/core/blob/e6eabe6706ae810f66cf4ca0024e3d65824e0490/core/cat/looking_glass/stray_cat.py#L134) using [this hook](https://github.com/cheshire-cat-ai/core/blob/e6eabe6706ae810f66cf4ca0024e3d65824e0490/core/cat/looking_glass/stray_cat.py#L150)

Please, correct me if I've misunderstood

**Comment by cristianorevil** [comment]
> let’s keep in mind that we should think about different “layers” of declarative memory:
> 
> * common memory: memories common to all users
> * group memory: memories to be recalled only if the user is in that group
> * user memory: private memories

WOW, different layers will be awesome and open endless possibilities

**Comment by cristianorevil** [comment]
> I think it is already feasible.
> 
> `doc.metadata["user_id"] = user_id` can be added using the `RabbitHole` hooks, e.g. [here](https://github.com/cheshire-cat-ai/core/blob/e6eabe6706ae810f66cf4ca0024e3d65824e0490/core/cat/rabbit_hole.py#L338). The `user_id` is available under `cat.user_id` in the `StrayCat` instance that the hook takes as an argument. The same, filtering can be done setting the `metadata` [key](https://github.com/cheshire-cat-ai/core/blob/e6eabe6706ae810f66cf4ca0024e3d65824e0490/core/cat/looking_glass/stray_cat.py#L134) using [this hook](https://github.com/cheshire-cat-ai/core/blob/e6eabe6706ae810f66cf4ca0024e3d65824e0490/core/cat/looking_glass/stray_cat.py#L150)
> 
> Please, correct me if I've misunderstood

I have been away from the cat for a while, so maybe i miss some important new features ecc! I will check the code reference you are linked and do some tests, i have only one doubt, adding a file via rabbithole http endpoint actually user_id headr is not readed, so how the cat can identify the user to set metadata correctly?

**Comment by nicola-corbellini** [comment]
> maybe adding request.headers.get("user_id", "user") into hook here

That is performed [here](https://github.com/cheshire-cat-ai/core/blob/e6eabe6706ae810f66cf4ca0024e3d65824e0490/core/cat/headers.py#L62). Hence, the endpoint now relies on this "session" [concept](https://github.com/cheshire-cat-ai/core/blob/e6eabe6706ae810f66cf4ca0024e3d65824e0490/core/cat/routes/upload.py#L24).

**Comment by valentimarco** [comment]
> let’s keep in mind that we should think about different “layers” of declarative memory:
> 
>     * common memory: memories common to all users
> 
>     * group memory: memories to be recalled only if the user is in that group
> 
>     * user memory: private memories
 UwU we should open a issue for this feature!

**Comment by pieroit** [comment]
Agree with @nicola-corbellini it's already possible via plugin

Same about group level memories, better experiment on ACL in a plugin and see if we can improve hooks to allow flexibility

Thanks all great discussion!

**Comment by cristianorevil** [comment]
@nicola-corbellini thank you. I confirm all works as expected! Now is possible for me to try to develop multiassistant cat (like GPTs)
