### ISSUE TITLE
Azure OpenAI LLM - The answers are showing part of the prompt context and instructions

### ISSUE THREAD

**Issue by Roby91** [cheshire-cat-ai/core#618]
I'm having bad answers in fresh installed 1.4.3 version.

The answers are always showing part of the prompt context and instructions as you can see from the screenshots.
I've started from a fresh docker installation (reset the docker to factory settings), deleted all the old cheshire cat folders.
I'm using Azure OpenAI as LLM (and embedder).

![Screenshot 2023-12-09 195124](https://github.com/cheshire-cat-ai/core/assets/12767821/574e4b27-7c3f-49ac-b7f3-6022b87fa797)

![Screenshot 2023-12-09 200309](https://github.com/cheshire-cat-ai/core/assets/12767821/5efb0534-ec8a-4493-9c07-0a72acee851a)

![Screenshot 2023-12-09 194930](https://github.com/cheshire-cat-ai/core/assets/12767821/f52df8bf-fec4-4fd9-aeec-bd2af600dcd4)

**Comment by valentimarco** [comment]
the LLM response correctly but continues the prompt. Check if you can set some stop strings on AzureAI, if not idk what say bc this is the first time i see problem with AzureAI...

**Comment by Roby91** [comment]
I can ensure you I had no problems with old versions of the cat (not sure about the version but at least previous then 1 month ago) and that I didn't change (redeployed) Azure OpenAI models.. Maybe something is changed in the prompt creation with the latest versions?

**Comment by pieroit** [comment]
@Roby91 thanks for signaling, I agree it is a "stop" token problem
Let me tag somebody in the community a little more expert on Azure @zioproto @cristianorevil

**Comment by zioproto** [comment]
@Roby91 can you share your configuration ? (remove the API key of course ). What model are you using ? Are you using `LLMAzureOpenAIConfig` or `LLMAzureChatOpenAIConfig` ?

**Comment by Roby91** [comment]
@zioproto here is my metadata.json:

[metadata.json](https://github.com/cheshire-cat-ai/core/files/13645862/metadata.json)

I'm using "LLMAzureOpenAIConfig" because my model is completion.

**Comment by zioproto** [comment]
Your configuration is wrong.

with the model `gpt-35-turbo` you have to use in the menu "Azure OpenAI Chat Models", because `gpt-35-turbo` is a chat model. 

You are using " "Azure OpenAI Completion models". This one was used in the past with the model `text-davinci-003` that is a completion model (now deprecated).

Please fix the config and try again.

Related code:
See the comment ` # Use only completion models ! `
https://github.com/cheshire-cat-ai/core/blob/e6eabe6706ae810f66cf4ca0024e3d65824e0490/core/cat/factory/llm.py#L127-L170

**Comment by Roby91** [comment]
Ok thanks.
In Azure AI Studio the "gpt-35-turbo" is flagged as "Completion" so that's why I was using completion model setting in the cat (which worked well in old versions).

Anyway, i tried switching to "Azure OpenAI Chat Models" and looks like it works for "regular" questions but it behaves strange when plugins are involved.

![Screenshot 2023-12-12 10 47 11](https://github.com/cheshire-cat-ai/core/assets/12767821/f4e2446b-d74d-4999-98aa-2999a4345464)

![Screenshot 2023-12-12 10 49 59](https://github.com/cheshire-cat-ai/core/assets/12767821/f96dff72-0e1c-460d-8a94-b9324948b832)

**Comment by zioproto** [comment]
@Roby91 sorry for the confusion. The `gpt-35-turbo` is indeed a "Completion" model that is meant for the "Chat" use-case.  The Azure Portal says Completion to distinguish from other models that do completely different things like "Embeddings".

If you think it would help, please feel free to propose a patch to change the "Azure OpenAI Chat Models" wording with something that contains "Chat Completion" and it is more easy to understand.

Thanks

**Comment by zioproto** [comment]
@pieroit I am not able to comment on the problem with the specific plugin.

If I understand correctly @Roby91 is activating plugins that are altering the prompts, and the tools are not working correctly anymore. 

This should not be Azure specific and requires @pieroit or somebody from the core team to have a closer look.

**Comment by zioproto** [comment]
> @zioproto @Roby91 a model is completion OR chat

It is called "Chat Completion API" in the documentation. Because the word `completion` is always used, this caused the confusion.

https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/chatgpt?tabs=python&pivots=programming-language-chat-completions

![Screenshot 2023-12-22 at 10 53 07](https://github.com/cheshire-cat-ai/core/assets/789701/70c82a34-e723-410d-b872-f2545f3c0818)

**Comment by pieroit** [comment]
Ok thanks for clarifying @zioproto 

@Roby91 can you try a fresh install? Pull the image again 
Cannot repeat the issue

**Comment by Roby91** [comment]
@pieroit @zioproto 

I removed all Docker images, downloaded 1.4.3 zip release, opened it via "docker compose up".
Configured Azure OpenAI Chat, with "Streaming" flag off (what's that for by the way?).
No plugins installed (except the Core CCat).

After lot of attempts I can say that, the issue happens with random frequency but may be related to "Clear conversation" action:
if it happens it does just as the first answer (at least for all my tests).

To reproduce the issue I do this:
start a new conversation, if the answer is ok I "clear conversation" and try with a random question (from the suggested ones).
Sometimes I get the wrong answer right away, sometimes after 3 attempts, sometimes after 10 attempts.
I cannot find similarities or strange patterns between questions.
Maybe is useful to notice that in 2 of 4 of the following screenshoots there is the "what time is it" question involved inside the full prompt of the answer that fails.

![screencapture-localhost-1865-admin-2023-12-24-18_55_55](https://github.com/cheshire-cat-ai/core/assets/12767821/739a6f53-0f34-42c7-9f2b-14aadc077207)

![screencapture-localhost-1865-admin-2023-12-24-18_56_46](https://github.com/cheshire-cat-ai/core/assets/12767821/7745feab-a014-4abf-a058-23b5ee1e44a3)

![screencapture-localhost-1865-admin-2023-12-24-19_06_50](https://github.com/cheshire-cat-ai/core/assets/12767821/00e4dba7-2c24-492e-b3b9-7d2bc355bffd)

![screencapture-localhost-1865-admin-2023-12-24-19_03_07](https://github.com/cheshire-cat-ai/core/assets/12767821/b21c1b9c-ff45-4f42-a12f-6df81c6c36b2)
