### ISSUE TITLE
Plugin compatibility with Cat version

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#622]
We need to define properly:
- how do plugins say what versions they support
- how does core check for compatibility

**Comment by valentimarco** [comment]
1. Add a obligatory property on the json like `"Core Version"` or `"compatible version"`
3.  By equal comparison (we can than expand with a >=). Here we can choose 2 ways i think: use the version tag of the pyproject.toml or add the property in the `core_plugin/plugin.json` (this need to be sync with the pyproject.toml)
When a plugin have a different version than we disable the plugin if is installed or deny the installation from the registry

**Comment by Greg0026** [comment]
Should we make the plugin uninstallable or make sure it doesn't activate?

**Comment by Greg0026** [comment]
> > Should we make the plugin uninstallable or make sure it doesn't activate?
> 
> Hi @Greg0026 thanks It looks like big plugin powered systems like WordPress do not deal with this. They just let you know which version the plugin is tested with, and then it's up to the admin to decide.
> 
> What do you think

I think we could add an optional property in the plugin.json file like 'compatible version' (as @valentimarco already said), and then compare it to the current version of the cat and raise an exception when the plugin is activated. Anyway I think this fix is ​​useful, even if it is rare that the cat version affects a plugin. It could be fixed in a few lines of code, something like this:
![Screenshot (41)](https://github.com/cheshire-cat-ai/core/assets/77922539/68d79328-0a2d-44b2-a73f-409313ebbcaf)

**Comment by pieroit** [comment]
> > > Should we make the plugin uninstallable or make sure it doesn't activate?
> > 
> > 
> > Hi @Greg0026 thanks It looks like big plugin powered systems like WordPress do not deal with this. They just let you know which version the plugin is tested with, and then it's up to the admin to decide.
> > What do you think
> 
> I think we could add an optional property in the plugin.json file like 'compatible version' (as @valentimarco already said), and then compare it to the current version of the cat and raise an exception when the plugin is activated. Anyway I think this fix is ​​useful, even if it is rare that the cat version affects a plugin. It could be fixed in a few lines of code, something like this: ![Screenshot (41)](https://private-user-images.githubusercontent.com/77922539/291094553-68d79328-0a2d-44b2-a73f-409313ebbcaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MDE1NTAsIm5iZiI6MTcwMjkwMTI1MCwicGF0aCI6Ii83NzkyMjUzOS8yOTEwOTQ1NTMtNjhkNzkzMjgtMGEyZC00NGIyLWE3M2YtNDA5MzEzZWJiY2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDEyMDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwZGQ4MmY4NmQ3ZWZhYjE4MzRlMDg3ZTQwNmVlYTJhYzk5MmY3YTc3ODM3Zjg5OWMzNDI3YTg5MmExMjVhM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ei4WqaxtjPju-H3G6dO9alni0woClI6DNi-9fe6pgBg)

Yep this is reasonable, let's see how to enforce required cat version in the registry
Let's see what @EugenioPetulla thinks about this

**Comment by pieroit** [comment]
We're abandoning the "compatible with" feature, which no seems too much complicated.
Let's for now establish a plugin update system ( #682  )
