### ISSUE TITLE
ERROR  cat.looking_glass.agent_manager.AgentManager.execute_agent::179 => IndexError('list index out of range')

### ISSUE THREAD

**Issue by pazoff** [cheshire-cat-ai/core#623]
Traceback (most recent call last):

  File "/app/cat/looking_glass/agent_manager.py", line 161, in execute_agent

    if used_tools[-1][0][0] in return_direct_tools:

IndexError: list index out of range

This is from the log file of cheshire_cat_core container
Installed via https://github.com/cheshire-cat-ai/local-cat

**Comment by pieroit** [comment]
When does this happen?
Thanks

**Comment by pazoff** [comment]
Right now.

**Comment by pazoff** [comment]
It happens after asking a question, every time.

**Comment by pazoff** [comment]
I have just reinstalled everything and using a custom LLM using this guide https://cheshirecat.ai/custom-large-language-model/.
The error happens on a fresh install.

**Comment by pazoff** [comment]
It seems it is connected with the custom LLMs option as when using Ollama the error does not reproduce.
