### ISSUE TITLE
Get plugins list from registry (sort by criteria)

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#625]
Core should be able to sort plugins list according to the sort required from the admin

https://github.com/cheshire-cat-ai/plugins-backend/issues/26

**Comment by pieroit** [comment]
Sorting criteria
https://github.com/cheshire-cat-ai/plugins-backend?tab=readme-ov-file#list-all-plugins-paginated

**Comment by kodaline** [comment]
@pieroit is someone already looking at this?

**Comment by pieroit** [comment]
@kodaline are you interested?

**Comment by kodaline** [comment]
> @kodaline are you interested?

yup, it seems interesting and would let me work closer on the core 😁

**Comment by zAlweNy26** [comment]
Are you still working on it @kodaline ?

**Comment by kodaline** [comment]
> Are you still working on it @kodaline ?

I talked with @pieroit for this yesterday, it was told to me to wait when we have at least 100 plugins etc to do this...
