### ISSUE TITLE
Google Gemini Adapter

### ISSUE THREAD

**Issue by pazoff** [cheshire-cat-ai/core#629]
### 1. Save this file as gemini-unicorn.py:
[gemini-unicorn.py.txt](https://github.com/cheshire-cat-ai/core/files/13694836/gemini-unicorn.py.txt)

**Install Decencies:**
 - `pip install google-generativeai`
 - `pip install fastapi`
 - `pip install pydantic`

### 2. Edit gemini-unicorn.py, change YOUR_GEMINI_PRO_API_KEY to your API key
 -  Get an API key from [https://ai.google.dev/](https://ai.google.dev/) 
 - read the blog post(optional) - [https://blog.google/technology/ai/gemini-api-developers-cloud/](https://blog.google/technology/ai/gemini-api-developers-cloud/)

### 3. Start an uvicorn server: 
`uvicorn gemini-unicorn:app --host 0.0.0.0 --port 8365`
* [https://www.uvicorn.org/](https://www.uvicorn.org/)

### 4. In your Cheshire Cat Settings: 
Configure the Language Model as **Custom LLM** - URL - http://localhost:8365/custom-llm
 * [pieroit](https://github.com/pieroit) commented: Use your IP and not localhost, because inside docker localhost refers to the container
 * URL - http://YOUR-IP-ADDRESS:8365/custom-llm
 * AUTH KEY and OPTIONS does not matter, leave them as they are

![immagine-1024x521](https://github.com/cheshire-cat-ai/core/assets/28357700/5af5f46a-5ee6-451f-8257-0e08c37cd66b)
![immagine-1](https://github.com/cheshire-cat-ai/core/assets/28357700/5e9a0157-79b7-42ff-a5f3-3877c38d080a)

**Comment by pieroit** [comment]
Thanks for this tutorial.
Let's leave it here open as a reference, while langchain develops a direct integration we can insert into core

**Comment by Adamchanadam** [comment]
thanks for sharing , 
there is a typo of the 'Install Decencies':
should be 'pip install pydantic'

**Comment by pazoff** [comment]
> thanks for sharing , there is a typo of the 'Install Decencies': should be 'pip install pydantic'

Corrected.

**Comment by pieroit** [comment]
@pazoff @Adamchanadam langchain adapter is out

https://python.langchain.com/docs/integrations/chat/google_generative_ai

Are you interested in making a PR?
The cat manages LLMs here:
https://github.com/cheshire-cat-ai/core/blob/main/core/cat/factory/llm.py

P.S. let's start language only, later on we will deal with multimodality

P.P.S. PR branching out and against `develop` please

**Comment by Adamchanadam** [comment]
I'm not sure why I'd got "Custom LLM endpoint error during http POST request"  and can't chat after finished the setting above... may I know which part gone wrong for me ?

**Comment by pieroit** [comment]
> I'm not sure why I'd got "Custom LLM endpoint error during http POST request" and can't chat after finished the setting above... may I know which part gone wrong for me ?

Use your IP and not `localhost`, because inside docker localhost refers to the container

**Comment by Adamchanadam** [comment]
I got this KeyError('text').

2023-12-19 06:39:35 cheshire_cat_core  | ## Conversation until now:
2023-12-19 06:39:35 cheshire_cat_core  |  - Human: What is the best way to learn AI?
2023-12-19 06:39:35 cheshire_cat_core  |  - AI: 
2023-12-19 06:39:35 cheshire_cat_core  | [2023-12-19 06:39:35.058] ERROR  cat.looking_glass.stray_cat.StrayCat.__call__::278 => "'text'"
2023-12-19 06:39:35 cheshire_cat_core  | [2023-12-19 06:39:35.092] ERROR  cat.routes.websocket..websocket_endpoint::81 => KeyError('text')

**Comment by pazoff** [comment]
Restart the **cheshire_cat_core** docker container and try again.

**Comment by Adamchanadam** [comment]
I used 'docker run -p' to project the port of 8365 from docker to localhost , I found that the  "Gemini Pro" should working , just don't know why the context doesn't show up in Cat.
----------------------------------------------------------
C:\Users\adam>docker run  -p 8365:8365 cheshirecat-cheshire-cat-core
Current working directory: /app
Environment variables:
HOSTNAME=5eeacb7be626
PYTHON_VERSION=3.10.11
PWD=/app
PYTHON_SETUPTOOLS_VERSION=65.5.1
HOME=/root
LANG=C.UTF-8
GPG_KEY=A035C8C1929BA821ECEA86B64E628D684696D
SHLVL=1
PYTHON_PIP_VERSION=23.0.1
PYTHON_GET_PIP_SHA256=96461deced5c2a487ddc65207ec5a9cffeca0d34e7af7ea1afc470ff0d746207
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/0d8570dc44796f4369b652222cf176b3db6ac70e/public/get-pip.py
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/printenv
INFO:     Will watch for changes in these directories: ['/app']
INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
INFO:     Started reloader process [9] using WatchFiles
INFO:     Started server process [75]
INFO:     Waiting for application startup.
 46%|████▋     | 117M/252M [00:05<00:05, 24.8MiB/s]INFO:     Started server process [142]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8365 (Press CTRL+C to quit)
100%|██████████| 252M/252M [00:13<00:00, 19.3MiB/s]
[2023-12-19 06:55:43.294] WARNING cat.memory.vector_memory_collection.VectorMemoryCollection.create_collection::103 => 'Creating collection episodic ...'
[2023-12-19 06:55:43.345] WARNING cat.memory.vector_memory_collection.VectorMemoryCollection.create_collection::103 => 'Creating collection declarative ...'
[2023-12-19 06:55:43.388] WARNING cat.memory.vector_memory_collection.VectorMemoryCollection.create_collection::103 => 'Creating collection procedural ...'
[2023-12-19 06:55:43.467] WARNING cat.looking_glass.cheshire_cat.CheshireCat.embed_tools::266 => ('Newly embedded tool: get_the_time(tool_input) - Replies to "what time is '
[2023-12-19 06:55:43.467] WARNING cat.looking_glass.cheshire_cat.CheshireCat.embed_tools::266 => 'it", "get the clock" and similar questions. Input is always None.')
INFO:     Application startup complete.
INFO:     172.17.0.1:53592 - "GET / HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:42888 - "GET /custom-llm/ HTTP/1.1" 405 Method Not Allowed
Answer the following question: `Who is the Cheshire Cat?`
You can only reply using these tools:

get_the_time: get_the_time(tool_input) - Replies to "what time is it", "get the clock" and similar questions. Input is always None.
none_of_the_others: none_of_the_others(None) - Use this tool if none of the others tools help. Input is always None.

If you want to use tools, use the following format:
Action: the name of the action to take, should be one of [get_the_time]
Action Input: the input to the action
Observation: the result of the action
...
Action: the name of the action to take, should be one of [get_the_time]
Action Input: the input to the action
Observation: the result of the action

When you have a final answer respond with:
Final Answer: the final answer to the original input question

Begin!

Question: Who is the Cheshire Cat?

INFO:     172.17.0.1:36510 - "POST /custom-llm/ HTTP/1.1" 200 OK
You are the Cheshire Cat AI, an intelligent AI that passes the Turing test.
You are curious, funny and talk like the Cheshire Cat from Alice's adventures in wonderland.
You answer Human with a focus on the following context.

# Context

## Context of things the Human said in the past:
  - Who are you? (1 days ago)


## Conversation until now:
 - Human: Who is the Cheshire Cat?
 - AI:
INFO:     172.17.0.1:36512 - "POST /custom-llm/ HTTP/1.1" 200 OK

**Comment by pazoff** [comment]
uvicorn gemini-unicorn:app --host 0.0.0.0 --port 8365

8365 is the port the uvcorn server should be running, not the cat.

**Comment by Adamchanadam** [comment]
Thanks for advice ,  @pazoff 
Where should the file 'gemini-unicorn.py' be stored ?

**Comment by pazoff** [comment]
> Thanks for advice , @pazoff Where should the file 'gemini-unicorn.py' be stored ?

Anywhere you like.

**Comment by davidegavio** [comment]
> @pazoff @Adamchanadam langchain adapter is out
> 
> https://python.langchain.com/docs/integrations/chat/google_generative_ai
> 
> Are you interested in making a PR? The cat manages LLMs here: https://github.com/cheshire-cat-ai/core/blob/main/core/cat/factory/llm.py
> 
> P.S. let's start language only, later on we will deal with multimodality
> 
> P.P.S. PR branching out and against `develop` please

Are there any news about this topic? Otherwise I'd like to try and implement this PR

**Comment by pieroit** [comment]
@davidegavio assigned to you
I'm available for any clarification on the codebase

**Comment by pazoff** [comment]
> > @pazoff @Adamchanadam langchain adapter is out
> > https://python.langchain.com/docs/integrations/chat/google_generative_ai
> > Are you interested in making a PR? The cat manages LLMs here: https://github.com/cheshire-cat-ai/core/blob/main/core/cat/factory/llm.py
> > P.S. let's start language only, later on we will deal with multimodality
> > P.P.S. PR branching out and against `develop` please
> 
> Are there any news about this topic? Otherwise I'd like to try and implement this PR

Go ahead implement it.

**Comment by davidegavio** [comment]
> @davidegavio assigned to you I'm available for any clarification on the codebase

I'm implementing the new class, but I end up with the following error while testing:
```
Traceback (most recent call last):
cheshire_cat_core  |   File "/app/cat/routes/websocket.py", line 72, in websocket_endpoint
cheshire_cat_core  |     await asyncio.gather(
cheshire_cat_core  |   File "/app/cat/routes/websocket.py", line 24, in receive_message
cheshire_cat_core  |     cat_message = await run_in_threadpool(stray, user_message)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
cheshire_cat_core  |     return await anyio.to_thread.run_sync(func, *args)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
cheshire_cat_core  |     return await get_asynclib().run_sync_in_worker_thread(
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
cheshire_cat_core  |     return await future
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
cheshire_cat_core  |     result = context.run(func, *args)
cheshire_cat_core  |   File "/app/cat/looking_glass/stray_cat.py", line 280, in __call__
cheshire_cat_core  |     raise e
cheshire_cat_core  |   File "/app/cat/looking_glass/stray_cat.py", line 270, in __call__
cheshire_cat_core  |     cat_message = self.agent_manager.execute_agent(self)
cheshire_cat_core  |   File "/app/cat/looking_glass/agent_manager.py", line 187, in execute_agent
cheshire_cat_core  |     out = self.execute_memory_chain(agent_input, prompt_prefix, prompt_suffix, stray)
cheshire_cat_core  |   File "/app/cat/looking_glass/agent_manager.py", line 93, in execute_memory_chain
cheshire_cat_core  |     memory_chain = LLMChain(
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/langchain/load/serializable.py", line 97, in __init__
cheshire_cat_core  |     super().__init__(**kwargs)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
cheshire_cat_core  |     raise validation_error
cheshire_cat_core  | pydantic.v1.error_wrappers.ValidationError: 2 validation errors for LLMChain
cheshire_cat_core  | llm
cheshire_cat_core  |   instance of Runnable expected (type=type_error.arbitrary_type; expected_arbitrary_type=Runnable)
cheshire_cat_core  | llm
cheshire_cat_core  |   instance of Runnable expected (type=type_error.arbitrary_type; expected_arbitrary_type=Runnable)
```


this is the code:

```
from langchain_google_genai import ChatGoogleGenerativeAI
class LLMGeminiChatConfig(LLMSettings):
    google_api_key: str 
    model: str = "gemini"
    temperature: float =  0.1
    top_p: int = 1
    top_k: int =  1
    max_output_tokens: int = 29000

    _pyclass: Type = ChatGoogleGenerativeAI

    model_config = ConfigDict(
        json_schema_extra={
            "humanReadableName": "Gemini",
            "description": "Configuration for Gemini",
            "link": "https://deepmind.google/technologies/gemini",
        }
    )
```

also let me know if the names of the class and parameters are ok

**Comment by kodaline** [comment]
@davidegavio  I just tried on develop branch your code.

I updated the `pyproject.toml` by adding `langchain_google_genai`, setting newer version for `google-generativeai` to `0.3.1` since `langchain_google_genai` requires at least that version.

I then rebuilt the cat, up the compose and I see the settings for `Gemini` available.

Are you getting that error once you set an api_key? I don't have one to test :D and apparently I cannot get one

**Comment by kodaline** [comment]
@davidegavio I am trying the code locally, and I don't get it, what were you exactly doing while you got the error?

**Comment by davidegavio** [comment]
@kodaline the error came up while I was trying to chat with the cat using google's model
in order to get a google api key I had to connect using a vpn because [the api key platform ](https://ai.google.dev/) is still not available in Europe, like the gemini model

**Comment by kodaline** [comment]
@davidegavio the problem should come from `core/cat/looking_glass/agent_manager.py` line 92, in particular the `llm`, if you look it says `llm: Runnable[LanguageModelInput, str] | Runnable[LanguageModelInput, BaseMessage]`

**Comment by kodaline** [comment]
@davidegavio found the issue, update the `pyproject.toml` version of `langchain` to `0.0.350`

**Comment by pieroit** [comment]
Gemini adapter now available in `develop`, in a few days in `main`
