### ISSUE TITLE
Rename the `cat/mad_hatter/decorators/plugin.py` module

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/core#633]
In the documentation, we have a script automatically generating docs from the docstrings, [according to the module name](https://github.com/cheshire-cat-ai/docs/pull/104) (not very elegant probably). 

In the `core` code there are two files named `plugin.py`, but only one should be documented. Hence, renaming [this one](https://github.com/cheshire-cat-ai/core/blob/main/core/cat/mad_hatter/decorators/plugin.py) could solve the issue.

**Comment by Tudor44** [comment]
> In the documentation, we have a script automatically generating docs from the docstrings, [according to the module name](https://github.com/cheshire-cat-ai/docs/pull/104) (not very elegant probably).
> 
> In the `core` code there are two files named `plugin.py`, but only one should be documented. Hence, renaming [this one](https://github.com/cheshire-cat-ai/core/blob/main/core/cat/mad_hatter/decorators/plugin.py) could solve the issue.

I fixed it renaming the .py with name "plugin_decorator" changing the module definition as well. Could be fine?

**Comment by pieroit** [comment]
> > In the documentation, we have a script automatically generating docs from the docstrings, [according to the module name](https://github.com/cheshire-cat-ai/docs/pull/104) (not very elegant probably).
> > In the `core` code there are two files named `plugin.py`, but only one should be documented. Hence, renaming [this one](https://github.com/cheshire-cat-ai/core/blob/main/core/cat/mad_hatter/decorators/plugin.py) could solve the issue.
> 
> I fixed it renaming the .py with name "plugin_decorator" changing the module definition as well. Could be fine?

Thanks, make sure it is possible to import it like this:
`from cat.mad_hatter.decorators import plugin`
(same as [other decorators](https://github.com/cheshire-cat-ai/core/blob/e6eabe6706ae810f66cf4ca0024e3d65824e0490/core/cat/mad_hatter/decorators/__init__.py))
Make a PR ;)
P.S. remember to branch from `develop`
