### ISSUE TITLE
Decrease rabbit hole log level 

### ISSUE THREAD

**Issue by AlessandroSpallina** [cheshire-cat-ai/core#635]
**Describe**
[Here](https://github.com/cheshire-cat-ai/core/blob/main/core/cat/rabbit_hole.py#L350-L352) we see that whenever a chunk is added into the rabbit hole then the content is logged with INFO level. Here a screen of the result, for every chunk:

![Schermata del 2023-12-26 18-44-12](https://github.com/cheshire-cat-ai/core/assets/10786872/a535fd48-39e5-4655-9452-65205df25e82)

Since while writing a plugin I would need to log something with INFO level, but having other components of the Cat logging so much can quickly decrease the readability, I propose to modify [the lines](https://github.com/cheshire-cat-ai/core/blob/main/core/cat/rabbit_hole.py#L350-L352) to:
* Decrease the log level from INFO to DEBUG
* Ensure only one line is logged for each chunk in order to avoid chaos in logs
    * log.info() is interpreting any occurrence of '\n', a replace('\n', '\\\n') of the string to be logged (or repr() or something else) would avoid multiple lines when printing the chunk content

**Comment by pieroit** [comment]
Sounds ok
What about having just a few INFO for percentages (the same as websocket messages)

**Comment by AlessandroSpallina** [comment]
> What about having just a few INFO for percentages (the same as websocket messages)
Yup, that's better

**Comment by pieroit** [comment]
Should be fixed
