### ISSUE TITLE
Rename `cat/mad_hatter/core_plugin/settings.py`

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/core#645]
**Is your feature request related to a problem? Please describe.**
Similar to #633, there are two files named `settings.py` in the cat's folder. 
The first one is related to the `/settings` endpoints and the second one is about the plugin's settings.
Because of the not very sophisticated scanning mechanism in the documentation, both end up documented, but only the second one should.

**Describe the solution you'd like**
Since in the second one stores `@plugin` hooks, what about renaming it something else? E.g. `events.py` or `plugin_events.py` or something else

**Comment by NJacksonDev** [comment]
Hi, happy to work on this. Could you please assign this to me?

**Comment by nicola-corbellini** [comment]
@NJacksonDev done! Let's go with `plugin_events.py` name. Thank you!
