### ISSUE TITLE
[BUG] Inability to Specify HTTPS Protocol in QdrantClient Connection Setup

### ISSUE THREAD

**Issue by lucapirrone** [cheshire-cat-ai/core#654]
**Describe the bug**
The current implementation of the QdrantClient connection setup within our codebase does not support the specification of the HTTPS protocol. This omission leads to connectivity issues when attempting to connect to a Qdrant instance configured to accept only HTTPS connections.

**To Reproduce**
1. Set up an Qdrant server environment that accepts only HTTPS connections.
2. Launch an instance of the cat with qdrant server host and port in environment variables
3. Observe the failure in establishing a connection with the error message: "The plain HTTP request was sent to HTTPS port."

**Expected behavior**
The cat's connection to the qdrant server should be successful.

**Suggested Solution**
`
self.vector_db = QdrantClient(
    host=qdrant_host,
    port=qdrant_port,
    https=qdrant_https, # is a boolean indicating the protocol (from env variables)
    api_key=qdrant_api_key # it may also be useful to set the qdrant api key (from env variables)
)
`

**Comment by pieroit** [comment]
@lucapirrone thanks for spotting this.
Assigning to you

Question: does it work if you include the protocol in `QDRANT_HOST`?
Also, the protocol could be extracted easily from `QDRANT_HOST`
(I disagree on having an env variable just for secure vs unsecure http of an external service)

Ok for `QDRANT_API_KEY`

**Comment by lucapirrone** [comment]
Hi @pieroit, 

if I try to connect with these parameters in env variables:
`QDRANT_HOST=https://qdrant-dev.learnn.com`
`QDRANT_PORT=6333`
I get the following connection error:
`QDrant does not respond to https://qdrant-dev.learnn.com:6333`

To fix that i had to edit the core connect_to_vector_memory function:
<img width="906" alt="image" src="https://github.com/cheshire-cat-ai/core/assets/31966729/58c36e28-2ea8-410d-bc56-38c10776eca4">

But if you prefer to extract the protocol from `QDRANT_HOST` env variables it could be done like this
core/cat/memory/vector_memory.py
<img width="932" alt="image" src="https://github.com/cheshire-cat-ai/core/assets/31966729/1dd4a9f2-0a57-4943-aaeb-e4ecbfcd2d63">
core/cat/utils.py
<img width="579" alt="image" src="https://github.com/cheshire-cat-ai/core/assets/31966729/748789a1-8bf8-4539-b4bc-2998c36a34fe">

What do you think about that?
Thank you!
