### ISSUE TITLE
Levenshtein distance in `cat.utils`

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#655]
In a lot of cases (e.g. conversational forms) we need to check how similar strings are between each other (e.g. `Margherita` vs `margherita` cs `marghertia`), in a fast way - without calling into play the LLM each time.

I suggest we insert into `cat.utils` a small function that can be used like this:

```python
from cat.utils import levenshtein_distance

if levenshtein_distance(some_string, "Margherita") > 0.8:
    # do something
```

Score should be between 0 and 1.
There are many packages around, maybe we can start with the standard library (if there is  such a method somewhere) or libraries already included in the cat ([nltk edit distance](https://www.nltk.org/api/nltk.metrics.edit_distance.html?highlight=edit_distance) for example)

**Comment by horw** [comment]
Hi, @pieroit, I can implement it.
