### ISSUE TITLE
[Feature] Enable Direct Prompt Modification for Improved Compatibility and Flexibility

### ISSUE THREAD

**Issue by jameseh** [cheshire-cat-ai/core#665]
**Is your feature request related to a problem? Please describe:**
The current prompt construction process lacks flexibility for customization, requiring code forking or workarounds to modify prompt sections. This poses challenges for users integrating custom LLMs.

**Describe the solution you'd like:**
I'd like to request features that enable users to change the prompt text, prefix, and suffix directly, without code forking. This would significantly improve compatibility with custom LLMs, including the ability to align prompt identifiers (e.g., for human/AI) with tokenizer tokens for consistency.

**Describe alternatives you've considered:**
Alternatives like forking the repository or external prompt reconstruction have drawbacks such as hindering updates or increasing complexity.

**Additional context:**
For reference, the prompt construction logic can be found in the following file:
[core/cat/looking_glass/prompts.py](https://github.com/cheshire-cat-ai/core/blob/main/core/cat/looking_glass/prompts.py)

While external prompt reconstruction is possible using string manipulation, I believe built-in features for direct prompt customization would offer a more sustainable and user-friendly approach.

**Comment by pieroit** [comment]
From the plugin page in the admin you can easily install a plugin called C.A.T. (cat advanced tools) and in the plugin settings you can easily change the prefix.

Also you can change any part of the prompt dynamically without forking the code, just by creating a plugin and using a couple of hooks `agent_prompt_prefix` and `agent_prompt_suffix`
See here 
https://cheshire-cat-ai.github.io/docs/technical/plugins/hooks/#__tabbed_1_2

Follow the quickstart to learn how to write a plugin

**Comment by jameseh** [comment]
Thank you for the quick help and pointing me in the right direction!

**Comment by pieroit** [comment]
@jameseh you're welcome.
Have fun ^._.^
