### ISSUE TITLE
GET /plugins endpoint should indicate updatable plugins

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#682]
In the returning JSON, already installed plugins may contain a key `upgrade` with the new version, like `0.1.12`

**Comment by bositalia** [comment]
Nice

**Comment by bositalia** [comment]
check idea.

.....
        registry_plugins_index.pop(manifest["plugin_url"], None)

        #for p in installed_plugins.get('url'):
            # Fetch GitHub plugin.json file
            # github_response = requests.get(registry_plugins_index.get("url")

            # Check if GitHub request was successful
            # github_response.raise_for_status()

            # Parse GitHub response
            # github_data = github_response.json()
            # github_version = github_data.get('version')

            # Compare versions
            # if installed_plugins.get('version') != github_version:
                # pronto per aggiornare
            #else:
            #   return False
...

**Comment by bositalia** [comment]
# GET plugins
@router.get("/")
async def get_available_plugins(
    request: Request,
    query: str = None,
    #author: str = None, to be activated in case of more granular search
    #tag: str = None, to be activated in case of more granular search
) -> Dict:
    """List available plugins"""

    # retrieve plugins from official repo
    registry_plugins = await registry_search_plugins(query)
    # index registry plugins by url
    registry_plugins_index = {}
    for p in registry_plugins:
        plugin_url = p["url"]
        registry_plugins_index[plugin_url] = p

    # get active plugins
    ccat = request.app.state.ccat
    active_plugins = ccat.mad_hatter.load_active_plugins_from_db()

    # list installed plugins' manifest
    installed_plugins = []
    
    da_aggiornare = False
    
    for p in ccat.mad_hatter.plugins.values():
        
        # get manifest
        manifest = deepcopy(p.manifest) # we make a copy to avoid modifying the plugin obj
        manifest["active"] = p.id in active_plugins # pass along if plugin is active or not
        manifest["hooks"] = [{ "name": hook.name, "priority": hook.priority } for hook in p.hooks]
        manifest["tools"] = [{ "name": tool.name } for tool in p.tools]
        
        # filter by query
        plugin_text = [str(field) for field in manifest.values()]
        plugin_text = " ".join(plugin_text).lower()
        if (query is None) or (query.lower() in plugin_text):
            installed_plugins.append(manifest)

# Inizio mofifiche            
            for r in registry_plugins:
                if r["plugin_url"] == p.manifest["plugin_url"]:
                    if r["version"] == p.manifest["version"]:
                        da_aggiornare = False
                    else:
                        da_aggiornare = True
                        # invocare metodo per visualizzare
                        # informazione "PLUGIN UPGRADABLE"
# fine modifiche

        # do not show already installed plugins among registry plugins
        registry_plugins_index.pop(manifest["plugin_url"], None)

    return {
        "filters": {
            "query": query,
            #"author": author, to be activated in case of more granular search
            #"tag": tag, to be activated in case of more granular search
        },
        "installed": installed_plugins,
        "registry": list(registry_plugins_index.values())
    }
