### ISSUE TITLE
[Feature] Run this without Docker

### ISSUE THREAD

**Issue by cleesmith** [cheshire-cat-ai/core#694]
**Describe the solution you'd like**
To run this locally without Docker, as I just want to use it locally and not aiming for production.
Do you have any instructions for doing that?
Thanks,
Chris

**Comment by pieroit** [comment]
We avoided getting the Cat out of docker because too many support requests would be related to personal setups.

A linux system is quite necessary, at least in a container

Use docker also locally, man :)
