### ISSUE TITLE
[Feature] Visit URL and "talk" about it

### ISSUE THREAD

**Issue by zinwelzl** [cheshire-cat-ai/core#695]
Hi.

Can you add feature for example
visit www.example.com and count works
or
visit www.SOMEURL.com and summarize text

I didn't find plugin for that.

**Comment by zinwelzl** [comment]
I can upload web page, but how can I use it later in chat?

**Comment by nicola-corbellini** [comment]
you should ask questions related to those pages and the Cat will look in its memory and answer accordingly.
Maybe I'm misunderstanding what you need
