### ISSUE TITLE
[Feature] Support for llamaindex IngestionPipeline and other feature to enhance RAG apps

### ISSUE THREAD

**Issue by raphael2692** [cheshire-cat-ai/core#708]
I would like to use llamaindex ingestion pipeline feature to build more precise RAG apps with the cat :)

In particular, I would like to be able to use these fetures:

- Question extractor: create a set of question (using an llm) to augment a chunk of text (this really helps with cosine search in many usecase)
- Keyword extractor 
- Hybrid search: eg, using elasticsearch as a vector store one could be able to use both vetor silmilarity and keyword search tooptimize chunk extraction. 

Thanks :)

**Comment by valentimarco** [comment]
Hi, welcome to the community!
The cat uses langchain and they call chains what llamaindex calls pipeline, you can find the list [here](https://python.langchain.com/docs/modules/chains) (idk if they are good as pipelines, sorry 😿)

I agree that llamaindex >>>>> langchain (i hate my self langchain <3) but we are watching the evolution of the library to see if is worth to switch to them!

**Comment by raphael2692** [comment]
Good to know! So I guess that if I want to customize how documents are ingested I need to customize the relative chain. Is there a plug-in approach for this kind of customization or editing the source is the only way? Thanks :)

**Comment by valentimarco** [comment]
can you explain better? you can already customize the ingestion with the [hooks](https://cheshire-cat-ai.github.io/docs/technical/plugins/hooks/#__tabbed_1_3)

**Comment by raphael2692** [comment]
Sure!

I wanted to ingest documents in a similar fashion as described [`here`](https://docs.llamaindex.ai/en/stable/examples/metadata_extraction/MetadataExtractionSEC.html ) , in particular implementing something like the [QuesitonAnsweredExtractor ](https://github.com/run-llama/llama_index/blob/main/llama_index/extractors/metadata_extractors.py) class. 

It seems I can do the same using those hooks so thank you so much for the assistance! :)
