### ISSUE TITLE
[BUG] Something went wrong while connecting to the server (https)

### ISSUE THREAD

**Issue by FrancescoMontedori** [cheshire-cat-ai/core#709]
**Describe the bug**
i'm trying to deploy the cat on a nginx server that use https protocol. The UI starts normally but when i connect to the /admin endpoint i get the message "Something went wrong while connecting to the server". I use a reverse proxy from port 80 to port 3001

**To Reproduce**

**Expected behavior**
Cat working normally

**Additional context**
This is my docker.compose.yml:

version: '3.7'

services:

  cheshire-cat-core:
    build:
      context: ./core
    container_name: cheshire_cat_core
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
      - CORE_HOST=${CORE_HOST:-localhost}
      - CORE_PORT=${CORE_PORT:-3001}
      - CORE_USE_SECURE_PROTOCOLS=${CORE_USE_SECURE_PROTOCOLS:-true}
      - API_KEY=${API_KEY:-}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-true}
      - SAVE_MEMORY_SNAPSHOTS=${SAVE_MEMORY_SNAPSHOTS:-false}
    ports:
      - ${CORE_PORT:-3001}:80
    volumes:
      - ./core:/app
    command:
      - python
      - "-m"
      - "cat.main"
    restart: unless-stopped

This is the log from the terminal:
cheshire_cat_core  | INFO:      - "GET / HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /settings.js HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /main.css HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /widget.css HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /widget.js HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /favicon.ico HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET / HTTP/1.0" 304 Not Modified
cheshire_cat_core  | INFO:      - "GET /admin/favicon.ico HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /admin/favicon.ico HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /admin/favicon.ico HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /admin/favicon.ico HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /admin/favicon.ico HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /admin/favicon.ico HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /admin/favicon.ico HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /admin/favicon.ico HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /admin/ HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /ws/user HTTP/1.0" 404 Not Found
cheshire_cat_core  | INFO:      - "GET /embedder/settings/ HTTP/1.0" 307 Temporary Redirect
cheshire_cat_core  | INFO:      - "GET /llm/settings/ HTTP/1.0" 307 Temporary Redirect
cheshire_cat_core  | INFO:      - "GET /plugins/settings/ HTTP/1.0" 307 Temporary Redirect
cheshire_cat_core  | INFO:      - "GET /memory/collections/ HTTP/1.0" 307 Temporary Redirect
cheshire_cat_core  | INFO:      - "GET /plugins/ HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /memory/conversation_history/ HTTP/1.0" 307 Temporary Redirect
cheshire_cat_core  | INFO:      - "GET / HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /admin/favicon.ico HTTP/1.0" 200 OK
cheshire_cat_core  | INFO:      - "GET /ws/user HTTP/1.0" 404 Not Found
cheshire_cat_core  | INFO:      - "GET /ws/user HTTP/1.0" 404 Not Found

**Comment by valentimarco** [comment]
Hi, Welcome to the community!

Did you check our blog post about [Cat + Ngnix](https://cheshirecat.ai/how-to-use-cheshire-cat-behind-nginx/)?
I know that is a simple one, but maybe there is an error in the config, Would like to share it?

If you need more support, check out our discord and again welcome to the community!

**Comment by FrancescoMontedori** [comment]
Hi, thanks for quick the support, the problem was with header not properly configured in the nginx configuration file. Now the cat is working as expected.
