### ISSUE TITLE
[Feature] Add API Key on Openai Compatible API 

### ISSUE THREAD

**Issue by Rizaldy** [cheshire-cat-ai/core#713]
**Problem Statement**
As we know that currently many platform already using OpenAI compatible API, namely Together, Anyscale, Fireworks, OpenRouter and many more. But when I try to use it the OpenAI compatible API on the settings there are no API Key input fields. Even OpenRouter is also using API, where on the screenshot below it can be use with OpenRouter

<img width="429" alt="image" src="https://github.com/cheshire-cat-ai/core/assets/7367220/b0414561-a0ae-4437-8cde-cffe56c8995c">

The reason we are using this hosted platform because my poor old local machine dont have the GPU when it comes to Mixtral, heck even 34B is already failing :)

**Solution**
It would be good if the setting also put API KEY input so we can use it with many cloud provider

And lastly I'm sorry if its already covered somewhere, Im just installed it recently and fell in love with the cat :D would appreciate to shed some light on this matter

Thanks

**Comment by pieroit** [comment]
Agree
Can you do a PR?
P.S. from `develop` to `develop`

**Comment by Rizaldy** [comment]
I end up using plugin copying from fireworks.ai :D and used openai API from langchain for the generate functions. But since still on testing haven't upload it to github and registered yet. Now it works for open router and will test with other openai API compatible from other provider
