### ISSUE TITLE
[Feature] Support Recursive URL in the RabbitHole

### ISSUE THREAD

**Issue by valentimarco** [cheshire-cat-ai/core#717]
**Is your feature request related to a problem? Please describe.**
If you want to ingest large pages with sub-pages, the only way right now is to have a python script with a list of all the url and sub-url.

**Describe the solution you'd like**
 `POST /rabbithole/web` should accept a list of url and an option object to be able to implement the [recursive url extractor](https://python.langchain.com/docs/integrations/document_loaders/recursive_url), below an example of body:
```json
{
  "url": "string" | ["string"],
  "chunk_size": 512,
  "chunk_overlap": 128,
  "recursive": "bool",
  "option":{
      "exclude_dirs" : "string",
      "max_depth": "int",
      "timeout": "int",
      "prevent_outside": "bool"
   }
}
```
The param `recursive` must be false by default, so the user can choose.

**Additional context**
Although the extractor accept an lambda function to insert custom extractor, i think we can use the one that langchain use as example (BeautifulSoup). If the user need a different one, can override the parser using rabbithole_instantiates_parsers

**Comment by mattiamazzari** [comment]
In upload.py:
`@router.post("/web")
async def upload_url(
    request: Request,
    background_tasks: BackgroundTasks,
    url: Union[str, List[str]] = Body(
        ...,
        description="URL or list of URLs of the website(s) to which you want to save the content"
    ),
    chunk_size: int = Body(
        default=512,
        description="Maximum length of each chunk after the document is split (in characters)",
    ),
    chunk_overlap: int = Body(default=128, description="Chunk overlap (in characters)"),
    recursive: bool = Body(
        default=False,
        description="If True, the URL will be recursively followed and all the linked pages will be ingested"
    ),
    options: Dict = Body(
        default={},
        description="Options for the ingestion process"
    ),
    stray = Depends(session),
):

    try:
        # Send a HEAD request to the specified URL
        response = requests.head(
            url,
            headers={"User-Agent": "Magic Browser"},
            allow_redirects=True
        )
        status_code = response.status_code

        if status_code == 200:

            # upload file to long term memory, in the background
            background_tasks.add_task(
                stray.rabbit_hole.ingest_file, stray, url, chunk_size, chunk_overlap, recursive, options
            )
            return {"url": url, "info": "URL is being ingested asynchronously"}
`

In core/cat/rabbit_hole,py:
`from langchain_community.document_loaders.recursive_url_loader import RecursiveUrlLoader
from bs4 import BeautifulSoup as Soup

   def ingest_file(
            self,
            stray,
            file: Union[str, UploadFile],
            chunk_size: int = 512,
            chunk_overlap: int = 128,
            recursive: bool = False,
            options: dict = None
    ):

        if recursive:
            self.__reload_file_handlers()
            loader = RecursiveUrlLoader(
                url=file,
                max_depth=options.get("max_depth", 2),
                exclude_dirs=options.get("exclude_dirs", ""),
                timeout=options.get("timeout", 10),
                prevent_outside=options.get("prevent_outside", True),
                extractor=lambda x: Soup(x, self.__file_handlers).text
            )
            docs = loader.load()

        else:
            # split file into a list of docs
            docs = self.file_to_docs(
                stray=stray,
                file=file,
                chunk_size=chunk_size,
                chunk_overlap=chunk_overlap
            )
`

Something like this?

**Comment by valentimarco** [comment]
After some time, is better to move all of this as plugin!
I will share some info on discord so we can see it together if you need help,
Thanks anyway for the contribution and welcome to the community
