### ISSUE TITLE
Manage plugin upgrade

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#718]
Admin receives from `GET /plugins` a flag expressing if a plugin is upgradeable or not.
As soon as the button `Upgrade` is added, admin will be able to request the upgrade.
The endpoint called will be the same as the installation one: `POST /plugins/upload/registry`

Core should be able to delete the old one and install the new.
Later on we can figure strategies to preserve plugin data and settings.

**Comment by bositalia** [comment]
> can I be assigned to this?

I can participate in this modification, I would like to understand the functioning of the admin frontend if possible with kodaline.

**Comment by pieroit** [comment]
> > can I be assigned to this?
> 
> I can participate in this modification, I would like to understand the functioning of the admin frontend if possible with kodaline.

If @kodaline is available we can have a tour of core and admin on this feat (also @zAlweNy26 is involved )

**Comment by kodaline** [comment]
> > > can I be assigned to this?
> > 
> > 
> > I can participate in this modification, I would like to understand the functioning of the admin frontend if possible with kodaline.
> 
> If @kodaline is available we can have a tour of core and admin on this feat (also @zAlweNy26 is involved )

sure let's schedule a call, from monday-friday I am available only after 6pm :/

**Comment by pieroit** [comment]
> Hi! Just opened a PR to fix the current behaviour and preserve plugin settings after plugin upgrade. But, as far as I can understand from this issue, settings.json may not be the only thing you want to preserve after upgrade. Were you thinking about a more generalized approach?

One way could be a convention, like "everything you save in a `data` folder is going to be kept during plugin update.

At the moment preserving `plugin.json` is already a plus. We should check in the future what happens when plugin settings schema changes.

Thanks @lucagobbi

**Comment by pieroit** [comment]
@valentimarco really appreciated you are updating the kanban ;)
