### ISSUE TITLE
The cat is ignoring me

### ISSUE THREAD

**Issue by VincenzoCiv** [cheshire-cat-ai/core#724]
Hello, I'm trying to use the cat to process a txt file with the transcription of a lecture to have it generate some notes. However, after 2 hours from the request, the cat hasn't provided me with any results yet. I'm not sure if I made a mistake in the prompts or in the settings. If you could help me understand, I would be grateful.

<img width="848" alt="Capture d'écran 2024-02-17 165656" src="https://github.com/cheshire-cat-ai/core/assets/101653274/3b36ce8c-13cb-47a5-b614-12518581e86e">

**Comment by pazoff** [comment]
> Hello, I'm trying to use the cat to process a txt file with the transcription of a lecture to have it generate some notes. However, after 2 hours from the request, the cat hasn't provided me with any results yet. I'm not sure if I made a mistake in the prompts or in the settings. If you could help me understand, I would be grateful.
> <img alt="Capture d&apos;écran 2024-02-17 165656" width="848" src="https://private-user-images.githubusercontent.com/101653274/305655409-3b36ce8c-13cb-47a5-b614-12518581e86e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxODkxMzAsIm5iZiI6MTcwODE4ODgzMCwicGF0aCI6Ii8xMDE2NTMyNzQvMzA1NjU1NDA5LTNiMzZjZThjLTEzY2ItNDdhNS1iNjE0LTEyNTE4NTgxZTg2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QxNjUzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDRhM2I5YTAzMTkxNTI0YTY5YWQ1ZmY5MGVmNmY5ODNlNjg2OGExZWVlNWY5MjA3ODBkZmIzYmQwZjk4MzhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eLx81HUyh8rkhH5nIVoljgHscl8iJlYm2730E6rWUVU">

Try here:
https://cheshire-cat-ai.github.io/docs/quickstart/play-with-the-cat/

**Comment by VincenzoCiv** [comment]
Thank you,
I've read the guide on the file upload part, but I'm not getting any completion notification even after a while since I uploaded the file. Are there any maximum text sizes or preferred formats (like .pdf rather than .txt)?

**Comment by pazoff** [comment]
> Thank you, I've read the guide on the file upload part, but I'm not getting any completion notification even after a while since I uploaded the file. Are there any maximum text sizes or preferred formats (like .pdf rather than .txt)?

Have you read the blog?
https://cheshirecat.ai/how-the-cat-works/

**Comment by VincenzoCiv** [comment]
Thank you, even though I'm a beginner in this field, I've read the documentation and tried to understand the functioning as much as possible. 

From what I've gathered, files are processed within the 'rabbit Hole' component, and indeed, after sending the .txt file, I receive a message that the file has been placed into the rabbit hole. However, even if I make requests regarding that file, particularly to summarize its contents, I don't receive any response. I'm not sure if it's due to excessive file size or some mistake on my part.

**Comment by pazoff** [comment]
> I'm not getting any completion notification even after a while since I uploaded the file.
![image](https://github.com/cheshire-cat-ai/core/assets/28357700/f2419b06-b954-4010-a27c-5cdbab5f03d8)
What is configured on your side for the embedder?

**Comment by pazoff** [comment]
> Thank you, even though I'm a beginner in this field, I've read the documentation and tried to understand the functioning as much as possible.
> 
> From what I've gathered, files are processed within the 'rabbit Hole' component, and indeed, after sending the .txt file, I receive a message that the file has been placed into the rabbit hole. However, even if I make requests regarding that file, particularly to summarize its contents, I don't receive any response. I'm not sure if it's due to excessive file size or some mistake on my part.

You should make requests regarding the content of the file, not the file itself.

**Comment by pazoff** [comment]
> Thank you, even though I'm a beginner in this field, I've read the documentation and tried to understand the functioning as much as possible.
> 
> From what I've gathered, files are processed within the 'rabbit Hole' component, and indeed, after sending the .txt file, I receive a message that the file has been placed into the rabbit hole. However, even if I make requests regarding that file, particularly to summarize its contents, I don't receive any response. I'm not sure if it's due to excessive file size or some mistake on my part.

Also you could try this plugin:
![image](https://github.com/cheshire-cat-ai/core/assets/28357700/fefa1975-0307-4414-81a8-cbaf520914d4)
https://github.com/Furrmidable-Crew/ccat_summarization

**Comment by VincenzoCiv** [comment]
Okay, I'll try and let you know. Thanks again for the help.

**Comment by pazoff** [comment]
> > I'm not getting any completion notification even after a while since I uploaded the file.
> > ![image](https://private-user-images.githubusercontent.com/28357700/305700974-f2419b06-b954-4010-a27c-5cdbab5f03d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDk1MTMsIm5iZiI6MTcwODI0OTIxMywicGF0aCI6Ii8yODM1NzcwMC8zMDU3MDA5NzQtZjI0MTliMDYtYjk1NC00MDEwLWEyN2MtNWNkYmFiNWYwM2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA5NDAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0OGVhMDU1YThjNDY1MDgyYTJhMzRkNjU2NGI5ZDFkMTU2YzU0MTQ4ZjdkOWQzZDAxOWFjNGNjOTI3NDM1ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.laJeBc3HpzuhMY5mJ4yG4KLorkYyN5QsV9uh3OwwqpI)
> 
> What is configured on your side for the embedder?

p.s If you change the embedder you must upload the files again!

**Comment by valentimarco** [comment]
@VincenzoCiv the issue is resolved?

**Comment by VincenzoCiv** [comment]
Yes, I more or less solved it, thanks. 
Sorry, I've had a fever these days and I forgot to close the issue. 
Thanks again.
