### ISSUE TITLE
[Feature] add a new hook before that the document is parsed

### ISSUE THREAD

**Issue by giovannialbero1992** [cheshire-cat-ai/core#731]
**Is your feature request related to a problem? Please describe.**
Especially when an HTML is ingest, it is useful check the html in order to remove dirty data / pieces of the HTML that are not useful to embed (headers, footers, etc.).

**Describe the solution you'd like**
I'd add before the `parse` a new hook to manipulate the content 

**Describe alternatives you've considered**
This kind of activity can be done before to call rabbit_hole but if we wanna ingest urls we loose the metadatas about the source.

**Additional context**
Having this hook in place anyone can implement a plugin or a chain of them to manipulate the content before to ingest it.

**Comment by nicola-corbellini** [comment]
Correct me if I'm misunderstanding, but I'm not sure adding it before the [parsing](https://github.com/cheshire-cat-ai/core/blob/b8a611549511e012ef4b66e34759df08b77f6305/core/cat/rabbit_hole.py#L284) happens is the right place.
At that point, you have file bytes and you should parse them to remove the noise.

Hence, you could post process the text [before the rabbit hole splits the text](https://cheshire-cat-ai.github.io/docs/technical/plugins/hooks/#__tabbed_1_3) or inside the `parse` itself. 
In the last case, you could override the BeautifulSoup [parser](https://github.com/cheshire-cat-ai/core/blob/b8a611549511e012ef4b66e34759df08b77f6305/core/cat/rabbit_hole.py#L35) and perform parsing and post processing all at once

**Comment by giovannialbero1992** [comment]
Hi @nicola-corbellini, at that point the HTML for example is already stripped, so I can't do parsing to remove noise based on some tag or attribute.

**Comment by nicola-corbellini** [comment]
Ah my bad, didn't think about that. Than a custom parser is the best solution, I think.
We are relying on Langchain, which, in turn, uses BeautifulSoup (ref [here](https://api.python.langchain.com/en/latest/document_loaders/langchain_community.document_loaders.parsers.html.bs4.BS4HTMLParser.html)).
 Maybe tuning some params could be enough, but implementing a new one guarantees full control.

**Comment by giovannialbero1992** [comment]
If you agree I could do a proposal on this ;-)

**Comment by nicola-corbellini** [comment]
Mmm ok...in my mind the solution was to just make a plugin with your own parser and replace the default one with the *rabbit_hole_instantiates_parsers* [hook](https://cheshire-cat-ai.github.io/docs/technical/plugins/hooks/#__tabbed_1_3), but if you have a proposal I'm happy to hear it
