### ISSUE TITLE
[Feature]Docstring in the tools more clear

### ISSUE THREAD

**Issue by paoloach** [cheshire-cat-ai/core#743]
**Is your feature request related to a problem? Please describe.**
I had some trouble understanding what the docstring in the tools actually meant. Especially, it was not clear the input part
To the end of the day, there are two distinct concepts: a trigger and  something like a filter (it extract some informations)

**Describe the solution you'd like**
I can suggest to have a more structured description in order to make evident this two concept like

```
trigger: The sentence that trigger the tools
data:  What information it will extract, previously name tool_input,
```

and then parse the description, combine it and use as before.

I suggest to use _trigger_ and _data_ because are the words more used in this case.

Anyway, I recommend  against term _tool_input_ or _cat_ but instead use more used term like
_data_ and _context_
They are the used words in these case.

To avoid breacking change, I can suggest two way:

- A new decorator, like structured_tool
- Check if the docstring is a structured one or blob and differentiate the two case in the code

In the future, you can use this structured docstring also for adding new field like _example_

**Describe alternatives you've considered**
No realy alternative if not leave as is

.

**Comment by pieroit** [comment]
Hi @paoloach we added examples to tool, now you can have the triggers separated from the description:

```python
@tool(examples=["what time is it", "get the time"])
def get_the_time(tool_input, cat):
    """Useful to get the current time when asked. Input is always None."""

    return str(datetime.now())
```

If you need something more elaborate than a tool, che out the new `CatForm` (still experimental)

**Comment by paoloach** [comment]
Hi @pieroit, 
What I wanted to give was just advice to improve understanding of how to use the tools, also based on my experience.
As it is now it seems cryptic to me and the cause seems to be due to the fact that the meaning of the docstring is not clear.
I understand it now so I have no problems, but maybe another person abandons the use of cheshire because they don't understand how to use it.
I have often seen libraries chosen in favor of others because it was clear in its functioning while the other was not.
Or maybe I'm particularly stupid and I'm the only one with the problem.
