### ISSUE TITLE
Refactoring Azure integration

### ISSUE THREAD

**Issue by cristianorevil** [cheshire-cat-ai/core#747]
As discussed here: https://github.com/cheshire-cat-ai/core/issues/745 with @zioproto and @olafgeibig the Azure integration need some rework. Actually in the list there are these points:

- Upgrade packages to AzureChatOpenAI (from langchain_openai import AzureChatOpenAI)
- Add options max_tokens to bypass the slow problem with gpt-4 on azure

Please add other suggestions

**Comment by pieroit** [comment]
Also avoid automatic selection for the Azure embedder #746
