### ISSUE TITLE
Error executing Chesire Cat with local llm and qdrant

### ISSUE THREAD

**Issue by marcob71** [cheshire-cat-ai/core#749]
Hy,
I'm trying to execute the cat with local LLM as described here https://cheshirecat.ai/local-models-with-ollama/
After executing che docker compose up command the downloads complete and when starting the processes the following errors appear in sequence, always in the cheshire_cat_core module

PS C:\Dati\chesire> docker compose up
[+] Running 3/3
 ✔ Container cheshire_cat_vector_memory  Created                                                                                                                      0.0s
 ✔ Container ollama_cat                  Created                                                                                                                      0.0s
 ✔ Container cheshire_cat_core           Recreated                                                                                                                    0.8s
Attaching to cheshire_cat_core, cheshire_cat_vector_memory, ollama_cat
cheshire_cat_vector_memory  |            _                 _
cheshire_cat_vector_memory  |   __ _  __| |_ __ __ _ _ __ | |_
cheshire_cat_vector_memory  |  / _` |/ _` | '__/ _` | '_ \| __|
cheshire_cat_vector_memory  | | (_| | (_| | | | (_| | | | | |_
cheshire_cat_vector_memory  |  \__, |\__,_|_|  \__,_|_| |_|\__|
cheshire_cat_vector_memory  |     |_|
cheshire_cat_vector_memory  |
cheshire_cat_vector_memory  | Version: 1.8.1, build: 3fbe1cae
cheshire_cat_vector_memory  | Access web UI at http://localhost:6333/dashboard
cheshire_cat_vector_memory  |
cheshire_cat_vector_memory  | 2024-03-13T17:15:47.799043Z  INFO storage::content_manager::consensus::persistent: Loading raft state from ./storage/raft_state.json
cheshire_cat_vector_memory  | 2024-03-13T17:15:47.881401Z  INFO storage::content_manager::toc: Loading collection: episodic
ollama_cat                  | time=2024-03-13T17:15:48.013Z level=INFO source=images.go:800 msg="total blobs: 5"
ollama_cat                  | time=2024-03-13T17:15:48.091Z level=INFO source=images.go:807 msg="total unused blobs removed: 0"
ollama_cat                  | time=2024-03-13T17:15:48.157Z level=INFO source=routes.go:1019 msg="Listening on [::]:11434 (version 0.1.28)"
ollama_cat                  | time=2024-03-13T17:15:48.158Z level=INFO source=payload_common.go:107 msg="Extracting dynamic libraries..."
cheshire_cat_vector_memory  | 2024-03-13T17:15:50.201592Z  INFO collection::shards::local_shard: Recovering collection episodic: 0/0 (0%)
cheshire_cat_vector_memory  | 2024-03-13T17:15:50.201636Z  INFO collection::shards::local_shard: Recovered collection episodic: 0/0 (100%)
cheshire_cat_vector_memory  | 2024-03-13T17:15:50.212395Z  INFO qdrant: Distributed mode disabled
cheshire_cat_vector_memory  | 2024-03-13T17:15:50.212457Z  INFO qdrant: Telemetry reporting enabled, id: e04da357-2441-4a21-a2b2-053e78b14767
cheshire_cat_vector_memory  | 2024-03-13T17:15:50.215225Z  INFO qdrant::actix: TLS disabled for REST API
cheshire_cat_vector_memory  | 2024-03-13T17:15:50.215300Z  INFO qdrant::actix: Qdrant HTTP listening on 6333
cheshire_cat_vector_memory  | 2024-03-13T17:15:50.215308Z  INFO actix_server::builder: Starting 7 workers
cheshire_cat_vector_memory  | 2024-03-13T17:15:50.215321Z  INFO actix_server::server: Actix runtime found; starting in Actix runtime
cheshire_cat_vector_memory  | 2024-03-13T17:15:50.218505Z  INFO qdrant::tonic: Qdrant gRPC listening on 6334
cheshire_cat_vector_memory  | 2024-03-13T17:15:50.218554Z  INFO qdrant::tonic: TLS disabled for gRPC API
ollama_cat                  | time=2024-03-13T17:15:54.145Z level=INFO source=payload_common.go:150 msg="Dynamic LLM libraries [cpu cpu_avx cpu_avx2 cuda_v11 rocm_v60000]"
ollama_cat                  | time=2024-03-13T17:15:54.145Z level=INFO source=gpu.go:77 msg="Detecting GPU type"
ollama_cat                  | time=2024-03-13T17:15:54.145Z level=INFO source=gpu.go:191 msg="Searching for GPU management library libnvidia-ml.so"
ollama_cat                  | time=2024-03-13T17:15:54.145Z level=INFO source=gpu.go:237 msg="Discovered GPU libraries: [/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 /usr/lib/wsl/drivers/nv_dispsig.inf_amd64_195ec6a4e5afbb7e/libnvidia-ml.so.1]"
ollama_cat                  | time=2024-03-13T17:15:54.162Z level=INFO source=gpu.go:82 msg="Nvidia GPU detected"
ollama_cat                  | time=2024-03-13T17:15:54.162Z level=INFO source=cpu_common.go:15 msg="CPU has AVX"
ollama_cat                  | time=2024-03-13T17:15:54.169Z level=INFO source=gpu.go:119 msg="CUDA Compute Capability detected: 8.6"
cheshire_cat_core           | --- Logging error in Loguru Handler #1 ---
cheshire_cat_core           | Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=851842), 'exception': None, 'extra': {}, 'file': (name='embedding.py', path='/usr/local/lib/python3.10/site-packages/fastembed/embedding.py'), 'function': '<module>', 'level': (name='WARNING', no=30, icon='⚠️'), 'line': 7, 'message': 'DefaultEmbedding, FlagEmbedding, JinaEmbedding are deprecated.Use from fastembed import TextEmbedding instead.', 'module': 'embedding', 'name': 'fastembed.embedding', 'process': (id=7, name='MainProcess'), 'thread': (id=140514201339712, name='MainThread'), 'time': datetime(2024, 3, 13, 17, 15, 54, 353340, tzinfo=datetime.timezone(datetime.timedelta(0), 'UTC'))}
cheshire_cat_core           | Traceback (most recent call last):
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/loguru/_handler.py", line 184, in emit
cheshire_cat_core           |     formatted = precomputed_format.format_map(formatter_record)
cheshire_cat_core           | KeyError: 'original_name'
cheshire_cat_core           | --- End of logging error ---
cheshire_cat_core           | --- Logging error in Loguru Handler #1 ---
cheshire_cat_core           | Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=821539), 'exception': None, 'extra': {}, 'file': (name='embedding.py', path='/usr/local/lib/python3.10/site-packages/fastembed/embedding.py'), 'function': '<module>', 'level': (name='WARNING', no=30, icon='⚠️'), 'line': 7, 'message': 'DefaultEmbedding, FlagEmbedding, JinaEmbedding are deprecated.Use from fastembed import TextEmbedding instead.', 'module': 'embedding', 'name': 'fastembed.embedding', 'process': (id=24, name='SpawnProcess-1'), 'thread': (id=140358760773440, name='MainThread'), 'time': datetime(2024, 3, 13, 17, 16, 0, 484806, tzinfo=datetime.timezone(datetime.timedelta(0), 'UTC'))}
cheshire_cat_core           | Traceback (most recent call last):
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/loguru/_handler.py", line 184, in emit
cheshire_cat_core           |     formatted = precomputed_format.format_map(formatter_record)
cheshire_cat_core           | KeyError: 'original_name'
cheshire_cat_core           | --- End of logging error ---
cheshire_cat_vector_memory  | 2024-03-13T17:16:03.545052Z  INFO actix_web::middleware::logger: 172.19.0.4 "GET /collections HTTP/1.1" 200 90 "-" "python-httpx/0.27.0" 0.000242
cheshire_cat_vector_memory  | 2024-03-13T17:16:03.561873Z  INFO actix_web::middleware::logger: 172.19.0.4 "GET /collections/episodic HTTP/1.1" 200 455 "-" "python-httpx/0.27.0" 0.000255
cheshire_cat_core           | ERROR:    Traceback (most recent call last):
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 94, in send
cheshire_cat_core           |     return parse_as_type(response.json(), type_)
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 213, in parse_as_type
cheshire_cat_core           |     return model_type(obj=obj).obj
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
cheshire_cat_core           |     __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
cheshire_cat_core           | pydantic_core._pydantic_core.ValidationError: 1 validation error for ParsingModel[InlineResponse2005] (for parse_as_type)
cheshire_cat_core           | obj.result.config.optimizer_config.max_optimization_threads
cheshire_cat_core           |   Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
cheshire_cat_core           |     For further information visit https://errors.pydantic.dev/2.4/v/int_type
cheshire_cat_core           |
cheshire_cat_core           | During handling of the above exception, another exception occurred:
cheshire_cat_core           |
cheshire_cat_core           | Traceback (most recent call last):
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
cheshire_cat_core           |     async with self.lifespan_context(app) as maybe_state:
cheshire_cat_core           |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
cheshire_cat_core           |     return await anext(self.gen)
cheshire_cat_core           |   File "/app/cat/main.py", line 29, in lifespan
cheshire_cat_core           |     app.state.ccat = CheshireCat()
cheshire_cat_core           |   File "/app/cat/utils.py", line 150, in getinstance
cheshire_cat_core           |     cls.instances[class_] = class_(*args, **kwargs)
cheshire_cat_core           |   File "/app/cat/looking_glass/cheshire_cat.py", line 67, in __init__
cheshire_cat_core           |     self.load_memory()
cheshire_cat_core           |   File "/app/cat/looking_glass/cheshire_cat.py", line 257, in load_memory
cheshire_cat_core           |     self.memory = LongTermMemory(vector_memory_config=vector_memory_config)
cheshire_cat_core           |   File "/app/cat/memory/long_term_memory.py", line 17, in __init__
cheshire_cat_core           |     self.vectors = VectorMemory(**vector_memory_config)
cheshire_cat_core           |   File "/app/cat/memory/vector_memory.py", line 37, in __init__
cheshire_cat_core           |     collection = VectorMemoryCollection(
cheshire_cat_core           |   File "/app/cat/memory/vector_memory_collection.py", line 51, in __init__
cheshire_cat_core           |     self.check_embedding_size()
cheshire_cat_core           |   File "/app/cat/memory/vector_memory_collection.py", line 62, in check_embedding_size
cheshire_cat_core           |     self.client.get_collection(self.collection_name).config.params.vectors.size
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 1530, in get_collection
cheshire_cat_core           |     return self._client.get_collection(collection_name=collection_name, **kwargs)
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 1963, in get_collection
cheshire_cat_core           |     result: Optional[types.CollectionInfo] = self.http.collections_api.get_collection(
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py", line 1262, in get_collection
cheshire_cat_core           |     return self._build_for_get_collection(
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py", line 377, in _build_for_get_collection
cheshire_cat_core           |     return self.api_client.request(
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 74, in request
cheshire_cat_core           |     return self.send(request, type_)
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 96, in send
cheshire_cat_core           |     raise ResponseHandlingException(e)
cheshire_cat_core           | qdrant_client.http.exceptions.ResponseHandlingException: 1 validation error for ParsingModel[InlineResponse2005] (for parse_as_type)
cheshire_cat_core           | obj.result.config.optimizer_config.max_optimization_threads
cheshire_cat_core           |   Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
cheshire_cat_core           |     For further information visit https://errors.pydantic.dev/2.4/v/int_type
cheshire_cat_core           |
cheshire_cat_core           | ERROR:    Application startup failed. Exiting.

**Expected behavior**
I'm using this compose.yml file

version: '3.7'

services:
  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    depends_on:
      - cheshire-cat-vector-memory
      - ollama
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
      - CORE_HOST=${CORE_HOST:-localhost}
      - CORE_PORT=${CORE_PORT:-1865}
      - QDRANT_HOST=${QDRANT_HOST:-cheshire_cat_vector_memory}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
      - CORE_USE_SECURE_PROTOCOLS=${CORE_USE_SECURE_PROTOCOLS:-}
      - API_KEY=${API_KEY:-}
      - LOG_LEVEL=${LOG_LEVEL:-WARNING}
      - DEBUG=${DEBUG:-true}
      - SAVE_MEMORY_SNAPSHOTS=${SAVE_MEMORY_SNAPSHOTS:-false}
    ports:
      - ${CORE_PORT:-1865}:80
    volumes:
      - ./cat/static:/app/cat/static
      - ./cat/public:/app/cat/public
      - ./cat/plugins:/app/cat/plugins
      - ./cat/metadata.json:/app/metadata.json
    restart: unless-stopped

  cheshire-cat-vector-memory:
    image: qdrant/qdrant:latest
    container_name: cheshire_cat_vector_memory
    expose:
      - 6333
    volumes:
      - ./cat/long_term_memory/vector:/qdrant/storage
    restart: unless-stopped

  ollama:
    container_name: ollama_cat
    image: ollama/ollama:latest
    volumes:
      - ./ollama:/root/.ollama
    expose:
      - 11434
    environment:
      - gpus=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

I have a pc with Windows 10, i7 3770 CPU, 32GB RAM and a Geforce RTX 3060 12GB
I use the last version of Docker Desktop 4.28.0 (139021).
Any idea to help me resolve this issue?
Thank you, Marco

**Comment by valentimarco** [comment]
Hello and welcome, unfortunately this is a windows problem that you can resolve by using only the combo cheshire-cat-core + ollama (so without the qdrant service of the docker-compose).

**Comment by valentimarco** [comment]
@marcob71 the issue is resolved?

**Comment by marcob71** [comment]
Hy,
I solved the problem by adding qdrant directly in the administration panel. Of course, I commented out the reference lines in compose.yml.
