### ISSUE TITLE
[BUG] upload memories 

### ISSUE THREAD

**Issue by AndreaPesce2002** [cheshire-cat-ai/core#754]
**I tried to load the Recalled_Memories.json file with the memory inside (with over 3K memories) and it gives me this error:

cheshire_cat_core | ERROR: Exception in ASGI application
cheshire_cat_core | Traceback (most recent call last):
cheshire_cat_core | File "/usr/local/lib/python3.10/site-
packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
cheshire_cat_core | result = await app( # type: ignore[func-returns-value]
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
cheshire_cat_core | return await self.app(scope, receive
, send)
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
cheshire_cat_core | await super().__call__(scope, receive, send)
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
cheshire_cat_core | await self.middleware_stack(scope, receive, send)
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
cheshire_cat_core | raise exc
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py",
line 162, in __call__
cheshire_cat_core | await self.app(scope, receive, _send)
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
cheshire_cat_core | await self.simple_response(scope, receive, send, request_headers=headers)
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
cheshire_cat_core | await self.app(scope, receive, send)
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
cheshire_cat_core | raise exc
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
cheshire_cat_core | await self.app(scope, receive, sender)
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20,
in __call__
cheshire_cat_core | raise e
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
cheshire_cat_core | await self.app(scope, receive, send)
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718,
in __call__
cheshire_cat_core | await route.handle(scope, receive, send)
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
cheshire_cat_core | await self.app(scope, receive, send)
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/starlette/routing.
py", line 69, in app
cheshire_cat_core | await response(scope, receive, send)
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 174, in __call__
cheshire_cat_core | await self.background()
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/starlette/background.py",
line 43, in __call__
cheshire_cat_core | await task()
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/starlette/background.py", line 28, in __call__
cheshire_cat_core | await run_in_threadpool(self.func, *self.args, **self.kwargs)
cheshire_cat_core | File "/usr/local/lib/python3.10/site-
packages/starlette/concurrency.py", line 41, in run_in_threadpool
cheshire_cat_core | return await anyio.to_thread.run_sync(func, *args)
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
cheshire_cat_core | return await get_asynclib().run_sync_in_worker_thread(
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
cheshire_cat_core | return await future
cheshire_cat_core | File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, running
cheshire_cat_core | result = context.
run(func, *args)
cheshire_cat_core | File "/app/cat/rabbit_hole.py", line 74, in ingest_memory
cheshire_cat_core | raise Exception(message)
cheshire_cat_core | Exception: Embedder mismatch: file embedder OpenAIEmbeddings is different from DumbEmbedder

**Must play**
1) I went to memory
2) I downloaded the memory
3) I uninstalled and reinstalled the cat
4) I tried to insert the new memory by going to Home and then upload memories

**Comment by zAlweNy26** [comment]
As the error says, you can't upload memories if you have a different embedder. Change your embedder to match the same written in the memory json file.
