### ISSUE TITLE
[Feature]Could the chat API support the OpenAI Chat Completion API standard to be compatible with a chat web app?

### ISSUE THREAD

**Issue by thinker007** [cheshire-cat-ai/core#756]
for example 
let lobechat  LibreChat support cheshire-cat-ai backend

**Comment by pieroit** [comment]
Cat at the moment needs websocket, we have notifications and custom info along the ws message.

If you want you can create a small server to do the integration, I don't really see the point (the Cat is an agent not a LLM)

**Comment by thinker007** [comment]
> Cat at the moment needs websocket, we have notifications and custom info along the ws message.
> 
> If you want you can create a small server to do the integration, I don't really see the point (the Cat is an agent not a LLM)

If not chat completion api ,maybe we can have openai assistant API ?
The principle is the same, our API is best to provide a standardized interface that is easy to integrate with third-party UIs.

**Comment by valentimarco** [comment]
Create a wrapper around the OpenAI chat Completion API and use it to connect the UIs to the cat!

**Comment by thinker007** [comment]
> Create a wrapper around the OpenAI chat Completion API and use it to connect the UIs to the cat!

Thanks for your help 
you mean Create a wrapper between cat  ws service and  OpenAI chat Completion API?

any suggestion?
