### ISSUE TITLE
[Feature] Add GET method to retrieve working memory information for the why

### ISSUE THREAD

**Issue by valentimarco** [cheshire-cat-ai/core#758]
**Is your feature request related to a problem? Please describe.**
Would be great to visualize the working memory when opening the why tab on the admin

**Describe the solution you'd like**
Create a GET Method to access the working memory. Should be pretty easy...

**Comment by zAlweNy26** [comment]
What kind of informations would you like to see?

**Comment by valentimarco** [comment]
last 5 messages of the chat history for sure. I was thinking also for the documents but can be hard

**Comment by pieroit** [comment]
> Last 5 messages of the chat history and any arbitrary key defined for sure. I was thinking also for the documents but can be hard.

Working memory contents can be python objects or any other thing, so they must be serialized or omitted (recursively)
There is also an endpoint specific to get convo history, can we do a PUT to impose it?
Also @Pingdred was interested in this feat

Let me know
