### ISSUE TITLE
Rework of /public endpoint

### ISSUE THREAD

**Issue by valentimarco** [cheshire-cat-ai/core#766]
The /public endpoint was originally thought as a public static page where the user could expose the cat! 
Most of the users prefer to create a frontend wrapper with custom auth etc...
What should we do with this endpoint?
1. Delete it from the core.
2. Create a page with minimal functionality and auth.

**Comment by AlessandroSpallina** [comment]
me and some colleagues will write a frontend with auth through keycloak, we’ll publish a plugin for that too.

this should arrive in a couple of months

**Comment by pieroit** [comment]
Awesome!
We'll take two pigeons with one fava to study how to introduce users

**Comment by pieroit** [comment]
@valentimarco thanks for opening the issue, public is either to take away or pit something really minimal into it
