### ISSUE TITLE
[BUG] something went wrong while connecting to the server. Error 304

### ISSUE THREAD

**Issue by AncientMystic** [cheshire-cat-ai/core#779]
Trying to use Cheshire with Ollama and so far i have the settings configured the api is up, other webuis can reach ollama and work fine, but Cheshire seems to have a problem. 

I installed via docker with the command provided for a quick setup to try it out as ive had my eye on it for awhile but couldn’t get it working with ollama last time. 

I believe this is a header file misconfiguration? But im not sure where to start on fixing it/what exactly needs to be changed, etc

the admin page works fine and i can even install plugins but the chat side just doesn’t work. 

this is the error in the terminal when loading /public
"PUT /llm/settings/LLMOllamaConfig HTTP/1.1" 200 OK
"GET / HTTP/1.1" 304 Not Modified
"GET /widget.js HTTP/1.1" 200 OK
"GET /llm/settings HTTP/1.1" 200 OK

**Comment by zAlweNy26** [comment]
Those are not errors. The chat endpoint uses an old widget which is not been updated since a lot. I'd suggest you to use the admin panel if possible, and if you want to "open it to public", create your own UI.

**Comment by AncientMystic** [comment]
Understood, thank you for the quick reply, I appreciate it.
