### ISSUE TITLE
Custom and pluggable Agent

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#79]
The Cat features a langchain [ConversationalAgent](https://python.langchain.com/en/latest/reference/modules/agents.html#langchain.agents.ConversationalAgent) which covers most easy use cases:
- chat with a memory context
- chat with tools use

At the moment this solution presents several limits:
- confusion between memory context and tools
- difficulty executing tools in sequence
- prompt is too long (small models have no chance)

Here is a roadmap to improve the Agent:
1 - have a more agile and resilient default agent (choosing among [these])(https://python.langchain.com/docs/modules/agents.html)
2 - have a pluggable agent - inserting a few hooks into [CustomAgent](https://python.langchain.com/docs/modules/agents/how_to/custom_agent), making it multiprompt and working on dictionaries
3 - having a hook to totally override the cat Agent in case a dev is brave enough (same as we do with LLM and embedders)

@nicola-corbellini @sirius-0 let's tackle this

**Comment by pieroit** [comment]
@sirius-0 please comment so I can assign the issue

**Comment by sirius-0** [comment]
> @sirius-0 please comment so I can assign the issue

Here

**Comment by valentimarco** [comment]
@pieroit With the new agent structure, should we discuss a solution?

**Comment by pieroit** [comment]
> @pieroit With the new agent structure, should we discuss a solution?

Agree, time to brainstorm this

**Comment by pieroit** [comment]
We have now these hooks:
- `agent_fast_reply` to jump over the Agent
- `fast_reply` to jump over the whole StrayCat
