### ISSUE TITLE
Endpoint and button for "factory reset"

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#797]
Many people messes up with the embedders and LLMs, breaking the installation. Typical error comes from Qdrant:
`TypeError: '>=' not supported between instances of 'ValueError' and 'int'`

Let's have an endpoint to reset default llm and embedder (plugins should not be an issue).
Reset button could also be placed in admin settings for people not able to check out the terminal.

**Comment by alfredotoselli** [comment]
Hello! A couple question about the endpoint:
- "reset default llm and embedder" means to set the dumb `Default Language Model` as LLM and the `Default Embedder` as Embedder? In this case the reset buttons in the admin panel (now seem inactive) will hit this new endpoint?
- from the user's perspective the concept of "factory reset" in practice means: reset llm; reset embedder; wipe all collections; right ?

![llm](https://github.com/user-attachments/assets/63c195fb-4800-4aa6-9569-fdc91ccb9e80)
![embedder](https://github.com/user-attachments/assets/31278b8c-dedc-4bfc-bd5b-4ba992d56c62)

**Comment by pieroit** [comment]
> * "reset default llm and embedder" means to set the dumb `Default Language Model` as LLM and the `Default Embedder` as Embedder? In this case the reset buttons in the admin panel (now seem inactive) will hit this new endpoint?

Those reset button should only revert to the latest db config, if I remember correctly (@zAlweNy26 can you confirm?)

> * from the user's perspective the concept of "factory reset" in practice means: reset llm -> reset embedder -> wipe all collections right ?

It has become more complicated because there are now users and various settings.
The easiest way to reset is to delete `cat/data/metadata.json` and wipe all the memories.
Not sure how this endpoint should behave at the moment :/

**Comment by zAlweNy26** [comment]
I don't remember that, I think it should reset to what it is when you first install the cat.
