### ISSUE TITLE
Chunk management in the rabbithole.py - Bug or Help??

### ISSUE THREAD

**Issue by ElioErrico** [cheshire-cat-ai/core#798]
If i want to edit `chunk_size `and `chunk_overlap `should i edit the `chunk_size: int = 256` and `chunk_overlap: int = 64` default parameter inside the following methods in the `rabbithole.py`?

 ```
   def file_to_docs(
            self,
            stray,
            file: Union[str, UploadFile],
            chunk_size: int = 256,
            chunk_overlap: int = 64,
    ) -> List[Document]:
```

```
   def string_to_docs(
            self,
            stray,
            file_bytes: str,
            source: str = None,
            content_type: str = "text/plain",
            chunk_size: int = 256,
            chunk_overlap: int = 64
        ) -> List[Document]:
```

```
    def ingest_file(
            self,
            stray,
            file: Union[str, UploadFile],
            chunk_size: int = 256,
            chunk_overlap: int = 64,
    ):
```

Then if I well understood this parameters will be used inside the function `__split_text ` in the `rabbithole.py`:

```
    def __split_text(self, stray, text, chunk_size, chunk_overlap):

        text = stray.mad_hatter.execute_hook(
            "before_rabbithole_splits_text", text, cat=stray
        )

        text_splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap,
            separators=["\\n\\n", "\n\n", ".\\n", ".\n", "\\n", "\n", " ", ""],
            encoding_name = "cl100k_base",
            keep_separator=True,
            strip_whitespace = True
        )
```

**In my case the chunk management is working only if I edit the method __split_text directly editing the text_splitter,** and it seems to me that nothing changes if I edit the previous cited methods.
for example:

```
        text_splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
            chunk_size=1024,
            chunk_overlap=256,
            separators=["\\n\\n", "\n\n", ".\\n", ".\n", "\\n", "\n", " ", ""],
            encoding_name = "cl100k_base",
            keep_separator=True,
            strip_whitespace = True
        )
```

Am I reporting a bug or I misunderstood something?

**Comment by pieroit** [comment]
Thanks @ElioErrico, we want to add an hook for that reason, described here:
https://github.com/cheshire-cat-ai/core/issues/691#issuecomment-2067700896

Are you interested in doing a PR?

Closing this issue as duplicate

**Comment by ElioErrico** [comment]
What is a PR? :)

**Comment by pieroit** [comment]
> What is a PR? :)

A Pull Request!
Nevermind, your suggestion is welcomed and will be adapted with a new hook ;)
Thanks

**Comment by zAlweNy26** [comment]
> Thanks @ElioErrico, we want to add an hook for that reason, described here: [#691 (comment)](https://github.com/cheshire-cat-ai/core/issues/691#issuecomment-2067700896)
> 
> Are you interested in doing a PR?
> 
> Closing this issue as duplicate

@pieroit you don't even consider my PR? :(

**Comment by pieroit** [comment]
> > Thanks @ElioErrico, we want to add an hook for that reason, described here: [#691 (comment)](https://github.com/cheshire-cat-ai/core/issues/691#issuecomment-2067700896)
> > Are you interested in doing a PR?
> > Closing this issue as duplicate
> 
> @pieroit you don't even consider my PR? :(

Sorry lost track of latest PRs to organize events :D 
Back on track soon :*
