### ISSUE TITLE
BUG @hook After_Rabbit_Hole_splitted_text 

### ISSUE THREAD

**Issue by ElioErrico** [cheshire-cat-ai/core#810]
Hello everybody,

I was trying to use the `@hook After_Rabbit_Hole_splitted_text`.
Applying the same code of the documentation in #https://cheshire-cat-ai.github.io/docs/technical/plugins/hooks/#__tabbed_1_3 
I face an error and no document is uploaded. 

Did I make some mistakes or something changed with the update??? 

```
@hook  # default priority = 1
def after_rabbithole_splitted_text(chunks, cat):
    # post process the chunks
    edited_chunks = []
    for chunk in chunks:
        new_chunk = cat.llm(f"Replace any dirty word with 'Meow': {chunk}")
        edited_chunks.append(new_chunk)
    return edited_chunks 

```
![image](https://github.com/cheshire-cat-ai/core/assets/143315119/9b1d3ab4-fd8c-4b34-8ebc-2a6e9d226ac1)
![image](https://github.com/cheshire-cat-ai/core/assets/143315119/e95cb226-bb3b-4381-8749-98e0b5dcb608)

**Comment by nicola-corbellini** [comment]
I realize the example in the doc is wrong, thank you for pointing that out. Would you mind opening an issue in the doc repo please?
the `chunk` is a LangChain `Document`, hence you can get the text with `chunk.page_content`.

The error originates because in the new list, you should append `Document` data as well. The correct code should be:
```python
@hook  # default priority = 1
def after_rabbithole_splitted_text(chunks, cat):
    # post process the chunks
    edited_chunks = []
    for chunk in chunks:
        new_text = cat.llm(f"Replace any dirty word with 'Meow': {chunk.page_content}")
        new_chunk = Document(page_content=new_text, metadata={})
        edited_chunks.append(new_chunk)
    return edited_chunks 
```
please, let me know if this solves the issue

**Comment by pieroit** [comment]
> I realize the example in the doc is wrong, thank you for pointing that out. Would you mind opening an issue in the doc repo please? the `chunk` is a LangChain `Document`, hence you can get the text with `chunk.page_content`.
> 
> The error originates because in the new list, you should append `Document` data as well. The correct code should be:
> 
> ```python
> from langchain.docstore.document import Document
> @hook  # default priority = 1
> def after_rabbithole_splitted_text(chunks, cat):
>     # post process the chunks
>     edited_chunks = []
>     for chunk in chunks:
>         new_text = cat.llm(f"Replace any dirty word with 'Meow': {chunk.page_content}")
>         new_chunk = Document(page_content=new_text, metadata={})
>         edited_chunks.append(new_chunk)
>     return edited_chunks 
> ```
> 
> please, let me know if this solves the issue

Can't he just replace the content?

```python
from langchain.docstore.document import Document
@hook  # default priority = 1
def after_rabbithole_splitted_text(chunks, cat):
    # post process the chunks
    for chunk in chunks:
        new_text = cat.llm(f"Replace any dirty word with 'Meow': {chunk.page_content}")
        chunk.page_content = new_text
    return chunks 
```

**Comment by pieroit** [comment]
Can confirm this works:

```python
@hook
def after_rabbithole_splitted_text(chunks, cat):
    for chunk in chunks:
        chunk.page_content = "anythaaang"
    return chunks 
```

**Comment by pieroit** [comment]
Opening the issue in docs

**Comment by ElioErrico** [comment]
Working thanks!
