### ISSUE TITLE
[Feature] Bash install scripts set for the cat

### ISSUE THREAD

**Issue by saniales** [cheshire-cat-ai/core#820]
**Is your feature request related to a problem? Please describe.**
The current simple method to install the cat is via Docker, however it is not the simple possible approach.

**Describe the solution you'd like**
An install script should be able to install all the dependencies + the cat (and can also be used in the Dockerfile to simplify and unify the installation methods). The script (or scripts) should be for major UNIX distros (I think of Ubuntu-like, CentOS-like and raw install via curl only) + Windows (powershell + downloads) ideally.

**Describe alternatives you've considered**
It is also possible to provide a tutorial for each of the cases above. But the long term solutions should be a good install scripts set.

What do you think?

***I can take care of the developments and maintenance of those scripts***

**Comment by valentimarco** [comment]
There was a request similar: #694
This way the cat is more like a Product/Runner (Ollama for example is one of those, bash script and docker image) rather than a framework to build stuff

**Comment by saniales** [comment]
I am going to close this as I am starting personally a CLI based on the core. This allows to better manage installations and plugins without breaking core functionalities (i.e. creating conflicts)

You can find the new repo [here](https://github.com/saniales/paws-cli). When we reach a good enough stability, I will ask for transfer in the main cat org. @pieroit @valentimarco

**Comment by pieroit** [comment]
@saniales it's going to be a bloodbath, but it may reduce friction.
Thanks and let's see where it goes
