### ISSUE TITLE
[BUG] Hooks with same priority collide

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#830]
(to be verified)

When there are two hooks with same name and same priority, one gets overridden.

Probably a bug in MadHatter's hooks [cache](https://github.com/cheshire-cat-ai/core/blob/c79272bcd3ae60a4037b5e2e42f12d4106f1d033/core/cat/mad_hatter/mad_hatter.py#L153)

**Comment by jacopopalumbo01** [comment]
I've tried with two dummies plugin like follows:

PLUGIN 1:
```python
from cat.mad_hatter.decorators import hook
from cat.log import log

@hook(priority=3)
def before_cat_sends_message(final_output, cat):
    # You can perform operations with the cat (modify working memory, access LLM, etc.)
    log.debug("TEST ONE")
    log.debug(final_output.content)
    
    final_output.content += "TESTONE"
    # You can return a new value that will be used instead of Cat calculated value
    return final_output
```

PLUGIN 2:
```python
from cat.mad_hatter.decorators import hook
from cat.log import log

@hook(priority=3)
def before_cat_sends_message(final_output, cat):
    # You can perform operations with the cat (modify working memory, access LLM, etc.)
    log.debug("TEST TWO")
    log.debug(final_output.content)
    
    final_output.content += "TESTTWO"
    # You can return a new value that will be used instead of Cat calculated value
    return final_output
```

and it seems to work correctly. The agent responds always with a message of the type: "GENERATED_TEXTTESTONETESTTWO".
Maybe the bug that they exposed during the last dev meeting is only related to some hooks.

Did they provide more infos about it?

**Comment by pieroit** [comment]
@jacopopalumbo01 same for me, could not manage to replicate the bug

@valentimarco do you have some hint?
