### ISSUE TITLE
[Feature]: Add groq llms

### ISSUE THREAD

**Issue by Flecart** [cheshire-cat-ai/core#834]
**Is your feature request related to a problem? Please describe.**
Adding groq to possible LLMs

**Describe the solution you'd like**
In the LLMs page, allow a select with groq 
![image](https://github.com/cheshire-cat-ai/core/assets/63465494/ddeae4e1-ef33-4b05-b691-541e3cf8894a)

**Describe alternatives you've considered**
Possible that customLLM tab is sufficient, but don't know how to make it work.

**Additional context**
I can implement this, but I would like some mentoring about where to modify!

**Comment by valentimarco** [comment]
You can install this plugin in the registry https://github.com/pazoff/GroqAI-Integration as GroqAI Integration!
