### ISSUE TITLE
[BUG] Interface does not return error on not pdf files

### ISSUE THREAD

**Issue by Flecart** [cheshire-cat-ai/core#838]
**Describe the bug**
Cat continues to think, and does not return error.
![image](https://github.com/cheshire-cat-ai/core/assets/63465494/904526a3-ea64-4115-9ca5-13c44e0ae6cd)

**To Reproduce**
Steps to reproduce the behavior (as exampple`):
1. Go to home, set up LLM and embeddings
2. Try to add this pdf (broken pdf)
[00-key-exchange.pdf](https://github.com/cheshire-cat-ai/core/files/15448790/00-key-exchange.pdf)

3. See interface has no errors, while terminal correctly returns error

```txt
  File "/usr/local/lib/python3.10/site-packages/pdfminer/pdfdocument.py", line 752, in __init__
    raise PDFSyntaxError("No /Root object! - Is this really a PDF?")
pdfminer.pdfparser.PDFSyntaxError: No /Root object! - Is this really a PDF?
```

**Expected behavior**
UI returns correct error

**Comment by bositalia** [comment]
This is not a mistake. #838
Explanation.
A wrong file was scanned, it is not a pdf but another format, as an attachment, the actual pdf file is “digested” correctly.
I attach Wrong File, renamed to txt to display content.
I attach original pdf file “retrieved” from university.
I attach screen of content and various tests.
Delete BUG pls. 

[00-key-exchange-bad-pdf.txt](https://github.com/cheshire-cat-ai/core/files/15453719/00-key-exchange-bad-pdf.txt)
[00-key-exchange-giusto.pdf](https://github.com/cheshire-cat-ai/core/files/15453728/00-key-exchange-giusto.pdf)
<img width="1432" alt="Immagine 2024-05-27 111124" src="https://github.com/cheshire-cat-ai/core/assets/59937047/960b46d1-0a1c-4cab-8136-2883ac6d015c">
![Firefox_Screenshot_2024-05-27T09-06-06 903Z](https://github.com/cheshire-cat-ai/core/assets/59937047/43b7c6ca-ea81-40fd-8273-5dc388b40bf0)
![Firefox_Screenshot_2024-05-27T09-06-06 903Z](https://github.com/cheshire-cat-ai/core/assets/59937047/43b7c6ca-ea81-40fd-8273-5dc388b40bf0)
![Firefox_Screenshot_2024-05-27T09-04-26 788Z](https://github.com/cheshire-cat-ai/core/assets/59937047/3aa2af41-2be4-416a-b43e-da27e32a9df1)
<img width="938" alt="Immagine 2024-05-27 112758" src="https://github.com/cheshire-cat-ai/core/assets/59937047/e9d6cea4-67fa-4078-b543-4618f6adcb45">
<img width="464" alt="Immagine 2024-05-27 112853" src="https://github.com/cheshire-cat-ai/core/assets/59937047/56fcb6f8-9ea9-4ad2-9369-88401051576c">
