### ISSUE TITLE
[ERROR] AsyncCompletions.create() got an unexpected keyword argument 'api_type'"

### ISSUE THREAD

**Issue by edoardosaputelli** [cheshire-cat-ai/core#842]
**Describe the bug**

The error occurs when I try to use an OpenAI over Azure LLM (Setting “Azure OpenAI Completion Models”). 
When I try to interact with the model, the error “AsyncCompletions.create() got an unexpected keyword argument ‘api_type’” comes out. I tried both the Dumb and Default Embedder.

**To Reproduce**
Steps to reproduce the behavior (as example`):
1. Go to Settings
2. Click on LLM > Configure
3. Insert the API parameters (I'm sure they work via Python API)
4. Click "Save"
5. Click on Embedder > Configure
6. Select Dumb (or Default) Embedder
7. Click "Save"
8. Go to Home
9. Insert any prompt
10. The error comes out

**Expected behavior**

I expect the model to respond to my prompt.

**Additional context**

**Comment by pieroit** [comment]
Are you on the latest version?

**Comment by edoardosaputelli** [comment]
Yes, I tried starting from the latest (1.6.1) to 1.5.3, then I opened the issue

**Comment by ketchalegend** [comment]
@pieroit i still have this issue. Did you find a way to solve it or am i doing something wrong?

**Comment by pieroit** [comment]
Yel should be an issue with Azure + langchain, try next release and configure your cat from scratch ;)
Let me know
