### ISSUE TITLE
[BUG] Entering admin with https generates many errors

### ISSUE THREAD

**Issue by rafleze** [cheshire-cat-ai/core#850]
I deployed a cat instance on a server where kubernetes orchestrates the service. I added the CORE_USE_SECURE_PROTOCOLS=true  parameter but when I navigate the admin I have many errors.

![Screenshot 2024-06-10 alle 10 53 10](https://github.com/cheshire-cat-ai/core/assets/1647787/86f866ab-77dc-4ea6-ad93-973ee7cda7f3)

the problem is that in the endpoint called without the slash. when it redirects it breaks because it does it in http

![image](https://github.com/cheshire-cat-ai/core/assets/1647787/922d4dc7-31f9-4e81-b532-4d16f8089981)

Maybe the solution is explained at this link: https://stackoverflow.com/questions/63511413/fastapi-redirection-for-trailing-slash-returns-non-ssl-link

At the moment I solved the problem adding this parameter: FORWARDED_ALLOW_IPS

But I suppose that the redirect could be avoided adding "/" at the end of the url.

**Comment by zAlweNy26** [comment]
Can you try this PR #837 and tell us if the problem persists?

**Comment by pieroit** [comment]
Should be already fixed in `develop`
