### ISSUE TITLE
[Feature]Add API Client for C++/C/Arduino

### ISSUE THREAD

**Issue by LorenzoSiena** [cheshire-cat-ai/core#851]
### **The issue:**
It seems that the project already has clients to contact the cat, but they are all high-level and interpreted as python, javascript etc. The much more energy-constrained platforms of microcontrollers such as arduino, esp32 do not have the privilege of running on expensive and heavy platforms such as python vm, so it would be optimal for the entire edge computing landscape to be able to use a lightweight client dedicated to microboards.

### **The solution**
Adding an official client for arduino/esp32 board

### **The alternative**
Implement a websocket and api handler to handle only the main /admin page through Arduino libraries.
A very crude solution and limited to chatting using the raw JSON format 

### **The JSON format**

**My Request**
![Schermata del 2024-06-10 16-18-33](https://github.com/cheshire-cat-ai/core/assets/74120782/17f1fb56-7ded-44b7-b93c-85747ad0c2c8)

**My Response**
![Schermata del 2024-06-10 16-18-22](https://github.com/cheshire-cat-ai/core/assets/74120782/953dae77-8496-4956-8151-764cc2d171b9)

Thank you for your time and best wishes for the project.

**Comment by zAlweNy26** [comment]
@LorenzoSiena I suggest you to check out these resources:
- [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator?tab=readme-ov-file#overview)
- [OpenAPI Schema](https://github.com/cheshire-cat-ai/api-client-ts/blob/main/catapi.json)

**Comment by LorenzoSiena** [comment]
> * OpenAPI Schema



> @LorenzoSiena I suggest you to check out these resources:
> 
>     * [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator?tab=readme-ov-file#overview)
> 
>     * [OpenAPI Schema](https://github.com/cheshire-cat-ai/api-client-ts/blob/main/catapi.json)

About the schema, i found multiple version of it , from my istance on docker on serverip:port/openapi.json and maybe another on this repo ,so, are all the same or i should use the "last version available"?

**Comment by zAlweNy26** [comment]
@LorenzoSiena I suggested you that specific version of the schema because is the only version that has types specified in it. Actually the CCat is not fully typed so I manually created that schema to match the correct DTOs.

**Comment by LorenzoSiena** [comment]
I will start working on it in the next few days and in case i will update you with the repository.

**Comment by pieroit** [comment]
Stale
