### ISSUE TITLE
[BUG] Any http request does not trigger the before_cat_reads_message/before_cat_sends_message hook or function

### ISSUE THREAD

**Issue by LorenzoSiena** [cheshire-cat-ai/core#858]
**My experience**
"OMG WHY before_cat_sends_message() WON'T TRIGGER FROM MY POST REQUEST?!
Ah... ok i see why" 

**THE BUG:**
I'm developing a plugin to receive audio messages and translate them locally on the machine, and I noticed while debugging that if I upload the file from the admin interface (or using the post for the endpoint http://localhost:1865/rabbithole/) in order to send the audio file, the cat will not trigger the before_cat_reads_message() function 
(from the documentation "Intervene before the Cat sends its answer via WebSocket") 
but this means that the function responsible for modifying a message just before receiving it works ONLY for websocket connections.
If I do it from a dedicated ws client in python the problem does not exist.
Same goes for before_cat_sends_message().
It is not normal for the transmission medium below in the stack to produce different results in the stack above.
Furthermore it could generate undefined results when calling the api for other purposes.

**To Reproduce**

-Set Debug verbose mode (LOG_LEVEL=${LOG_LEVEL:-DEBUG} ) in your .env ,compose.yml or wherever
-Install any plugin using the hook before_cat_sends_message
-Send anything through rabbithole (?)
-Check for before_cat_sends_message/ before_cat_reads_message calls like below after 
```
DEBUG  cat.mad_hatter.mad_hatter.MadHatter.execute_hook::276 
cheshire_cat_core                | "Executing core_plugin::before_cat_reads_message with priority 0"
```
(spoiler there won't be any)

**Is it really important?**
It's about the "before I read" and "after I read" behavior so...

**Additional context**
It is not normal for the transmission medium below in the stack to produce different results in the stack above.
It's like Instagram making 2FA available only if I'm connected with an ethernet cable.
Furthermore it could generate undefined results when calling the api for other purposes or using anything different from Websocket.

**Are you going to help us fixing the problem?**
Nope i'm already hacking my way.
But I hope my report will be useful for the future vision of the project.

**Some screens**
![Schermata del 2024-06-15 19-03-28(1)](https://github.com/cheshire-cat-ai/core/assets/74120782/4a5c26f2-8442-432b-936f-082044891380)
![Schermata del 2024-06-15 19-34-31](https://github.com/cheshire-cat-ai/core/assets/74120782/f41e029f-92ab-45bb-a665-751d472d175b)
![Schermata del 2024-06-15 19-03-28(2)](https://github.com/cheshire-cat-ai/core/assets/74120782/f8cfabcf-589c-4625-8484-a593180aa30e)

**Comment by valentimarco** [comment]
The hook is design to work only for messages, as suggest the name. [Here the line where we call it](https://github.com/cheshire-cat-ai/core/blob/31cc1ee4456c9a54cefe3c9812d433dd77f4206c/core/cat/looking_glass/stray_cat.py#L307)

**Comment by valentimarco** [comment]
I will check the bug soon!
