### ISSUE TITLE
[BUG] error setting the Google Gemini Embedder

### ISSUE THREAD

**Issue by mardif** [cheshire-cat-ai/core#872]
**Describe the bug**
Trying to set up a Google Gemini Embedder on cheshirecat, setting models/embedding-001 as value.
Clicking on save, I get this error from Google:

```
cheshire_cat_core  | [2024-07-18 09:34:01.535] ERROR  cat.routes.embedder..upsert_embedder_setting::139
cheshire_cat_core  | GoogleGenerativeAIError('Error embedding content: 504 Deadline Exceeded')
cheshire_cat_core  | INFO:     xx.xx.xx.xx:55772 - "PUT /embedder/settings/EmbedderGeminiChatConfig HTTP/1.1" 400 Bad Request
```

**To Reproduce**
Steps to reproduce the behavior (as exampple`):
1. Startup cheshirecat
2. Click on Settings tab and on embedder
3. Set your personal API_KEY
4. Set model as models/embedding-001

**Expected behavior**
Everything should works correctly

**Additional context**
Checking the logs, I see this error:
```
cheshire_cat_core  | [2024-07-18 09:34:01.535] ERROR  cat.routes.embedder..upsert_embedder_setting::139
cheshire_cat_core  | GoogleGenerativeAIError('Error embedding content: 504 Deadline Exceeded')
cheshire_cat_core  | INFO:     xx.xx.xx.xx:55772 - "PUT /embedder/settings/EmbedderGeminiChatConfig HTTP/1.1" 400 Bad Request
```
the problem is raised by cheshire_cat.py line 232 (version 1.6.2):
`embedder_size = len(self.embedder.embed_query("hello world"))`

**Comment by pieroit** [comment]
Fixed on `develop`, coming with the next release :D

**Comment by mardif** [comment]
Thanks @pieroit
