### ISSUE TITLE
[BUG] what is the username and password to log in ?

### ISSUE THREAD

**Issue by higreetings** [cheshire-cat-ai/core#878]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (as exampple`):

**Expected behavior**

**Additional context**

**Comment by pieroit** [comment]
You can either use
`admin` / `admin`
Or
`user` / `user`

In the admin panel you will be soon be able to change those passwords and add other users

**Comment by pieroit** [comment]
![image](https://github.com/user-attachments/assets/e371c994-2158-4d36-a9cf-959860e92765)

Fixed on `develop`.
From next release on, if you only have default users, this message will appear upon login.

Thanks for the feedback
