### ISSUE TITLE
[BUG] Collection aliases problem on Windows

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/core#882]
**Describe the bug**
Recently, I helped a friend installing the Cat on a Windows machine.
I used the same `compose.yml` provided in the [local-cat](https://github.com/cheshire-cat-ai/local-cat/blob/main/compose.yml) repo, removing the Ollama service.
However, the Cat raised an `IndexError`, preventing the server to start.

I tried to reproduce the error on my Ubuntu machine with a fresh installation, but I was not able. 
By the way, I solved commenting [this check](https://github.com/cheshire-cat-ai/core/blob/f14f2c0acebddd3f1f1efb6ba3b161bea45e9e3a/core/cat/memory/vector_memory_collection.py#L63).

**Comment by nickprock** [comment]
Hi @nicola-corbellini ,
I'm trying ti reproduce the error using:
- core repo
- locale Cat .yml
- Windows 11
- rancher

But I can't, my test works.
Could you give other info?

**Comment by nicola-corbellini** [comment]
Hi @nickprock , sorry but I wasn't able to troubleshoot further, since I was remotely guiding a friend.
I just can tell you that he already had a very old installation of the Cat and we installed a new one from scratch.
He was using Docker desktop and I pruned everything multiple times in the attempt to do the fresh installation.
