### ISSUE TITLE
[BUG] permission error cat/data ubuntu 22.04 AND !!!! no users in setting !!!!

### ISSUE THREAD

**Issue by canapaio** [cheshire-cat-ai/core#884]
**Describe the bug**
Permission cat/data error create dile json tct or sqlite in ubuntu 22.04 - lolca ollama - llama3.1 llm

**To Reproduce**
Steps to reproduce the behavior (as exampple`):
1. Clone ccat
cana@tvai:~$ mkdir test171
cana@tvai:~$ cd test171/
cana@tvai:~/test171$ git clone https://github.com/cheshire-cat-ai/core.git
Clone in 'core' in corso...
remote: Enumerating objects: 15520, done.
remote: Counting objects: 100% (2170/2170), done.
remote: Compressing objects: 100% (678/678), done.
remote: Total 15520 (delta 1566), reused 2007 (delta 1459), pack-reused 13350
Ricezione degli oggetti: 100% (15520/15520), 11.46 MiB | 15.98 MiB/s, fatto.
Risoluzione dei delta: 100% (10588/10588), fatto.
cana@tvai:~/test171$ cd core/
cana@tvai:~/test171/core$

2. edir .enc and edit compose.yml for testing docker
a. for .env file see env.txt
[env.txt](https://github.com/user-attachments/files/16591247/env.txt)
b for compose file see comose.txt
[compose.txt](https://github.com/user-attachments/files/16591256/compose.txt)

3. start docker compose up
[docker compose up.txt](https://github.com/user-attachments/files/16591270/docker.compose.up.txt)

4. Open http://ipaddress:1868/admin/ in browser admin admin
5. setup ollama llm local server
![immagine](https://github.com/user-attachments/assets/1252b0e6-0d8a-4d61-8383-998eeb0e49e3)

6. select plugun write file in cat/data exp. CCat Conversation Logger
[log_001.txt](https://github.com/user-attachments/files/16591396/log_001.txt)

9. See error 1 in settings, no users in list
![immagine](https://github.com/user-attachments/assets/37664a6f-70d7-4ed9-a81c-f8d8d462d48c)

10. try send messagge in chat (log error)
[human test.txt](https://github.com/user-attachments/files/16591437/human.test.txt)

11. change folter plugin from sqlite:///cat/data/conv_log.db to sqlite:///conv_log.db (no error) the file created
[human test2.txt](https://github.com/user-attachments/files/16591460/human.test2.txt)

13. if i chage folder permission to 777 ccat work in cat/data corectly

**Comment by canapaio** [comment]
No users in setting in windows docker desktop test

**Comment by pieroit** [comment]
> No users in setting in windows 11 docker desktop test

Can you delete cookies for `localhost`? Maybe different installations are conflicting over those

**Comment by pieroit** [comment]
On the permissions issue, I really have no clue sorry :(
