### ISSUE TITLE
[BUG] user management is missing

### ISSUE THREAD

**Issue by mc9625** [cheshire-cat-ai/core#885]
**Describe the bug**
I have several Cheshire Cat Ai instances, on one installed from scratch with 1.7.1 everything works fine and I have been asked to change my admin password and I have User Management section in Settings. On the others instances, one updated with a git pull from previous version (sorry I can't remember but I guess 1.6.x) and another again installed from scratch to 1.7.1  albeit I have a user login window, I can't change the admin password and I can't see the user management section in settings

**To Reproduce**
Steps to reproduce the behavior (as exampple`):
[actually the error occurs on "updated" Cheshire Cat AI instances]
1. Update to 1.7.x 
2. Login as admin
3. Click on Settings
4. No user management section

**Expected behavior**
After the first login as admin (after the update) the user should be asked to change his password. Also there should be a User management session

**Comment by riccardoniccoliwetechs** [comment]
failed to solve: archive/tar: unknown file mode ?rwxr-xr-x

**Comment by pieroit** [comment]
Cannot replicate this issues, installed from scratch several times in the latest days, this never happened

**Comment by pieroit** [comment]
Confirmed, rebuild the container if you are using the cloned code:
```
docker compose down
docker compose build --no-cache
docker copmose up
```

And remember to clear the browser cache
