### ISSUE TITLE
[Feature] Add new Memory endpoints

### ISSUE THREAD

**Issue by valentimarco** [cheshire-cat-ai/core#889]
**Is your feature request related to a problem? Please describe.**
At the moment, is not possible via RESTAPI:
1. [**GET**] Retrieve all the points from a single collection
2. [**GET**] Retrieve all the points from all collections
3. [**PUT**] Modify a single point from a single collection via **qdrant point's ID**
4. [**POST**] Create a single point in a collection ()
5. [**POST**] Create multiple points in a collection (Can be useful for custom points created outside, example knowleage graphs)
6. [**POST**] Retrieve all points from a single collection by **metadata**
7. [**PUT**] Modify conversation_history
8. [**POST**] Create a custom collection

**Describe the solution you'd like**
For the 7. point where we need to discuss a little, Maybe is time to a little system of cache?

**Additional context**
I need to manipulate memory from outside and is difficult to connect my infrastructure with the cat

**Comment by pieroit** [comment]
> **Is your feature request related to a problem? Please describe.** At the moment, is not possible via RESTAPI:
> 
> 1. [**GET**] Retrieve all the points from a single collection

All the points? Usually APIs have the whole list of records, but paginated

> 2. [**GET**] Retrieve all the points from all collections

> 3. [**PUT**] Modify a single point from a single collection via **qdrant point's ID**

Yes this could be useful

> 4. [**POST**] Create a single point in a collection ()

This endpoint is already present in the latest release, [here](https://github.com/cheshire-cat-ai/core/blob/f14f2c0acebddd3f1f1efb6ba3b161bea45e9e3a/core/cat/routes/memory.py#L154)

> 5. [**POST**] Create multiple points in a collection (Can be useful for custom points created outside, example knowleage graphs)

You mean the same as 4, but batched?

> 6. [**POST**] Retrieve all points from a single collection by **metadata**

Yes this is also useful

> 7. [**PUT**] Modify conversation_history

Agree

> 8. [**POST**] Create a custom collection
> 

Also useful, not sure how complicated it coul be to maintain (es. what happens when embedder changes)

> **Describe the solution you'd like** For the 7. point where we need to discuss a little, Maybe is time to a little system of cache?
> 

Why a cache? It is just an assignation to `StrayCat.working_memory.history`

> **Additional context** I need to manipulate memory from outside and is difficult to connect my infrastructure with the cat

Thanks for these suggestions, some are precious indeed :D
Let's see which points to tackle first and open issues specific for them

**Comment by pieroit** [comment]
(sorry closed for a mistake, reopened)

**Comment by valentimarco** [comment]
> > **Is your feature request related to a problem? Please describe.** At the moment, is not possible via RESTAPI:
> > 
> > 1. [**GET**] Retrieve all the points from a single collection
> 
> All the points? Usually APIs have the whole list of records, but paginated

I forgot to write it xd

> > 5. [**POST**] Create multiple points in a collection (Can be useful for custom points created outside, example knowleage graphs)
> 
> You mean the same as 4, but batched?

Yes

**Comment by MihirKohli** [comment]
Seems like this issue has been resolved

**Comment by pieroit** [comment]
> Seems like this issue has been resolved

Welcome, we need to separate these points in different issues so it is possible to contribute individually on them ;)

**Comment by MihirKohli** [comment]
please do i am more than happy to contribute

**Comment by valentimarco** [comment]
> > Seems like this issue has been resolved
> 
> Welcome, we need to separate these points in different issues so it is possible to contribute individually on them ;)

Or do It all in ones XD

**Comment by valentimarco** [comment]
We can also use the power of markdown and do this ~~already done stone~~ to mark which is done

**Comment by dave90** [comment]
#892 is for the first 2 items:
- [GET] Retrieve all the points from a single collection
- [GET] Retrieve all the points from all collections

**Comment by valentimarco** [comment]
Dev meeting 26/08:
6. Refactor recall: GET to POST and the body will have:
```json
{
 "metadata": {},
"qdrantFilter": {} //qdrant filter is a dict, so you can write the custom filter. By defualt we should support equal for metadata
}
```

**Comment by pieroit** [comment]
@valentimarco @MihirKohli @dave90 @lucagobbi closing this issue as it has been separated in specific ones

Thanks for joining!
