### ISSUE TITLE
Endpoint `POST /memory/recall` with metadata

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#899]
Endpoint `GET /memory/recall` should remain and log a warning that is going to be deprecated in v2.

The new `POST /memory/recall` should accept a json with this format:
```json
{
    "text": "...",
    "k": 34,
    "metadata": {}
}
```

`metadata` for the moment (as in other endpoints) is a simple flat dictionary to search in AND

In the future we may allow another field `vector_db_filter` to be sent directly to Qdrant, with Qdrant filter syntax

**Comment by valentimarco** [comment]
Same as #898, closing the old one to favor this
