### ISSUE TITLE
`CCAT_CORS_ALLOWED_ORIGINS` still does not work

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#906]
**To Reproduce**
Set up a cat with `.env`:
```
CCAT_HTTPS_PROXY_MODE=1
CCAT_CORS_ALLOWED_ORIGINS=https://mydomain.com,https://example.com
```

The Cat still accepts requests from other origins
P.S.: also tried omitting the protocol, no luck

**Comment by kodaline** [comment]
@pieroit how did you set the following env variable? `CCAT_CORS_FORWARDED_ALLOW_IPS`

**Comment by pieroit** [comment]
> @pieroit how did you set the following env variable? `CCAT_CORS_FORWARDED_ALLOW_IPS` That env variable is part of the uvicorn configuration, I don't know but the def value is '*' so maybe you need to set that variable to the list of trusted domains too? Check here https://www.uvicorn.org/settings/
> 
> ps. we might need to revisit the CORS env variables such as the `CCAT_CORS_ALLOWED_ORIGINS`

I did not set it

**Comment by sambarza** [comment]
@pieroit
In my environment this config is enough to get CORS error when I try to consume APIs from something different from http://test.sam.com:5000:
CCAT_CORS_ALLOWED_ORIGINS=https://example.org,https://www.example.org,http://test.sam.com:5000

I'm just looking to API call, there is not CORS check from browser when using web socket
