### ISSUE TITLE
[BUG]Authentication Key Fails When Accessing admin via NGINX Reverse Proxy

### ISSUE THREAD

**Issue by DevilHost069** [cheshire-cat-ai/core#907]
**Describe the bug**
 When using Cheshire-Cat-Core with Docker Compose, the application works fine when accessed directly via the exposed port (e.g., http://localhost:1865/admin). However, when accessing the application through an NGINX reverse proxy (e.g., http://localhost/admin), the authentication key fails with the error "**_Invalid auth key, please try again._**" The same API key works correctly when bypassing NGINX.
![Screenshot from 2024-09-11 10-56-06](https://github.com/user-attachments/assets/e1ac835f-fd7a-424f-b070-2223bddce899)

**To Reproduce** Steps to reproduce the behavior:

Deploy Cheshire-Cat-Core using Docker Compose.
Set up NGINX as a reverse proxy for Cheshire-Cat-Core.
Access the admin interface via http://localhost/admin.
Enter the valid auth key.
See the error: "Invalid auth key, please try again."
Expected behavior The authentication key should work correctly when accessing Cheshire-Cat-Core via the NGINX reverse proxy, just as it works when accessing the app directly through the exposed port.

**Additional context**

NGINX configuration includes proxying for the / and /ws paths.
Cheshire-Cat-Core works without any issues when accessed via the port exposed directly by Docker Compose (http://localhost:1865/admin).
Docker Compose config and NGINX config snippets are provided below:
Docker Compose Config:

`version: '3.4'

networks: 
  kong-net:
    driver: bridge

services:
 nginx-proxy:
        image: public.ecr.aws/nginx/nginx:alpine
        container_name: nginx-reverseproxy
        restart: unless-stopped
        ports:
        - "80:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - kong-net

cheshire-cat-core:
  image: ghcr.io/cheshire-cat-ai/core:1.6.2
  container_name: cheshire_cat_core
  ports:
  - ${CORE_PORT:-1865}:80
  environment:
    PYTHONUNBUFFERED: 1
    WATCHFILES_FORCE_POLLING: true
    CCAT_API_KEY: ${CHESHIRE_ACCESS_TOKEN}
  volumes:
  - ./cheshirecat/static:/app/cat/static:rw
  - ./cheshirecat/plugins:/app/cat/plugins:rw
  - ./cheshirecat/data:/app/cat/data:rw
  networks:
    - kong-net`

_env file_

`CHESHIRE_ACCESS_TOKEN=cataitoken
`

NGINX Config:

`server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://cheshire-cat-core/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
    }
    location /ws {
        proxy_pass http://cheshire-cat-core/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}`

**Comment by pieroit** [comment]
You are using an older admin, now it works via JWT and there is  a proper login form.
Rebuild the docker and clear browser cache

Not sure about the nginx config, we have a few tutorials on reverse proxies (beware of env variables):
https://cheshire-cat-ai.github.io/docs/production/administrators/docker-compose/#cat-reverse-proxy
https://cheshirecat.ai/how-to-use-cheshire-cat-behind-nginx/

**Comment by pieroit** [comment]
Closing the issue, if you encounter any more errors open a new one with the details ;)
