### ISSUE TITLE
Lower default threshold for recall

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#909]
New embedder models (especially multilingual) are way more finegraned and conservative than embedders from a few months ago.

If a threshold of 0.7/0.8 was reasonable then, it is not now and it should be way lower.

It is possible to change thresholds via plugin (e.g. Cat Advanced Tools), but the default ones should also be lowered.

Intervention point: [here](https://github.com/cheshire-cat-ai/core/blob/f14f2c0acebddd3f1f1efb6ba3b161bea45e9e3a/core/cat/looking_glass/stray_cat.py#L211)

**Comment by scicco** [comment]
Hello, I've seen the tag 'good first issue' and I tried to start contributing to this feature.

**Comment by pieroit** [comment]
Merging soon
