### ISSUE TITLE
[BUG] If the Cat starts without an internet connection, it wipes the memories

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#919]
A nasty one folks

**Comment by alfredotoselli** [comment]
Cannot reproduce with the following steps:

1. Start the cat
2. Config OpenAI LLM and Embedder
3. A couple of message exchange and a document upload
4. Shut down the cat
5. Turn off internet connection
6. Start the cat -> ConnectionError
7. Turn on internet
8. Restart the container
9. Memories are still there (embedder hasn't changed as well)

**Comment by pieroit** [comment]
Thanks for checking @alfredotoselli , closing this.
I guess it is the specific embedder service I was using, it makes a request at startup (then it fails because no internet) and the Cat sets the default embedder.
