### ISSUE TITLE
[BUG] Azure Container App Network Error

### ISSUE THREAD

**Issue by Nopesound** [cheshire-cat-ai/core#920]
**Describe the bug**
I created an azure container app, and I loaded the image ghcr.io/cheshire-cat-ai/core:latest inside it, when I run it everything is fine, I can correctly configure the LLM and the embedded (ChatGPT) but when I try to upload a document I receive the error message "network error", I tried both with a document in markup format and a pdf document.

**To Reproduce**
1. I start the azure container app
2. I log in with Admin
3. In the home I click on the spark and try to upload a document
4. It displays the error "network error"

**Expected behavior**
That it would load the document and that I could start querying Cheshire on the content of the document

**Additional context**
I encounter the same problem in the plugins tab. 

Maybe I'm doing some configuration wrong.

**Comment by valentimarco** [comment]
Hi, thx for describing the issue! Can you try using [ccat_https_proxy_mode Env variable](https://cheshire-cat-ai.github.io/docs/production/administrators/env-variables/#ccat_https_proxy_mode)?

**Comment by Nopesound** [comment]
Hi, I have been using a simple Azure Container App. Is it possible to use this resource for Cheshire? I am starting to have some doubts..

**Comment by valentimarco** [comment]
Sorry but i am not aware of this service from azure. The max I have used is k3s in a vps and works flawlessly.
Maybe @ggiallo28 can help, i tried the cat on aws lambda
and @cristianorevil that use azure stuff

**Comment by ggiallo28** [comment]
Hello @Nopesound, is the "network error" visible on the fronted right?
Can you share your browser network events? And, if you have access to it, can you share Azure Container App logs?

**Comment by cristianorevil** [comment]
How you call the url of the cat, in https? If yes yo need to setup correctly the env for the container:

# Decide to use https / wss secure protocols
CCAT_CORE_USE_SECURE_PROTOCOLS=true
# Uvicorn and FastAPI operating behind https proxy
CCAT_HTTPS_PROXY_MODE=true
# Comma separated list of IPs to trust with proxy headers. A wildcard '*' means always trust.
CCAT_CORS_FORWARDED_ALLOW_IPS="*"

**Comment by Nopesound** [comment]
Thanks @cristianorevil, it works for me. Just one thing, when I restart the container app everything in my cheshire is deleted. Documents, apikey, conversation. Is it possible to save this information in another location? For example a storage account.
