### ISSUE TITLE
REST api for chat

### ISSUE THREAD

**Issue by mastrogiovanni** [cheshire-cat-ai/core#922]
**Is your feature request related to a problem? Please describe.**
In out production environment we have existing codebase and stateless microservices.
We are able to interact with the Cat via websocket but the process is not so lean:
we need to open a websocket connection send a message, receive the responses and 
then close the websocket once the final message is received.
We would like to have a cheshire REST endpoint that given a text return the final response 
only to the caller

**Describe the solution you'd like**
We need a simple REST endpoint to make chat interaction: text to response

**Describe alternatives you've considered**
We already use to open a socket send a message, discard all the token messages and once received the final response we close the socket

**Additional context**
The cat currently raise an exception if a websocket is missing.
This feature need to configure the StrayCat to avoid sending tokens

**Comment by valentimarco** [comment]
Thx for opening the issue however there is another issue that talks about this topic with particular focus on adding what you did in the PR. 
I close this and link to you the other issue: #921
