### ISSUE TITLE
Log-in button stays greyed out after inputting username and pswd

### ISSUE THREAD

**Issue by ptrpla** [cheshire-cat-ai/core#926]
**Is your feature request related to a problem? Please describe.**
On the Admin log-in page, after you add a username and pswd the log-in. 

**Describe the solution you'd like**
Generally, from a UX point of view, it would be ideal if after adding the username and pswd the button should change color (to black based on the current design) to show the user that they can click to log-in. If it stays greyed out it seems as if the input is incorrect or missing i.e. I cannot go to the next action (logging in).

**Additional context**
Attached a screenshot:
<img width="348" alt="Screenshot 2024-10-01 at 18 05 09" src="https://github.com/user-attachments/assets/926dec46-1e9f-4708-a0e6-04b1e1879dd7">

**Comment by aaronbesc** [comment]
Would you give me the chance to work on this issue? Thank you!
