### ISSUE TITLE
Invalid credentials message moved above the log-in button

### ISSUE THREAD

**Issue by ptrpla** [cheshire-cat-ai/core#927]
**Is your feature request related to a problem? Please describe.**
When you input invalid credentials, the message to warn the user is displayed at the bottom of the page and doesn't catch immediately the eye.

**Describe the solution you'd like**
From a UX stand point, the invalid credentials message should be as visible as possible next to the log-in button to immediately catch the user's eye. 

**Additional context**
Screenshot attached:
<img width="547" alt="Screenshot 2024-10-01 at 18 05 31" src="https://github.com/user-attachments/assets/c51b8c89-b03a-4ad3-b12b-32ff4f11704e">

**Comment by pieroit** [comment]
@ptrpla the login page is offered directly from core, so moved some of the issues here
thanks for taking the time to evaluate and give feedback!

**Comment by EKS2003** [comment]
Hi I would like to give a try to this issue!
