### ISSUE TITLE
[BUG] Startup process processed twice

### ISSUE THREAD

**Issue by sambarza** [cheshire-cat-ai/core#935]
**Describe the bug**
The startup process in main.py is being executed twice.

**To Reproduce**
1. Add `print("STARTING", __name__)` in the main.py file just after the imports
2. Run the application
3. In the console you should see the following:
```
cheshire_cat_core  | STARTING __main__
cheshire_cat_core  | STARTING cat.main
```

**Additional context**
uvicorn.run() is importing main.py again, causing the startup process to be triggered twice:
```python
    uvicorn.run(
        "cat.main:cheshire_cat_api",
        host="0.0.0.0",
        port=80,
        use_colors=True,
        log_level=get_env("CCAT_LOG_LEVEL").lower(),
        **debug_config,
        **proxy_pass_config,
    )
```

**Comment by valentimarco** [comment]
Should we change with [fastapi-cli](https://fastapi.tiangolo.com/fastapi-cli/)??

**Comment by sambarza** [comment]
Maybe something simpler, just move the `cheshire_cat_api` FastAPI initialization to a separate file, and keep only the `uvicorn.run` in main.

**Comment by pieroit** [comment]
Merging soon
