### ISSUE TITLE
Custom LLM endpoint error during http POST request

### ISSUE THREAD

**Issue by giuseppefrusso** [cheshire-cat-ai/core#941]
Hello, 
I cannot use a custom LLM that I download on the Internet. 

In particular, I used this llamafile: https://huggingface.co/Mozilla/TinyLlama-1.1B-Chat-v1.0-llamafile/resolve/main/TinyLlama-1.1B-Chat-v1.0.F16.llamafile?download=true

I have Windows, so I renamed the file to .exe and I execute and it seems to work on the URL localhost:8080, but when I load this URL on Cheshire Cat AI interface, the cat cannot work because of the error in the title.

![immagine](https://github.com/user-attachments/assets/fe79295b-90eb-4b18-a486-283c590f6bde)

**Comment by pieroit** [comment]
You need an adapter for llamafiles, via plugin

**Comment by valentimarco** [comment]
You can use the openai compatibile llm setting to connect your llamafile model. Check the llamafile docs to start the model in server mode.
