### ISSUE TITLE
[Feature] Install multiple plugins at once.

### ISSUE THREAD

**Issue by razvanab** [cheshire-cat-ai/core#944]
**Is your feature request related to a problem? Please describe.**

Installing plugins one by one and the fact that the page goes back to the first one in the list after each install of a plugin.

**Describe the solution you'd like**

Select multiple plugins to install at once.

**Describe alternatives you've considered**

Give up

**Additional context**

**Comment by pieroit** [comment]
Maybe in the future,
At this point in time you can easily automate plugin installation, as we have the full endpoints to manage plugins.

I see a point in the aadmin reloading the page and not allowing easy scrolling, but that is a specific issue to post on the admin.

Thanks for your suggestion @razvanab

**Comment by razvanab** [comment]
I see.
Thanks for the reply.
