### ISSUE TITLE
[Feature] Add Authorization to Tools

### ISSUE THREAD

**Issue by michaelsaccone** [cheshire-cat-ai/core#947]
### About
We discussed about controlling settings, sessions and other administrative data in a conversational way, as an Admin.
It would be useful, then, to add an Authorization layer to Tools.

### Solution
When defining a tool, you can define in the decorator the permission level a user should have in order to call that tool.
And in the Tool retrieval part, we filter the tools by permissions before proposing them to the LLM.

If the idea seem's interesting, I can work on it

**Comment by pieroit** [comment]
Isn't it way easier to check permissions inside the tool?
`cat.user_id` and there should be soon a  `cat.user_info` / `cat.user`

thanks for suggesting @michaelsaccone

**Comment by michaelsaccone** [comment]
@pieroit Well, if you do it in the Tool, then the tool has already been called.
That means you can only say to the user that he has no permission to do so.
If you check a priori as I'm suggesting, then the users cannot even see that tool, and can instead call other tools, if there are inherent tools with similar description!

**Comment by lucagobbi** [comment]
What about using the `agent_allowed_tools` hook?

Example:

```python
@hook
def agent_allowed_tools(allowed_tools, cat):
    if cat.user_id != "admin":
        allowed_tools.remove("admin_only_tool")
    return allowed_tools
```

**Comment by sambarza** [comment]
I see that 'authorization checks' are not an easy task to standardize. Authorization IMHO requires a lot of flexibility, and the hook `agent_allowed_tool` seems to provide that flexibility. I’m thinking to all the scopes I had to implement in the past 😖

**Comment by michaelsaccone** [comment]
Imagine a scenario where more devs write different admin tools to do different things.
Then each of them must add another step to the allowed_tools hook that gets chained.
This is cool if we don't want - or don't have time - to touch the codebase.
A better approach in my opinion is to add a simple list of permission to a tool (in the decorator), that we put in the metadata. When we collect the allowed tools, we just query the vectors with the permissions the current user has and we automatically get all the tools that the current user can call.

**Comment by lucagobbi** [comment]
some questions arise: 
1. how can i handle authorization for plugins that are not under my direct control, third party plugins? e.g. plugin X requires a role `x_admin` I must map my admin users to have a role `x_admin`? 

2. What if the authorization depends not only on a mere role but on other conditions? e.g. you can use this tool only if you have the role "admin" AND your sending a msg during office hours

**Comment by pieroit** [comment]
Thanks for chiping in @michaelsaccone @sambarza @lucagobbi .
It is way too early (and dangerous) to work on this, closing this issue.

Once we have a better idea on roles and how to propagate and customize them all around the framework, we think about their declination for tools, hooks and whatever. This kind of feat cannot be worked bottom up unfortunately.
