### ISSUE TITLE
[BUG] Potential security hole in the Authorization handlers (and the authorization chain)

### ISSUE THREAD

**Issue by matteocacciola** [cheshire-cat-ai/core#948]
**Describe the bug**
I guess [this](https://github.com/cheshire-cat-ai/core/blob/f51a40e2208efaa740f79bd156b02cf41ec35c43/core/cat/factory/custom_auth_handler.py#L112) block represents a security hole. I am not discussing about dismissing the core auth handler. I am just suggesting to remove that block. Let me explain why.

Let me suppose that you want to authorize admins by an API key, and regular users by tokens. Then, that block is superfluous there.

Let me now suppose that **do not set any API key** because you want to authorize admins as well as users by tokens (it can happen in real world scenarios). Then, that block is a security hole.

P.S. I understand that the documentation is clear on this point, but the usage guidelines make sense because not following them results in a unusable package (because of the robustness of the code). Here, however, I can use the CheshireCat even if I don't follow the guidelines, which is really strange.

**To Reproduce**
Try to create a test with simple `client` (no `secure_client`) and see that you can interact with whatever endpoint, which is incorrect. There are lots of tests actually in the codebase like that.

**Expected behavior**
Remove that block.

**Comment by pieroit** [comment]
If you do NOT set keys, the installation will be wide open.
That is the intended behaviour, and the reason tests are done with `client`.
What is the problem about it?

Once you set keys and jwt secret as the docs says, you must auth correctly and if you have a custom auth handler the core one will be closed.

To sum up: when you go to production you **must set api keys and jwt secret**.

**Comment by matteocacciola** [comment]
@pieroit , so it is **wide open** but I **must set** in production? Either wide open or must set, imho

**Comment by pieroit** [comment]
> @pieroit , so it is **wide open** but I **must set** in production? Either wide open or must set, imho. What about if I don't want to set the API key because I want to use JWT based authorizations. Should I assume it is a restriction on the usage of Cheshire Cat?

Yes consider it a restriction.
You want to secure installation? Set api keys and jwt secret.
I know it is opinionated, may change in v2 if a better proposal comes along ;)

**Comment by matteocacciola** [comment]
> Yes consider it a restriction.

Good to know

>  You want to secure installation? Set api keys and jwt secret.

Fine, I made my job by reporting the security hole.
