### ISSUE TITLE
Make custom `BaseAuthHandler` and `BaseAgent` classes sync

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#958]
No more async in core classes and plugin primitives, as it is not necessary and the performance advantage is not worth the maintaining effort. See [here](https://github.com/cheshire-cat-ai/core/pull/957#issuecomment-2441503356) for more context.

Take away `async/await` from auth handlers and agent classes.
If somebody is available to do it, comment and I will assign the issue.

Hugs

**Comment by lucagobbi** [comment]
I have a PR ready for this, but I have one question: unlike the BaseAgent, which is entirely internal, removing async from the auth handlers would introduce a breaking change for developers who have implemented custom auth handlers async. Should we merge it in v2?

**Comment by pieroit** [comment]
> I have a PR ready for this, but I have one question: unlike the BaseAgent, which is entirely internal, removing async from the auth handlers would introduce a breaking change for developers who have implemented custom auth handlers async. Should we merge it in v2?

Let's break it now, I'll merge and give note about this when 1.8 is released

Thanks @lucagobbi
