### ISSUE TITLE
`plugin.json` includes `min_version` and `max_version` keys

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#960]
Have in `plugin.json` some indication of the versions of `core` which are compatible with the plugin itself.
It will be up to the plugin developer to keep track of compatible versions.

Same update should be reflected on the [registry](https://github.com/cheshire-cat-ai/plugins-backend).

**Comment by alfredotoselli** [comment]
I could take this.
We want it just as an info or with enforcement as well? Like plugin activation fails if compatible versions are specified and not matching with the core version in use?

**Comment by pieroit** [comment]
Thanks @alfredotoselli 
Step 1: have it as an info in `plugin.json`
Step 2: let's talk about enforcing or not here or in a meeting, not sure about it
