### ISSUE TITLE
[BUG] Cannot run cat from develop branch

### ISSUE THREAD

**Issue by giuseppe-coco** [cheshire-cat-ai/core#986]
**Describe the bug**
I cannot run the cat from `develop` branch.

**To Reproduce**
Steps to reproduce the behavior (as exampple`):
1. Go to `develop` branch
2. Go inside cat root folder
3. Run `docker compose up`
5. See error
`
Giuseppe@ip-10-77-77-170 ~/developing/cheshire-cat-ai-core $ docker compose up
[+] Running 1/0
 ✔ Container cheshire_cat_core  Created                                                                                                            0.0s 
Attaching to cheshire_cat_core
cheshire_cat_core  | INFO:     Will watch for changes in these directories: ['/app']
cheshire_cat_core  | INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
cheshire_cat_core  | INFO:     Started reloader process [1] using WatchFiles
cheshire_cat_core  | Process SpawnProcess-1:
cheshire_cat_core  | Traceback (most recent call last):
cheshire_cat_core  |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
cheshire_cat_core  |     self.run()
cheshire_cat_core  |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
cheshire_cat_core  |     self._target(*self._args, **self._kwargs)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
cheshire_cat_core  |     target(sockets=sockets)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
cheshire_cat_core  |     return asyncio.run(self.serve(sockets=sockets))
cheshire_cat_core  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
cheshire_cat_core  |     return loop.run_until_complete(main)
cheshire_cat_core  |   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
cheshire_cat_core  |     config.load()
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 477, in load
cheshire_cat_core  |     self.loaded_app = import_from_string(self.app)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
cheshire_cat_core  |     raise exc from None
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
cheshire_cat_core  |     module = importlib.import_module(module_str)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
cheshire_cat_core  |     return _bootstrap._gcd_import(name[level:], package, level)
cheshire_cat_core  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
cheshire_cat_core  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
cheshire_cat_core  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
cheshire_cat_core  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
cheshire_cat_core  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
cheshire_cat_core  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
cheshire_cat_core  |   File "/app/cat/startup.py", line 13, in <module>
cheshire_cat_core  |     from cat.routes import (
cheshire_cat_core  |   File "/app/cat/routes/base.py", line 6, in <module>
cheshire_cat_core  |     from cat.auth.connection import HTTPAuth
cheshire_cat_core  |   File "/app/cat/auth/connection.py", line 23, in <module>
cheshire_cat_core  |     from cat.looking_glass.stray_cat import StrayCat
cheshire_cat_core  |   File "/app/cat/looking_glass/stray_cat.py", line 16, in <module>
cheshire_cat_core  |     from cat.looking_glass.cheshire_cat import CheshireCat
cheshire_cat_core  |   File "/app/cat/looking_glass/cheshire_cat.py", line 21, in <module>
cheshire_cat_core  |     from cat.factory.llm import LLMDefaultConfig
cheshire_cat_core  |   File "/app/cat/factory/llm.py", line 10, in <module>
cheshire_cat_core  |     from langchain_anthropic import ChatAnthropic
cheshire_cat_core  | ModuleNotFoundError: No module named 'langchain_anthropic'
`

**Comment by pieroit** [comment]
@giuseppe-coco try to rebuild the container

`docker compose build --no-cache`

Let me know

**Comment by giuseppe-coco** [comment]
It works now! 
Thanks @pieroit !!
